from django.urls import path
from .views import InternalLoginView, InternalTokenRefreshView, current_user, internal_health
from .system_views import (
    DepartmentCollectionView,
    DepartmentDetailView,
    PermissionCollectionView,
    RoleCollectionView,
    RoleDetailView,
    RolePermissionView,
    RoleScopeOptionsView,
    RoleStatusView,
    SecurityOperationsView,
    UserCollectionView,
    UserDetailView,
    UserPasswordResetView,
    UserRoleOptionCollectionView,
    UserRoleView,
    UserStatusView,
    TenantCollectionView,
    TenantDetailView,
)


urlpatterns = [
    path("health/", internal_health, name="internal-health"),
    path("auth/login/", InternalLoginView.as_view(), name="internal-auth-login"),
    path("auth/refresh/", InternalTokenRefreshView.as_view(), name="internal-auth-refresh"),
    path("auth/me/", current_user, name="internal-auth-me"),
    path("system/tenants/", TenantCollectionView.as_view(), name="system-tenant-collection"),
    path("system/tenants/<int:pk>/", TenantDetailView.as_view(), name="system-tenant-detail"),
    path("system/departments/", DepartmentCollectionView.as_view(), name="system-department-collection"),
    path("system/departments/<int:pk>/", DepartmentDetailView.as_view(), name="system-department-detail"),
    path("system/users/", UserCollectionView.as_view(), name="system-user-collection"),
    path("system/users/<int:pk>/", UserDetailView.as_view(), name="system-user-detail"),
    path("system/users/<int:pk>/status/", UserStatusView.as_view(), name="system-user-status"),
    path("system/users/<int:pk>/password-reset/", UserPasswordResetView.as_view(), name="system-user-password-reset"),
    path("system/users/<int:pk>/roles/", UserRoleView.as_view(), name="system-user-roles"),
    path("system/user-role-options/", UserRoleOptionCollectionView.as_view(), name="system-user-role-options"),
    path("system/roles/", RoleCollectionView.as_view(), name="system-role-collection"),
    path("system/role-scope-options/", RoleScopeOptionsView.as_view(), name="system-role-scope-options"),
    path("system/roles/<int:pk>/", RoleDetailView.as_view(), name="system-role-detail"),
    path("system/roles/<int:pk>/status/", RoleStatusView.as_view(), name="system-role-status"),
    path("system/roles/<int:pk>/permissions/", RolePermissionView.as_view(), name="system-role-permissions"),
    path("system/permissions/", PermissionCollectionView.as_view(), name="system-permission-collection"),
    path("system/security-operations/", SecurityOperationsView.as_view(), name="system-security-operations"),
]
