# Generated by Django 5.2.16 on 2026-08-08 09:32



from django.db import migrations, models


def _backfill_order_snapshots(apps, schema_editor):
    """Promote any legacy singular/embedded snapshot into stable lists.

    Existing allocations have the old ``order_id_snapshot`` columns and may
    already carry the richer order data in ``snapshot``.  The migration is
    intentionally conservative: it never invents an order and leaves an
    empty list for rows whose historical snapshot had no order identity.
    """

    Allocation = apps.get_model("consolidation", "ConsolidationBoxAllocation")
    for allocation in Allocation.objects.all().iterator():
        snapshot = allocation.snapshot if isinstance(allocation.snapshot, dict) else {}
        order_ids = snapshot.get("order_ids") or snapshot.get("order_ids_snapshot") or []
        order_nos = snapshot.get("order_nos") or snapshot.get("order_nos_snapshot") or []
        if not order_ids and allocation.order_id_snapshot:
            order_ids = [allocation.order_id_snapshot]
        if not order_nos and allocation.order_no_snapshot:
            order_nos = [allocation.order_no_snapshot]
        normalized_ids = []
        for value in order_ids:
            if not value:
                continue
            try:
                normalized_ids.append(int(value))
            except (TypeError, ValueError):
                # A malformed legacy snapshot must not abort the entire
                # migration; the physical singular column remains available
                # for manual audit of that row.
                continue
        normalized_ids = sorted(set(normalized_ids))
        normalized_nos = sorted({str(value) for value in order_nos if value})
        if allocation.order_ids_snapshot != normalized_ids or allocation.order_nos_snapshot != normalized_nos:
            allocation.order_ids_snapshot = normalized_ids
            allocation.order_nos_snapshot = normalized_nos
            allocation.save(update_fields=["order_ids_snapshot", "order_nos_snapshot"])


class Migration(migrations.Migration):


    dependencies = [

        ('consolidation', '0001_initial'),

    ]



    operations = [

        migrations.AddField(

            model_name='consolidationboxallocation',

            name='order_ids_snapshot',

            field=models.JSONField(blank=True, default=list),

        ),

        migrations.AddField(
            model_name='consolidationboxallocation',
            name='order_nos_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(_backfill_order_snapshots, migrations.RunPython.noop),
    ]
