# Generated by Django 5.2.16 on 2026-08-08 10:08



from django.db import migrations, models





class Migration(migrations.Migration):



    dependencies = [

        ('consolidation', '0002_consolidationboxallocation_order_ids_snapshot_and_more'),

    ]



    operations = [

        migrations.AlterField(

            model_name='consolidationevent',

            name='action',

            field=models.CharField(choices=[('site_create', 'Create site'), ('site_update', 'Update site'), ('site_deactivate', 'Deactivate site'), ('create', 'Create consolidation'), ('update', 'Update consolidation'), ('allocate', 'Allocate box'), ('remove', 'Remove box'), ('release', 'Release consolidation'), ('receive', 'Receive box'), ('handover_submit', 'Submit handover evidence'), ('exception', 'Mark exception'), ('controlled_release', 'Controlled release'), ('ready', 'Ready for shipment'), ('cancel', 'Cancel consolidation')], max_length=40),

        ),

    ]
