# Generated by Django 5.2.16 on 2026-08-08 10:35

import json

from django.db import migrations, models


def _legacy_evidence_ids(raw):
    """Conservatively decode the old scalar/JSON compatibility column."""
    value = str(raw or "").strip()
    if not value:
        return []
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError, json.JSONDecodeError):
        parsed = value
    values = parsed if isinstance(parsed, list) else [parsed]
    normalized = set()
    for item in values:
        try:
            number = int(item)
        except (TypeError, ValueError):
            continue
        if number > 0:
            normalized.add(number)
    return sorted(normalized)[:9]


def backfill_evidence_ids(apps, schema_editor):
    Allocation = apps.get_model("consolidation", "ConsolidationBoxAllocation")
    for allocation in Allocation.objects.using(schema_editor.connection.alias).exclude(
        handover_evidence_id=""
    ).iterator():
        evidence_ids = _legacy_evidence_ids(allocation.handover_evidence_id)
        if evidence_ids:
            Allocation.objects.using(schema_editor.connection.alias).filter(
                pk=allocation.pk
            ).update(evidence_ids=evidence_ids)


def reverse_evidence_ids(apps, schema_editor):
    Allocation = apps.get_model("consolidation", "ConsolidationBoxAllocation")
    for allocation in Allocation.objects.using(schema_editor.connection.alias).iterator():
        values = allocation.evidence_ids if isinstance(allocation.evidence_ids, list) else []
        if values:
            Allocation.objects.using(schema_editor.connection.alias).filter(
                pk=allocation.pk
            ).update(handover_evidence_id=str(values[0]))


class Migration(migrations.Migration):
    dependencies = [
        ("consolidation", "0003_alter_consolidationevent_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="consolidationboxallocation",
            name="evidence_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_evidence_ids, reverse_evidence_ids),
    ]
