services:
  backend:
    image: saas-collab-backend:v2.44.54
  celery:
    image: saas-collab-backend:v2.44.54
  celery-beat:
    image: saas-collab-backend:v2.44.54
  frontend:
    image: saas-collab-frontend:v2.44.54
