FROM saas-collab-frontend:v2.44.45

ARG RELEASE_REVISION
LABEL org.opencontainers.image.version="2.44.46"
LABEL org.opencontainers.image.revision="${RELEASE_REVISION}"

RUN rm -rf /usr/share/nginx/html/*
COPY dist/ /usr/share/nginx/html/
