# Generated by Django 5.2.16 on 2026-07-16 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('purchase', 'Purchase'), ('price', 'Price'), ('listing', 'Listing'), ('clearance', 'Clearance'), ('finance', 'Finance'), ('report_export', 'Report export')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=80)),
                ('business_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'approval_type', 'status'], name='idx_workflow_approval')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_workflow_approval_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='BusinessException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('product', 'Product'), ('purchasing', 'Purchasing'), ('supplier', 'Supplier'), ('listing', 'Listing'), ('finance', 'Finance'), ('rpa', 'RPA'), ('integration', 'Integration')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('business_type', models.CharField(blank=True, max_length=80)),
                ('business_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_workflow_exceptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_exceptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_exceptions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'module', 'status'], name='idx_workflow_exception')],
            },
        ),
        migrations.CreateModel(
            name='CollaborationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('wechat', 'WeChat mock'), ('feishu', 'Feishu mock')], max_length=20)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('masked_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_confirmation', max_length=30)),
                ('decision_note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_workflow_collaboration_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_collaboration_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-received_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'channel', 'status'], name='idx_workflow_collab')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'channel', 'event_id'), name='uniq_workflow_collab_event')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=40)),
                ('resource_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('masked_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_audit_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='idx_workflow_audit')],
            },
        ),
    ]
