# Generated by Django 5.2.16 on 2026-07-17 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowauditevent',
            options={'base_manager_name': 'objects', 'ordering': ['tenant_id', 'created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='workflowauditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_audit_events', to='tenants.tenant'),
        ),
    ]
