# Generated by Django 5.2.17 on 2026-10-03 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workflows', '0002_alter_workflowauditevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexception',
            name='report_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businessexception',
            name='report_request_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='businessexception',
            name='module',
            field=models.CharField(choices=[('product', 'Product'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchasing', 'Purchasing'), ('supplier', 'Supplier'), ('listing', 'Listing'), ('finance', 'Finance'), ('rpa', 'RPA'), ('integration', 'Integration')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='businessexception',
            constraint=models.UniqueConstraint(fields=('tenant', 'created_by', 'report_request_key'), name='uniq_report_exception_request'),
        ),
    ]
