STANDARD_COLORS = (
    ("black", "黑色"), ("white", "白色"), ("gray", "灰色"), ("dark-gray", "深灰色"),
    ("light-gray", "浅灰色"), ("silver", "银色"), ("charcoal", "炭灰色"), ("graphite", "石墨色"),
    ("red", "红色"), ("dark-red", "深红色"), ("light-red", "浅红色"), ("scarlet", "猩红色"),
    ("crimson", "绯红色"), ("burgundy", "酒红色"), ("maroon", "栗红色"), ("rose", "玫瑰色"),
    ("pink", "粉色"), ("hot-pink", "亮粉色"), ("light-pink", "浅粉色"), ("dusty-pink", "灰粉色"),
    ("coral", "珊瑚色"), ("salmon", "鲑鱼色"), ("magenta", "品红色"), ("fuchsia", "紫红色"),
    ("orange", "橙色"), ("dark-orange", "深橙色"), ("light-orange", "浅橙色"), ("apricot", "杏色"),
    ("peach", "桃色"), ("amber", "琥珀色"), ("yellow", "黄色"), ("lemon", "柠檬黄"),
    ("gold", "金色"), ("mustard", "芥末黄"), ("khaki", "卡其色"), ("beige", "米色"),
    ("cream", "奶油色"), ("ivory", "象牙白"), ("champagne", "香槟色"), ("camel", "驼色"),
    ("brown", "棕色"), ("dark-brown", "深棕色"), ("light-brown", "浅棕色"), ("chocolate", "巧克力色"),
    ("coffee", "咖啡色"), ("tan", "棕褐色"), ("taupe", "灰褐色"), ("copper", "铜色"),
    ("green", "绿色"), ("dark-green", "深绿色"), ("light-green", "浅绿色"), ("lime", "青柠色"),
    ("olive", "橄榄绿"), ("mint", "薄荷绿"), ("emerald", "祖母绿"), ("forest-green", "森林绿"),
    ("sage", "鼠尾草绿"), ("army-green", "军绿色"), ("teal", "蓝绿色"), ("turquoise", "绿松石色"),
    ("cyan", "青色"), ("aqua", "水蓝色"), ("blue", "蓝色"), ("dark-blue", "深蓝色"),
    ("light-blue", "浅蓝色"), ("sky-blue", "天蓝色"), ("royal-blue", "宝蓝色"), ("navy", "藏青色"),
    ("denim", "牛仔蓝"), ("cobalt", "钴蓝色"), ("indigo", "靛蓝色"), ("lavender", "薰衣草色"),
    ("purple", "紫色"), ("dark-purple", "深紫色"), ("light-purple", "浅紫色"), ("violet", "紫罗兰色"),
    ("lilac", "丁香紫"), ("plum", "梅子色"), ("mauve", "藕紫色"), ("multicolor", "多色"),
    ("transparent", "透明"), ("natural", "本色"), ("fluorescent", "荧光色"), ("metallic", "金属色"),
)
