from django.urls import path

from .views import (
    product_bundle_create,
    product_bundle_image_cache,
    product_bundle_detail,
    product_bundle_availability,
    product_bundle_migration_preview,
    product_bundle_migration_confirm,
    product_bundle_return_suggestion,
    product_bundle_component_collection,
    product_bundle_component_detail,
    product_category_collection,
    product_attribute_collection,
    product_attribute_detail,
    product_category_detail,
    product_category_attributes,
    product_category_background_colors,
    product_coding_options,
    product_color_collection,
    product_color_detail,
    import_standard_product_colors,
    product_detail_collection,
    product_detail_export,
    product_detail_bulk_update,
    product_detail_bulk_cache_images,
    freeze_product_spu_code,
    confirm_status_recommendation,
    evaluate_mock_status_view,
    product_research_collection,
    product_research_detail,
    product_sku_collection,
    product_sku_detail,
    product_sku_image,
    product_legacy_collection,
    product_legacy_detail,
    product_legacy_generate,
    product_spu_collection,
    product_spu_export,
    product_spu_recode,
    product_spu_bulk_update,
    product_spu_detail,
    reject_status_recommendation,
    status_recommendation_collection,
    status_recommendation_detail,
    status_transition_collection,
)
from .action_views import product_sku_status_action, product_spu_status_action
from .batch_views import product_sku_batch_create
from .cost_views import (
    product_cost_backfill_preview,
    product_cost_backfill_execute,
    product_cost_collection,
    product_cost_warehouses,
    product_cost_confirm,
    product_cost_create,
    product_cost_import_confirm,
    product_cost_import_preview,
)


urlpatterns = [
    path("costs/", product_cost_collection, name="product-cost-collection"),
    path("costs/warehouses/", product_cost_warehouses, name="product-cost-warehouses"),
    path("costs/versions/", product_cost_create, name="product-cost-create"),
    path("costs/backfill-preview/", product_cost_backfill_preview, name="product-cost-backfill-preview"),
    path("costs/backfill-execute/", product_cost_backfill_execute, name="product-cost-backfill-execute"),
    path("costs/versions/<int:pk>/confirm/", product_cost_confirm, name="product-cost-confirm"),
    path("costs/import/preview/", product_cost_import_preview, name="product-cost-import-preview"),
    path("costs/import/confirm/", product_cost_import_confirm, name="product-cost-import-confirm"),
    path("coding-options/", product_coding_options, name="product-coding-options"),
    path("attributes/", product_attribute_collection, name="product-attribute-collection"),
    path("attributes/<int:pk>/", product_attribute_detail, name="product-attribute-detail"),
    path("categories/", product_category_collection, name="product-category-collection"),
    path("categories/<int:pk>/", product_category_detail, name="product-category-detail"),
    path("categories/<int:pk>/attributes/", product_category_attributes, name="product-category-attributes"),
    path("category-background-colors/", product_category_background_colors, name="product-category-background-colors"),
    path("colors/", product_color_collection, name="product-color-collection"),
    path("colors/<int:pk>/", product_color_detail, name="product-color-detail"),
    path("colors/import-standard/", import_standard_product_colors, name="product-color-import-standard"),
    path("research/", product_research_collection, name="product-research-collection"),
    path("research/<int:pk>/", product_research_detail, name="product-research-detail"),
    path("spus/", product_spu_collection, name="product-spu-collection"),
    path("spus/export/", product_spu_export, name="product-spu-export"),
    path("spus/recode/", product_spu_recode, name="product-spu-recode"),
    path("spus/bulk-update/", product_spu_bulk_update, name="product-spu-bulk-update"),
    path("spus/<int:pk>/", product_spu_detail, name="product-spu-detail"),
    path("spus/<int:pk>/status/", product_spu_status_action, name="product-spu-status"),
    path("spus/<int:pk>/freeze-code/", freeze_product_spu_code, name="product-spu-freeze-code"),
    path("skus/", product_sku_collection, name="product-sku-collection"),
    path("skus/batch/", product_sku_batch_create, name="product-sku-batch-create"),
    path("skus/<int:pk>/", product_sku_detail, name="product-sku-detail"),
    path("skus/<int:pk>/status/", product_sku_status_action, name="product-sku-status"),
    path("skus/<int:pk>/image/", product_sku_image, name="product-sku-image"),
    path("details/", product_detail_collection, name="product-detail-collection"),
    path("details/export/", product_detail_export, name="product-detail-export"),
    path("details/bulk-update/", product_detail_bulk_update, name="product-detail-bulk-update"),
    path("details/images/bulk-cache/", product_detail_bulk_cache_images, name="product-detail-bulk-cache-images"),
    path("legacy-items/", product_legacy_collection, name="product-legacy-collection"),
    path("legacy-items/<int:pk>/", product_legacy_detail, name="product-legacy-detail"),
    path("legacy-items/<int:pk>/generate/", product_legacy_generate, name="product-legacy-generate"),
    path("bundles/create/", product_bundle_create, name="product-bundle-create"),
    path("bundles/<int:sku_id>/image-cache/", product_bundle_image_cache, name="product-bundle-image-cache"),
    path("bundles/<int:sku_id>/", product_bundle_detail, name="product-bundle-detail"),
    path("bundles/<int:sku_id>/availability/", product_bundle_availability, name="product-bundle-availability"),
    path("bundles/migrations/preview/", product_bundle_migration_preview, name="product-bundle-migration-preview"),
    path("bundles/migrations/<str:token>/confirm/", product_bundle_migration_confirm, name="product-bundle-migration-confirm"),
    path("bundles/returns/<int:refund_item_id>/suggestion/", product_bundle_return_suggestion, name="product-bundle-return-suggestion"),
    path("bundle-components/", product_bundle_component_collection, name="product-bundle-component-collection"),
    path("bundle-components/<int:pk>/", product_bundle_component_detail, name="product-bundle-component-detail"),
    path("status-recommendations/", status_recommendation_collection, name="product-status-recommendation-collection"),
    path(
        "status-recommendations/<int:pk>/",
        status_recommendation_detail,
        name="product-status-recommendation-detail",
    ),
    path(
        "status-recommendations/<int:pk>/confirm/",
        confirm_status_recommendation,
        name="product-status-recommendation-confirm",
    ),
    path(
        "status-recommendations/<int:pk>/reject/",
        reject_status_recommendation,
        name="product-status-recommendation-reject",
    ),
    path("status-transitions/", status_transition_collection, name="product-status-transition-collection"),
    path("status/evaluate-mock/", evaluate_mock_status_view, name="product-status-evaluate-mock"),
]
