from django.urls import path

from .views import (
    product_bundle_component_collection,
    product_bundle_component_detail,
    product_category_collection,
    product_attribute_collection,
    product_attribute_detail,
    product_category_detail,
    product_category_attributes,
    product_category_background_colors,
    product_coding_options,
    product_color_collection,
    product_color_detail,
    import_standard_product_colors,
    product_detail_collection,
    product_detail_bulk_update,
    product_detail_bulk_cache_images,
    freeze_product_spu_code,
    confirm_status_recommendation,
    evaluate_mock_status_view,
    product_research_collection,
    product_research_detail,
    product_sku_collection,
    product_sku_detail,
    product_sku_image,
    product_legacy_collection,
    product_legacy_detail,
    product_legacy_generate,
    product_spu_collection,
    product_spu_bulk_update,
    product_spu_detail,
    reject_status_recommendation,
    status_recommendation_collection,
    status_recommendation_detail,
    status_transition_collection,
)


urlpatterns = [
    path("coding-options/", product_coding_options, name="product-coding-options"),
    path("attributes/", product_attribute_collection, name="product-attribute-collection"),
    path("attributes/<int:pk>/", product_attribute_detail, name="product-attribute-detail"),
    path("categories/", product_category_collection, name="product-category-collection"),
    path("categories/<int:pk>/", product_category_detail, name="product-category-detail"),
    path("categories/<int:pk>/attributes/", product_category_attributes, name="product-category-attributes"),
    path("category-background-colors/", product_category_background_colors, name="product-category-background-colors"),
    path("colors/", product_color_collection, name="product-color-collection"),
    path("colors/<int:pk>/", product_color_detail, name="product-color-detail"),
    path("colors/import-standard/", import_standard_product_colors, name="product-color-import-standard"),
    path("research/", product_research_collection, name="product-research-collection"),
    path("research/<int:pk>/", product_research_detail, name="product-research-detail"),
    path("spus/", product_spu_collection, name="product-spu-collection"),
    path("spus/bulk-update/", product_spu_bulk_update, name="product-spu-bulk-update"),
    path("spus/<int:pk>/", product_spu_detail, name="product-spu-detail"),
    path("spus/<int:pk>/freeze-code/", freeze_product_spu_code, name="product-spu-freeze-code"),
    path("skus/", product_sku_collection, name="product-sku-collection"),
    path("skus/<int:pk>/", product_sku_detail, name="product-sku-detail"),
    path("skus/<int:pk>/image/", product_sku_image, name="product-sku-image"),
    path("details/", product_detail_collection, name="product-detail-collection"),
    path("details/bulk-update/", product_detail_bulk_update, name="product-detail-bulk-update"),
    path("details/images/bulk-cache/", product_detail_bulk_cache_images, name="product-detail-bulk-cache-images"),
    path("legacy-items/", product_legacy_collection, name="product-legacy-collection"),
    path("legacy-items/<int:pk>/", product_legacy_detail, name="product-legacy-detail"),
    path("legacy-items/<int:pk>/generate/", product_legacy_generate, name="product-legacy-generate"),
    path("bundle-components/", product_bundle_component_collection, name="product-bundle-component-collection"),
    path("bundle-components/<int:pk>/", product_bundle_component_detail, name="product-bundle-component-detail"),
    path("status-recommendations/", status_recommendation_collection, name="product-status-recommendation-collection"),
    path(
        "status-recommendations/<int:pk>/",
        status_recommendation_detail,
        name="product-status-recommendation-detail",
    ),
    path(
        "status-recommendations/<int:pk>/confirm/",
        confirm_status_recommendation,
        name="product-status-recommendation-confirm",
    ),
    path(
        "status-recommendations/<int:pk>/reject/",
        reject_status_recommendation,
        name="product-status-recommendation-reject",
    ),
    path("status-transitions/", status_transition_collection, name="product-status-transition-collection"),
    path("status/evaluate-mock/", evaluate_mock_status_view, name="product-status-evaluate-mock"),
]
