# Generated by Django 5.2.16 on 2026-07-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('purchasing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=80)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_production', 'In production'), ('production_completed', 'Production completed'), ('ready_to_ship', 'Ready to ship'), ('shipping_review_pending', 'Shipping review pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped')], default='pending', max_length=40)),
                ('completed_quantity', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_system', models.CharField(blank=True, max_length=80, null=True)),
                ('source_table', models.CharField(blank=True, max_length=80, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('production_started_at', models.DateTimeField(blank=True, null=True)),
                ('production_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supply_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_purchase_orders', to='masterdata.suppliermaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_purchase_orders', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quantity', models.PositiveBigIntegerField()),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('request_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_production_progress_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_production_progress', to='tenants.tenant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='purchasing.supplypurchaseorder')),
            ],
            options={
                'ordering': ['order_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyPurchaseOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('start_production', 'Start production'), ('update_progress', 'Update progress'), ('complete_production', 'Complete production')], max_length=40)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('actor_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier')], max_length=20)),
                ('before_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_production', 'In production'), ('production_completed', 'Production completed'), ('ready_to_ship', 'Ready to ship'), ('shipping_review_pending', 'Shipping review pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped')], max_length=40)),
                ('after_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_production', 'In production'), ('production_completed', 'Production completed'), ('ready_to_ship', 'Ready to ship'), ('shipping_review_pending', 'Shipping review pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_purchase_order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='purchasing.supplypurchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_purchase_order_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyPurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('sku_code_snapshot', models.CharField(max_length=80)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.supplypurchaseorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_purchase_order_lines', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_purchase_order_lines', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order_id', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='supplypurchaseorder',
            index=models.Index(fields=['tenant', 'supplier', 'status'], name='idx_supply_po_scope'),
        ),
        migrations.AddIndex(
            model_name='supplypurchaseorder',
            index=models.Index(fields=['tenant', 'status', 'expected_delivery_date'], name='idx_supply_po_status'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_no'), name='uniq_supply_po_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_system', 'source_table', 'source_record_id'), name='uniq_supply_po_source'),
        ),
        migrations.AddIndex(
            model_name='supplyproductionprogress',
            index=models.Index(fields=['tenant', 'order', 'created_at'], name='idx_supply_progress_order'),
        ),
        migrations.AddConstraint(
            model_name='supplyproductionprogress',
            constraint=models.UniqueConstraint(fields=('order', 'request_id'), name='uniq_supply_progress_request'),
        ),
        migrations.AddConstraint(
            model_name='supplyproductionprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='supply_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='supplypurchaseorderevent',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='idx_supply_po_event'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorderevent',
            constraint=models.UniqueConstraint(fields=('order', 'idempotency_key'), name='uniq_supply_po_idempotency'),
        ),
        migrations.AddIndex(
            model_name='supplypurchaseorderline',
            index=models.Index(fields=['tenant', 'sku'], name='idx_supply_po_line_sku'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='uniq_supply_po_line_no'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'source_record_id'), name='uniq_supply_po_line_source'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supply_po_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='supply_po_line_price_gte_zero'),
        ),
    ]
