# Generated by Django 5.2.16 on 2026-07-25 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('purchasing', '0002_supplypurchaseorder_supplyproductionprogress_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypurchaseorder',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='supplypurchaseorder',
            name='creation_request_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='supplypurchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'creation_idempotency_key'), name='uniq_supply_po_create_key'),
        ),
    ]
