# Generated by Django 5.2.17 on 2026-09-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productbundlemigrationbatch_productbundleversion_and_more'),
        ('purchasing', '0006_supplyfulfillment_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypurchaseorderline',
            name='source_bundle_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expanded_supply_purchase_order_lines', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='supplypurchaseorderline',
            name='source_bundle_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
