<template>
  <section class="business-page">
    <header class="page-header"><div><p class="eyebrow">UI-P5 · 供应商协同</p><h1 class="page-title">我的出货记录</h1><p>附件仅保留占位字段，不上传真实物流附件。</p></div><el-tag :type="stateTagType(state)">{{state}}</el-tag></header>
    <el-form class="filters" inline><el-form-item label="状态"><el-select v-model="statusFilter" clearable style="width:160px"><el-option label="草稿" value="draft"/><el-option label="已提交" value="submitted"/><el-option label="已收货" value="received"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form>
    <el-alert v-if="message" :title="message" :type="state==='error'?'error':'warning'" show-icon :closable="false"/>
    <el-table v-loading="loading" :data="rows" border empty-text="当前供应商暂无出货记录"><el-table-column prop="shipment_no" label="出货单号" min-width="160"/><el-table-column prop="sku_code" label="SKU" min-width="140"/><el-table-column prop="ship_quantity" label="出货数量" min-width="110"/><el-table-column prop="carton_count" label="箱数" min-width="90"/><el-table-column prop="weight" label="重量" min-width="100"/><el-table-column prop="volume" label="体积" min-width="100"/><el-table-column prop="status" label="状态" min-width="110"/><el-table-column label="操作" width="90"><template #default="{row}"><router-link :to="`/suppliers/shipments/${row.id}`">查看</router-link></template></el-table-column></el-table>
    <footer class="pager"><span>共 {{total}} 条</span><el-pagination v-model:current-page="page" :page-size="20" layout="prev, pager, next" :total="total" @current-change="load"/></footer>
  </section>
</template>
<script setup>import{onMounted,ref}from'vue';import{fetchSupplierShipments}from'../../api/suppliers';import{apiState,collectionRows,collectionTotal,stateTagType}from'../../utils/businessResponse';const rows=ref([]),total=ref(0),page=ref(1),statusFilter=ref(''),loading=ref(false),state=ref('loading'),message=ref('');async function load(){loading.value=true;message.value='';const response=await fetchSupplierShipments({status:statusFilter.value,page:page.value,page_size:20});if(response.success){rows.value=collectionRows(response.data);total.value=collectionTotal(response.data);state.value=apiState(response.data)}else{rows.value=[];total.value=0;state.value='error';message.value=response.message}loading.value=false}function search(){page.value=1;load()}function reset(){statusFilter.value='';search()}onMounted(load);</script>
<style scoped>.business-page{display:grid;gap:16px}.page-header,.pager{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-header p{margin:4px 0 0;color:#64748b}.eyebrow{font-size:12px;font-weight:700;color:#0f766e!important}.filters{padding:12px;border:1px solid #d9e2ec;border-radius:8px;background:#fff}.pager{color:#64748b;font-size:13px}</style>
