# Generated by Django 5.2.16 on 2026-07-10 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReceiptImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_batch_no', models.CharField(max_length=80)),
                ('masked_account', models.CharField(max_length=80)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_date', models.DateField()),
                ('reference_no', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('matched', 'Matched'), ('exception', 'Exception')], default='imported', max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipt_imports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('masked_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('statement_no', models.CharField(max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(choices=[('demo', 'Demo'), ('manual_import', 'Manual import'), ('fixture', 'Fixture')], default='demo', max_length=30)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('matching', 'Matching'), ('matched', 'Matched'), ('exception', 'Exception')], default='imported', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_statements', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('auto_suggested', 'Auto suggested'), ('manual', 'Manual')], default='auto_suggested', max_length=30)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='suggested', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='finance.bankreceiptimport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reconciliation_matches', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='finance.platformstatement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('amount_difference', 'Amount difference'), ('currency_mismatch', 'Currency mismatch'), ('missing_receipt', 'Missing receipt')], max_length=40)),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reconciliation_exceptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_exceptions', to='tenants.tenant')),
                ('reconciliation_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='finance.reconciliationmatch')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('withdrawal_no', models.CharField(max_length=80)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='withdrawal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='finance.withdrawalrecord'),
        ),
        migrations.AddConstraint(
            model_name='bankreceiptimport',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_no'), name='uniq_receipt_reference_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='platformstatement',
            constraint=models.UniqueConstraint(fields=('tenant', 'statement_no'), name='uniq_statement_no_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'withdrawal_no'), name='uniq_withdrawal_no_per_tenant'),
        ),
    ]
