# Generated by Django 5.2.16 on 2026-08-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(max_length=80)),
                ('development_source', models.CharField(choices=[('operation', 'Operation submission'), ('internal', 'Internal development'), ('supplier', 'Supplier recommendation')], max_length=30)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('target_sites', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(choices=[('initiated', 'Initiated'), ('design', 'Design'), ('sampling', 'Sampling'), ('review', 'Review'), ('finalized', 'Finalized'), ('delivered', 'Delivered')], default='initiated', max_length=20)),
                ('target_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_margin_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('planned_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_development_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_development_projects', to=settings.AUTH_USER_MODEL)),
                ('finalized_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_projects', to='products.productspu')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_projects', to='products.productresearch')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_projects', to='masterdata.suppliermaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_projects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(max_length=40)),
                ('review_date', models.DateField()),
                ('actual_sales_qty', models.PositiveIntegerField(default=0)),
                ('estimated_sales_qty', models.PositiveIntegerField(default=0)),
                ('hit_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('actual_margin_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('estimated_margin_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('margin_deviation', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('conclusion', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('fail', 'Fail')], max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_performance_reviews', to='products.productspu')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='products.productresearch')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_performance_reviews', to='tenants.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='development.developmentproject')),
            ],
            options={
                'ordering': ['tenant_id', '-review_date'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentCostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=40)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_leg_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('tariff_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_margin_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_development_costs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='development.developmentproject')),
            ],
            options={
                'ordering': ['project_id', 'site', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initiated', 'Initiated'), ('design', 'Design'), ('sampling', 'Sampling'), ('review', 'Review'), ('finalized', 'Finalized'), ('delivered', 'Delivered')], max_length=20)),
                ('entered_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deliverables', models.JSONField(blank=True, default=dict)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_development_stages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='development.developmentproject')),
            ],
            options={
                'ordering': ['project_id', 'entered_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentRequirementChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_requirement_changes', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_change_logs', to='products.productresearch')),
            ],
            options={
                'ordering': ['requirement_id', '-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(max_length=80)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('evaluation_result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional')], default='pending', max_length=20)),
                ('evaluation_notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('unit_price_quoted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moq', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='development.developmentproject')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_samples', to='masterdata.suppliermaster')),
            ],
            options={
                'ordering': ['project_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=40)),
                ('platform', models.CharField(max_length=30)),
                ('snapshot_date', models.DateField()),
                ('daily_sales_qty', models.PositiveIntegerField(default=0)),
                ('daily_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_sales_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumulative_sales_qty', models.PositiveIntegerField(default=0)),
                ('cumulative_sales_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_source', models.CharField(choices=[('manual_import', 'Manual import'), ('erp_sync', 'ERP sync'), ('api_shopee', 'Shopee API'), ('api_lazada', 'Lazada API'), ('api_tiktok', 'TikTok API')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_snapshots', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-snapshot_date'],
            },
        ),
        migrations.AddIndex(
            model_name='developmentproject',
            index=models.Index(fields=['tenant', 'stage', 'status'], name='idx_dev_project_stage'),
        ),
        migrations.AddIndex(
            model_name='developmentproject',
            index=models.Index(fields=['tenant', 'assigned_to'], name='idx_dev_project_owner'),
        ),
        migrations.AddConstraint(
            model_name='developmentproject',
            constraint=models.UniqueConstraint(fields=('tenant', 'project_no'), name='uniq_dev_project_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='developmentperformancereview',
            constraint=models.UniqueConstraint(fields=('project', 'review_period'), name='uniq_dev_review_period'),
        ),
        migrations.AddConstraint(
            model_name='developmentcostestimate',
            constraint=models.UniqueConstraint(fields=('project', 'site', 'version'), name='uniq_dev_cost_version'),
        ),
        migrations.AddIndex(
            model_name='developmentprojectstage',
            index=models.Index(fields=['project', 'stage'], name='idx_dev_stage_project'),
        ),
        migrations.AddIndex(
            model_name='developmentrequirementchangelog',
            index=models.Index(fields=['requirement', 'changed_at'], name='idx_dev_req_change'),
        ),
        migrations.AddConstraint(
            model_name='developmentsample',
            constraint=models.UniqueConstraint(fields=('project', 'sample_no'), name='uniq_dev_sample_no'),
        ),
        migrations.AddIndex(
            model_name='productsalessnapshot',
            index=models.Index(fields=['tenant', 'snapshot_date'], name='idx_sales_snapshot_date'),
        ),
        migrations.AddConstraint(
            model_name='productsalessnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'site', 'snapshot_date'), name='uniq_sales_snapshot_day'),
        ),
    ]
