# Generated by Django 5.2.16 on 2026-08-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_product_sales_summary_view'),
        ('products', '0011_product_purchase_price'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentRequirementCompetitorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_report_id', models.CharField(max_length=160)),
                ('task_id', models.CharField(max_length=160)),
                ('platform', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=40)),
                ('product_id', models.CharField(max_length=160)),
                ('product_title', models.CharField(max_length=300)),
                ('relation_type', models.CharField(choices=[('reference', 'Reference'), ('primary', 'Primary competitor'), ('alternative', 'Alternative competitor')], default='reference', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('report_completed_at', models.DateTimeField()),
                ('data_updated_at', models.DateTimeField()),
                ('decision_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_development_competitor_links', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_links', to='products.productresearch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_competitor_links', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'requirement_id', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'requirement'], name='idx_dev_comp_req'), models.Index(fields=['tenant', 'external_report_id'], name='idx_dev_comp_report'), models.Index(fields=['tenant', 'platform', 'site'], name='idx_dev_comp_market')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'requirement', 'external_report_id'), name='uniq_dev_req_competitor_report')],
            },
        ),
    ]
