# Generated by Django 5.2.16 on 2026-07-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('formula', models.TextField()),
                ('aggregation_method', models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('average', 'Average'), ('latest', 'Latest')], max_length=20)),
                ('source_tables', models.JSONField(default=list)),
                ('supported_granularities', models.JSONField(default=list)),
                ('allowed_dimensions', models.JSONField(blank=True, default=list)),
                ('permission_code', models.CharField(default='analytics.view', max_length=120)),
                ('allow_drill_down', models.BooleanField(default=False)),
                ('contains_sensitive_data', models.BooleanField(default=False)),
                ('missing_data_policy', models.CharField(default='mark_missing', max_length=80)),
                ('allows_automated_decision', models.BooleanField(default=False, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'metric_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='MetricDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=120)),
                ('source_batch', models.CharField(max_length=120)),
                ('source_record_id', models.CharField(max_length=120)),
                ('calculation_task', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quality_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('quality_detail', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_data_points', to='tenants.tenant')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_points', to='reports.metricdefinition')),
            ],
            options={
                'ordering': ['tenant_id', 'metric_definition_id', 'occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetricAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_version', models.PositiveIntegerField()),
                ('granularity', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('dimensions_hash', models.CharField(max_length=64)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valid_point_count', models.PositiveIntegerField(default=0)),
                ('excluded_point_count', models.PositiveIntegerField(default=0)),
                ('quality_status', models.CharField(choices=[('passed', 'Passed'), ('no_valid_data', 'No valid data')], max_length=30)),
                ('is_formal', models.BooleanField(default=False)),
                ('source_lineage', models.JSONField(default=dict)),
                ('refreshed_at', models.DateTimeField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_aggregates', to='tenants.tenant')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregates', to='reports.metricdefinition')),
            ],
            options={
                'ordering': ['tenant_id', 'metric_definition_id', '-period_end', 'dimensions_hash'],
            },
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'metric_code', 'version'), name='uniq_metric_definition_version'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='metric_definition_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('allows_automated_decision', False)), name='metric_definition_no_auto_decision'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['tenant', 'metric_definition', 'occurred_at'], name='idx_metric_point_period'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['tenant', 'quality_status'], name='idx_metric_point_quality'),
        ),
        migrations.AddConstraint(
            model_name='metricdatapoint',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_table', 'source_record_id', 'metric_definition'), name='uniq_metric_source_record'),
        ),
        migrations.AddIndex(
            model_name='metricaggregate',
            index=models.Index(fields=['tenant', 'metric_definition', 'period_end'], name='idx_metric_aggregate_period'),
        ),
        migrations.AddIndex(
            model_name='metricaggregate',
            index=models.Index(fields=['tenant', 'quality_status'], name='idx_metric_aggregate_quality'),
        ),
        migrations.AddConstraint(
            model_name='metricaggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'metric_definition', 'definition_version', 'granularity', 'period_start', 'period_end', 'dimensions_hash'), name='uniq_metric_aggregate_slice'),
        ),
        migrations.AddConstraint(
            model_name='metricaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lt', models.F('period_end'))), name='metric_aggregate_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='metricaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('is_formal', False), models.Q(('quality_status', 'passed'), ('valid_point_count__gt', 0)), _connector='OR'), name='formal_metric_aggregate_has_valid_data'),
        ),
    ]
