# Generated by Django 5.2.16 on 2026-07-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricAggregateLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=120)),
                ('source_batch', models.CharField(max_length=120)),
                ('calculation_task', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tenant_id', 'aggregate_id', 'source_table', 'source_batch', 'calculation_task'],
            },
        ),
        migrations.AddField(
            model_name='metricaggregate',
            name='quality_detail',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='minimum_quality_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metricaggregate',
            name='quality_status',
            field=models.CharField(choices=[('passed', 'Passed'), ('degraded', 'Degraded'), ('no_valid_data', 'No valid data')], max_length=30),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='missing_data_policy',
            field=models.CharField(choices=[('mark_missing', 'Mark missing'), ('reject', 'Reject incomplete data'), ('zero_fill', 'Fill missing values with zero')], default='mark_missing', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quality_rate__gte', 0), ('minimum_quality_rate__lte', 1)), name='metric_definition_quality_rate_range'),
        ),
        migrations.AddField(
            model_name='metricaggregatelineage',
            name='aggregate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_records', to='reports.metricaggregate'),
        ),
        migrations.AddField(
            model_name='metricaggregatelineage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_aggregate_lineage', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='metricaggregatelineage',
            index=models.Index(fields=['tenant', 'aggregate'], name='idx_metric_lineage_aggregate'),
        ),
        migrations.AddIndex(
            model_name='metricaggregatelineage',
            index=models.Index(fields=['tenant', 'source_batch'], name='idx_metric_lineage_batch'),
        ),
        migrations.AddConstraint(
            model_name='metricaggregatelineage',
            constraint=models.UniqueConstraint(fields=('aggregate', 'source_table', 'source_batch', 'calculation_task'), name='uniq_metric_aggregate_lineage'),
        ),
    ]
