# Generated by Django 5.2.16 on 2026-07-11 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_metricaggregatelineage_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('analytics_summary', 'Analytics summary'), ('inventory_alerts', 'Inventory alerts'), ('replenishment', 'Replenishment recommendations'), ('lifecycle', 'Lifecycle reviews'), ('business_alerts', 'Business alerts'), ('finance_summary', 'Finance summary')], max_length=40)),
                ('data_scope', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed placeholder'), ('rejected', 'Rejected')], max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('masked_file_reference', models.CharField(blank=True, max_length=240)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_export_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportExportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request', 'Request'), ('view', 'View')], max_length=20)),
                ('result', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_export_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_audit_logs', to='tenants.tenant')),
                ('export_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.reportexportrequest')),
            ],
            options={
                'ordering': ['tenant_id', 'export_request_id', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['tenant', 'requested_by', 'status'], name='idx_report_export_owner'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['tenant', 'report_type', 'requested_at'], name='idx_report_export_type'),
        ),
        migrations.AddIndex(
            model_name='reportexportauditlog',
            index=models.Index(fields=['tenant', 'export_request', 'action'], name='idx_report_export_audit'),
        ),
    ]
