# Generated by Django 5.2.16 on 2026-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportexportrequest_reportexportauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexportauditlog',
            name='action',
            field=models.CharField(choices=[('request', 'Request'), ('view', 'View'), ('download', 'Download')], max_length=20),
        ),
    ]
