# Generated by Django 5.2.16 on 2026-07-17 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportexportauditlog_action'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexportauditlog',
            name='export_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='reports.reportexportrequest'),
        ),
        migrations.AlterField(
            model_name='reportexportauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_export_audit_logs', to='tenants.tenant'),
        ),
    ]
