# Generated by Django 5.2.17 on 2026-08-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportexportauditlog_export_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexportrequest',
            name='report_type',
            field=models.CharField(choices=[('analytics_summary', 'Analytics summary'), ('inventory_alerts', 'Inventory alerts'), ('replenishment', 'Replenishment recommendations'), ('lifecycle', 'Lifecycle reviews'), ('business_alerts', 'Business alerts'), ('finance_summary', 'Finance summary'), ('sales_details', 'Sales details')], max_length=40),
        ),
    ]

