# Generated by Django 5.2.17 on 2026-09-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_real_export_files'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexportrequest',
            name='source_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reportexportrequest',
            name='report_type',
            field=models.CharField(choices=[('analytics_summary', 'Analytics summary'), ('inventory_alerts', 'Inventory alerts'), ('replenishment', 'Replenishment recommendations'), ('lifecycle', 'Lifecycle reviews'), ('business_alerts', 'Business alerts'), ('finance_summary', 'Finance summary'), ('sales_details', 'Sales details'), ('self_service', 'Self-service report')], max_length=40),
        ),
        migrations.CreateModel(
            name='SavedReportView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'owner'], name='idx_saved_report_owner')],
            },
        ),
    ]
