# Generated by Django 5.2.17 on 2026-10-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0048_register_internal_api_client_approval'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(unique=True)),
                ('reason', models.CharField(max_length=240)),
                ('operation', models.CharField(max_length=40)),
                ('changes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleResourcePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(max_length=120)),
                ('permission_code', models.CharField(default='*', max_length=120)),
                ('scope_type', models.CharField(choices=[('all', '租户内全部数据'), ('custom', '按业务范围限制')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleBinding',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('permissions.userrole',),
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uniq_user_role_per_tenant',
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_bindings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='context_key',
            field=models.CharField(default='tenant', max_length=80),
        ),
        migrations.AddField(
            model_name='userrole',
            name='source',
            field=models.CharField(default='legacy', max_length=80),
        ),
        migrations.AddField(
            model_name='userrole',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userrole',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.department'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='permissions.orgmembership'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'role', 'context_key', 'source'), name='uniq_role_binding_context'),
        ),
        migrations.AddField(
            model_name='permissionchange',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionchange',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='roleresourcepolicy',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_policies', to='permissions.role'),
        ),
        migrations.AddField(
            model_name='roleresourcepolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='orgmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'department'), name='uniq_org_membership'),
        ),
        migrations.AddConstraint(
            model_name='roleresourcepolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'resource_code', 'permission_code'), name='uniq_role_resource_policy'),
        ),
    ]
