<template>
  <section class="sample-page"><header><div><span>FULFILLMENT DESK</span><h1>送样履约</h1><p>价格匹配失败不会阻塞送样，未导入数据会明确标记。</p></div><el-button type="primary" :disabled="!canManage" @click="openDialog">创建送样</el-button></header>
    <el-card shadow="never"><template #header><strong>SKU / 商品查询</strong></template><el-form inline><el-form-item label="店铺 ID"><el-input v-model="query.store_id" style="width:110px"/></el-form-item><el-form-item label="站点"><el-input v-model="query.site_code" style="width:90px"/></el-form-item><el-form-item label="SKU"><el-input v-model="query.sku"/></el-form-item><el-form-item label="商品 ID"><el-input v-model="query.product_id"/></el-form-item><el-button :loading="looking" @click="lookup">查询</el-button></el-form><el-alert v-if="lookupState" :title="lookupState" :type="prices.length?'success':'warning'" :closable="false"/><el-table v-if="prices.length" :data="prices"><el-table-column prop="store_name" label="店铺"/><el-table-column prop="product_name" label="商品"/><el-table-column prop="external_sku" label="SKU"/><el-table-column prop="parent_sku" label="父 SKU"/><el-table-column prop="original_price" label="原价"/><el-table-column prop="promotion_price" label="促销价"/><el-table-column prop="effective_price" label="有效售价"/><el-table-column prop="currency" label="币种"/><el-table-column prop="source_updated_at" label="更新时间" min-width="170"/></el-table></el-card>
    <el-card shadow="never"><el-table v-loading="loading" :data="rows" empty-text="暂无送样履约"><el-table-column prop="fulfillment_no" label="履约编号"/><el-table-column prop="outreach_task" label="建联任务"/><el-table-column prop="influencer" label="达人"/><el-table-column prop="store" label="店铺"/><el-table-column prop="owner" label="负责 BD"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="创建时间" min-width="170"/></el-table><el-pagination v-if="total > 0" v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[20,50,100]" :total="total" layout="total, sizes, prev, pager, next" @current-change="load" @size-change="changePageSize"/></el-card>
    <el-dialog v-model="dialog" title="创建送样" width="560px" @closed="discardDraft"><el-form label-width="110px"><el-form-item label="履约编号"><el-input v-model="form.fulfillment_no"/></el-form-item><el-form-item label="建联任务 ID"><el-input-number v-model="form.outreach_task" :min="1"/></el-form-item><el-form-item label="达人 ID"><el-input-number v-model="form.influencer" :min="1"/></el-form-item><el-form-item label="店铺 ID"><el-input-number v-model="form.store" :min="1"/></el-form-item><el-form-item label="负责 BD ID"><el-input-number v-model="form.owner" :min="1"/></el-form-item><el-form-item label="站点"><el-input v-model="item.site_code"/></el-form-item><el-form-item label="商品 ID"><el-input v-model="item.external_product_id"/></el-form-item><el-form-item label="SKU（可空）"><el-input v-model="item.requested_sku"/></el-form-item><el-form-item label="数量"><el-input-number v-model="item.quantity" :min="1"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">创建</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{useAuthStore}from'../../stores/auth';import{createSampleFulfillment,fetchSampleFulfillments,lookupProductPrice}from'../../api/influencers';import{collectionRows,collectionTotal}from'../../utils/businessResponse';
const auth=useAuthStore(),rows=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),prices=ref([]),loading=ref(false),looking=ref(false),saving=ref(false),dialog=ref(false),lookupState=ref(''),draftRequestKey=ref('');const canManage=computed(()=>auth.hasPermission('influencers.fulfillment.manage'));const query=reactive({store_id:'',site_code:'PH',sku:'',product_id:''});const form=reactive({fulfillment_no:'',outreach_task:1,influencer:1,store:1,owner:1});const item=reactive({site_code:'PH',external_product_id:'',requested_sku:'',quantity:1});
async function load(){loading.value=true;const r=await fetchSampleFulfillments({page:page.value,page_size:pageSize.value});loading.value=false;if(r.success){rows.value=collectionRows(r.data);total.value=collectionTotal(r.data)}else{rows.value=[];total.value=0;ElMessage.error(r.message)}}
function changePageSize(){page.value=1;load()}
function newDraftRequestKey(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function openDialog(){if(!draftRequestKey.value)draftRequestKey.value=newDraftRequestKey();dialog.value=true}
function discardDraft(){if(!saving.value)draftRequestKey.value=''}
async function lookup(){looking.value=true;const r=await lookupProductPrice({...query});looking.value=false;if(!r.success)return ElMessage.error(r.message);prices.value=r.data.results||[];lookupState.value=r.data.matched?`匹配到 ${prices.value.length} 条店铺 SKU 数据`:'数据源未导入或当前店铺/站点未匹配'}
async function submit(){saving.value=true;const key=draftRequestKey.value||(draftRequestKey.value=newDraftRequestKey());const items=(item.requested_sku||item.external_product_id)?[{...item}]:[];const r=await createSampleFulfillment({...form,items},key);saving.value=false;if(!r.success)return ElMessage.error(r.message);draftRequestKey.value='';dialog.value=false;ElMessage.success('送样已创建');await load()}
onMounted(load);
</script>
<style scoped>.sample-page{display:grid;gap:18px}header{display:flex;align-items:end;justify-content:space-between;padding:24px;border-radius:16px;background:linear-gradient(120deg,#17324d,#235d7a);color:#fff}header span{font-size:11px;letter-spacing:.18em;opacity:.75}h1{margin:6px 0;font-size:30px}p{margin:0;opacity:.8}</style>
