<template>
  <section class="sample-page">
    <header class="hero"><div><span>FULFILLMENT DESK</span><h1>送样履约</h1><p>跟踪建联达人从待发样到内容交付的完整履约过程。</p></div><el-button type="primary" :disabled="!canManage" @click="openCreate">新增送样</el-button></header>
    <div class="metrics"><div><span>当前记录</span><strong>{{ total }}</strong></div><div><span>已进入履约</span><strong>{{ fulfilledCount }}</strong></div><div><span>待发样</span><strong>{{ pendingCount }}</strong></div><div><span>异常/取消</span><strong>{{ exceptionCount }}</strong></div></div>
    <el-card shadow="never">
      <div class="toolbar"><el-input v-model="filters.search" clearable placeholder="搜索达人、任务、商品或订单" @keyup.enter="applyFilters"/><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option v-for="(label,value) in FULFILLMENT_STATUS_LABELS" :key="value" :label="label" :value="value"/></el-select><el-select v-model="filters.store" clearable filterable placeholder="全部店铺"><el-option v-for="store in rowStores" :key="store.id" :label="store.name" :value="store.id"/></el-select><el-button type="primary" @click="applyFilters">查询</el-button><el-button @click="resetFilters">重置</el-button></div>
      <el-table v-loading="loading" :data="rows" empty-text="暂无送样履约"><el-table-column prop="fulfillment_no" label="履约编号" min-width="145"/><el-table-column label="建联任务" min-width="150"><template #default="{row}"><b>{{ row.outreach_task_no||row.outreach_task }}</b><small>{{ row.outreach_task_name }}</small></template></el-table-column><el-table-column prop="influencer_name" label="达人" min-width="120"/><el-table-column prop="store_name" label="店铺" min-width="130"/><el-table-column label="产品 / SKU / 数量" min-width="220"><template #default="{row}"><b>{{ row.product_name_snapshot||'未填写' }}</b><small v-for="item in row.items||[]" :key="item.id">{{ item.requested_sku||'SKU 待补充' }} × {{ item.quantity }}</small></template></el-table-column><el-table-column prop="external_product_id" label="商品 ID" min-width="155"/><el-table-column prop="sample_order_no" label="样品订单" min-width="135"/><el-table-column prop="owner_name" label="负责 BD" min-width="110"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag>{{ statusLabel(FULFILLMENT_STATUS_LABELS,row.status) }}</el-tag></template></el-table-column><el-table-column prop="sample_sent_at" label="送样时间" min-width="155"/></el-table>
      <el-pagination v-if="total" v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/>
    </el-card>
    <el-dialog v-model="visible" title="新增送样履约" width="760px" @closed="discardDraft"><el-form label-width="110px"><el-form-item label="履约编号" required><el-input v-model="form.fulfillment_no"/></el-form-item><el-form-item label="建联任务" required><el-select v-model="form.outreach_task" filterable @change="selectTask"><el-option v-for="task in tasks" :key="task.id" :label="`${task.task_name||task.task_no}（${task.task_no}）`" :value="task.id"/></el-select></el-form-item><el-form-item label="达人" required><el-select v-model="form.outreach_target" :disabled="!form.outreach_task"><el-option v-for="target in targets" :key="target.id" :label="`达人 ${target.influencer}`" :value="target.id"/></el-select></el-form-item><el-form-item label="任务信息"><el-alert :closable="false" type="info" :title="inheritedTask?`店铺 ${inheritedTask.store_name||inheritedTask.store} · 商品 ${inheritedTask.external_product_id||'未填写'} · BD ${inheritedTask.owner_name||inheritedTask.owner}`:'请先选择建联任务'"/></el-form-item><el-form-item label="样品订单号"><el-input v-model="form.sample_order_no" placeholder="填写后按已发货口径处理"/></el-form-item><el-divider content-position="left">SKU 明细</el-divider><div v-for="(item,index) in items" :key="index" class="sku-row"><el-input v-model="item.site_code" placeholder="站点"/><el-input v-model="item.requested_sku" placeholder="SKU 可暂时为空"/><el-input-number v-model="item.quantity" :min="1"/><el-button link type="danger" :disabled="items.length===1" @click="items.splice(index,1)">删除</el-button></div><el-button link type="primary" @click="items.push(newItem())">+ 添加 SKU</el-button><el-alert class="price-note" type="warning" :closable="false" title="价格未匹配不会阻止送样记录保存。"/></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">创建</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue';import {ElMessage} from 'element-plus';import {useAuthStore} from '../../stores/auth';import {createSampleFulfillment,fetchOutreachTargets,fetchOutreachTasks,fetchSampleFulfillments,formatInfluencerError,FULFILLMENT_STATUS_LABELS,statusLabel} from '../../api/influencers';import {collectionRows,collectionTotal} from '../../utils/businessResponse';
const auth=useAuthStore(),rows=ref([]),tasks=ref([]),targets=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),loading=ref(false),saving=ref(false),visible=ref(false),inheritedTask=ref(null),draftKey=ref('');const filters=reactive({search:'',status:'',store:null});const form=reactive({fulfillment_no:'',outreach_task:null,outreach_target:null,sample_order_no:''});const newItem=()=>({site_code:'PH',external_product_id:'',requested_sku:null,quantity:1}),items=ref([newItem()]);const canManage=computed(()=>auth.hasPermission('influencers.fulfillment.manage'));const fulfilledStatuses=['shipped','received','creating','published','completed','live_creator'];const fulfilledCount=computed(()=>rows.value.filter(row=>fulfilledStatuses.includes(row.status)||row.shipped_at||row.sample_order_no).length);const pendingCount=computed(()=>rows.value.filter(row=>row.status==='pending').length);const exceptionCount=computed(()=>rows.value.filter(row=>['overdue','cancelled'].includes(row.status)).length);const rowStores=computed(()=>[...new Map(rows.value.filter(row=>row.store).map(row=>[row.store,{id:row.store,name:row.store_name||`店铺 ${row.store}`}])).values()]);
async function load(){loading.value=true;const r=await fetchSampleFulfillments({page:page.value,page_size:pageSize.value,...filters});loading.value=false;if(r.success){rows.value=collectionRows(r.data);total.value=collectionTotal(r.data)}else ElMessage.error(formatInfluencerError(r,'送样列表加载失败'))}function applyFilters(){page.value=1;load()}function resetFilters(){Object.assign(filters,{search:'',status:'',store:null});applyFilters()}const newKey=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;function discardDraft(){draftKey.value=''}async function openCreate(){Object.assign(form,{fulfillment_no:`SAMPLE-${Date.now()}`,outreach_task:null,outreach_target:null,sample_order_no:''});inheritedTask.value=null;targets.value=[];items.value=[newItem()];draftKey.value=newKey();const r=await fetchOutreachTasks({page:1,page_size:100,status:'in_progress'});tasks.value=r.success?collectionRows(r.data):[];visible.value=true}async function selectTask(id){inheritedTask.value=tasks.value.find(item=>item.id===id)||null;form.outreach_target=null;const r=await fetchOutreachTargets(id,{page:1,page_size:100});targets.value=r.success?collectionRows(r.data):[]}async function submit(){if(!form.fulfillment_no||!form.outreach_task||!form.outreach_target)return ElMessage.warning('请选择任务和达人');saving.value=true;const payload={...form,items:items.value.map(item=>({...item,external_product_id:inheritedTask.value?.external_product_id||'',requested_sku:item.requested_sku?.trim()||null}))};const r=await createSampleFulfillment(payload,draftKey.value);saving.value=false;if(!r.success)return ElMessage.error(formatInfluencerError(r,'送样创建失败'));draftKey.value='';visible.value=false;ElMessage.success('送样已创建');load()}onMounted(load);
</script>
<style scoped>.sample-page{display:grid;gap:16px}.hero{display:flex;justify-content:space-between;align-items:end;padding:20px 24px;border-radius:14px;background:linear-gradient(115deg,#075b4b,#13806b);color:#fff}.hero h1{margin:5px 0}.hero p{margin:0;opacity:.84}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #e5e7eb;border-radius:10px;background:#fff}.metrics div{padding:15px 18px;border-right:1px solid #e5e7eb}.metrics div:last-child{border:0}.metrics span,.metrics strong,td small{display:block}.metrics span,td small{color:#84909c;font-size:12px}.metrics strong{margin-top:5px;font-size:24px}.toolbar{display:flex;gap:10px;margin-bottom:16px}.toolbar .el-input{max-width:340px}.sku-row{display:grid;grid-template-columns:110px 1fr 130px 60px;gap:10px;margin-bottom:10px}.price-note{margin-top:14px}.el-pagination{margin-top:16px;justify-content:flex-end}@media(max-width:760px){.hero{align-items:stretch;flex-direction:column}.metrics{grid-template-columns:1fr 1fr}.toolbar{flex-wrap:wrap}.sku-row{grid-template-columns:1fr}}</style>
