# Generated by Django 5.2.16 on 2026-07-28 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_frozen_packing_standard(apps, schema_editor):
    standard = apps.get_model("packing", "PackingStandardVersion")
    standard.objects.get_or_create(
        code="packing-v1",
        version=1,
        defaults={
            "title": "SC-F2 frozen packing standard v1",
            "rules": {
                "empty_box_forbidden": True,
                "exact_completion_required": True,
                "mixed_box_label_items_required": True,
                "single_order_single_sku_recommended": True,
            },
            "is_active": True,
        },
    )


def remove_frozen_packing_standard(apps, schema_editor):
    # Reverse migration drops the referencing packing tables before it drops
    # PackingStandardVersion. Deleting this seed first would violate PROTECT
    # whenever a non-empty packing batch still references the frozen standard.
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('purchasing', '0004_supplypurchaseorderevent_idempotency_snapshot'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creation_idempotency_key', models.CharField(max_length=128)),
                ('creation_request_hash', models.CharField(max_length=64)),
                ('source_system', models.CharField(blank=True, max_length=80, null=True)),
                ('source_table', models.CharField(blank=True, max_length=80, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_packing_batches', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_batches', to='masterdata.suppliermaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_batches', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('box_no', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='packing.packingbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_boxes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['batch_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PackingBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_no_snapshot', models.CharField(max_length=80)),
                ('sku_code_snapshot', models.CharField(max_length=80)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.packingbox')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_items', to='purchasing.supplypurchaseorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_box_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['box_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_version', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('proposed_boxes', models.JSONField(default=list)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('applied_version', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='packing.packingbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_packing_change_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_packing_change_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_change_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['batch_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_batch', 'Create batch'), ('add_box', 'Add box'), ('update_box', 'Update box'), ('remove_box', 'Remove box'), ('complete_batch', 'Complete batch'), ('cancel_batch', 'Cancel batch'), ('submit_change', 'Submit change'), ('approve_change', 'Approve change'), ('reject_change', 'Reject change'), ('apply_change', 'Apply change'), ('generate_label', 'Generate label')], max_length=40)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('actor_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier')], max_length=20)),
                ('before_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('after_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('batch_version', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packing.packingbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['batch_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingStandardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('rules', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uniq_pack_standard_version'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='pack_standard_version_gt_zero')],
            },
        ),
        migrations.AddField(
            model_name='packingbatch',
            name='standard_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_batches', to='packing.packingstandardversion'),
        ),
        migrations.CreateModel(
            name='PackingSupplierCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_self_pack', models.BooleanField(default=False)),
                ('can_mix_order_packing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_capability', to='masterdata.suppliermaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_supplier_capabilities', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_packing_supplier_capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant_id', 'supplier_id'],
            },
        ),
        migrations.CreateModel(
            name='PackingBatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_guard', models.BooleanField(default=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_orders', to='packing.packingbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_batch_links', to='purchasing.supplypurchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_batch_orders', to='tenants.tenant')),
            ],
            options={
                'ordering': ['batch_id', 'order_id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'order'), name='uniq_pack_batch_order'), models.UniqueConstraint(fields=('order', 'active_guard'), name='uniq_pack_active_order'), models.CheckConstraint(condition=models.Q(('active_guard', True), ('active_guard__isnull', True), _connector='OR'), name='pack_active_guard_true_null')],
            },
        ),
        migrations.AddConstraint(
            model_name='packingbox',
            constraint=models.UniqueConstraint(fields=('batch', 'sequence'), name='uniq_pack_box_sequence'),
        ),
        migrations.AddConstraint(
            model_name='packingbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'box_no'), name='uniq_pack_box_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='packingbox',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='pack_box_sequence_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='packingbox',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gt', 0), _connector='OR'), name='pack_box_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='packingbox',
            constraint=models.CheckConstraint(condition=models.Q(('volume__isnull', True), ('volume__gt', 0), _connector='OR'), name='pack_box_volume_positive'),
        ),
        migrations.AddIndex(
            model_name='packingboxitem',
            index=models.Index(fields=['tenant', 'order_line'], name='idx_pack_item_order_line'),
        ),
        migrations.AddConstraint(
            model_name='packingboxitem',
            constraint=models.UniqueConstraint(fields=('box', 'order_line'), name='uniq_pack_box_order_line'),
        ),
        migrations.AddConstraint(
            model_name='packingboxitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='pack_box_item_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='packingchangerequest',
            constraint=models.CheckConstraint(condition=models.Q(('expected_version__gt', 0)), name='pack_change_expected_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='packingevent',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='idx_pack_event_action'),
        ),
        migrations.AddConstraint(
            model_name='packingevent',
            constraint=models.UniqueConstraint(fields=('batch', 'idempotency_key'), name='uniq_pack_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='packingevent',
            constraint=models.CheckConstraint(condition=models.Q(('batch_version__gt', 0)), name='pack_event_version_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='packingbatch',
            index=models.Index(fields=['tenant', 'supplier', 'status'], name='idx_pack_batch_scope'),
        ),
        migrations.AddConstraint(
            model_name='packingbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch_no'), name='uniq_pack_batch_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='packingbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'creation_idempotency_key'), name='uniq_pack_batch_create_key'),
        ),
        migrations.AddConstraint(
            model_name='packingbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_system', 'source_table', 'source_record_id'), name='uniq_pack_batch_source'),
        ),
        migrations.AddConstraint(
            model_name='packingbatch',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='pack_batch_version_gt_zero'),
        ),
        migrations.RunPython(
            seed_frozen_packing_standard,
            remove_frozen_packing_standard,
        ),
    ]
