# Generated by Django 5.2.16 on 2026-08-08 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packing", "0005_packingboxconsumption_request_hash"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingBoxConsumptionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("commit", "Commit"),
                            ("release", "Release"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("before_state", models.JSONField(default=dict)),
                ("after_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_box_consumption_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="packing.packingboxconsumption",
                    ),
                ),
                (
                    "result_consumption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_results",
                        to="packing.packingboxconsumption",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_box_consumption_actions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id", "created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "consumption", "action"],
                        name="idx_pack_consumption_action",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "idempotency_key"),
                        name="uniq_pack_consumption_action_key",
                    )
                ],
            },
        ),
    ]
