# Generated by Django 5.2.17 on 2026-08-14 07:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_productsku_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('platform_product_id', models.CharField(max_length=191)),
                ('seller_sku', models.CharField(blank=True, max_length=191)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('confirmed', 'Confirmed')], default='unmatched', max_length=20)),
                ('match_method', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commerce_marketplace_product_mapping',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSkuMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('platform_product_id', models.CharField(max_length=191)),
                ('platform_variant_id', models.CharField(max_length=191)),
                ('seller_sku', models.CharField(blank=True, max_length=191)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('confirmed', 'Confirmed')], default='unmatched', max_length=20)),
                ('match_method', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commerce_marketplace_sku_mapping',
            },
        ),
        migrations.CreateModel(
            name='RefundReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('external_refund_id', models.CharField(blank=True, max_length=191)),
                ('external_return_id', models.CharField(max_length=191)),
                ('case_type', models.CharField(max_length=40)),
                ('raw_status', models.CharField(max_length=80)),
                ('canonical_status', models.CharField(max_length=40)),
                ('arbitration_status', models.CharField(blank=True, max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('reason_text', models.CharField(blank=True, max_length=240)),
                ('responsible_party', models.CharField(blank=True, max_length=40)),
                ('requested_at_utc', models.DateTimeField()),
                ('approved_at_utc', models.DateTimeField(blank=True, null=True)),
                ('completed_at_utc', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at_utc', models.DateTimeField()),
                ('currency', models.CharField(max_length=8)),
                ('refund_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('refund_subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('refund_shipping_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('refund_tax', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('return_tracking_reference_hash', models.CharField(blank=True, max_length=64)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commerce_refund_return',
                'ordering': ['-requested_at_utc', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_return_item_id', models.CharField(max_length=191)),
                ('external_order_item_id', models.CharField(blank=True, max_length=191)),
                ('platform_product_id', models.CharField(blank=True, max_length=191)),
                ('platform_variant_id', models.CharField(blank=True, max_length=191)),
                ('seller_sku', models.CharField(blank=True, max_length=191)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=240)),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=8)),
                ('refund_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'commerce_refund_return_item',
                'ordering': ['refund_return_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('external_order_id', models.CharField(max_length=191)),
                ('raw_status', models.CharField(max_length=80)),
                ('canonical_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=40)),
                ('fulfillment_type', models.CharField(blank=True, max_length=40)),
                ('created_at_utc', models.DateTimeField()),
                ('paid_at_utc', models.DateTimeField(blank=True, null=True)),
                ('updated_at_utc', models.DateTimeField()),
                ('cancelled_at_utc', models.DateTimeField(blank=True, null=True)),
                ('completed_at_utc', models.DateTimeField(blank=True, null=True)),
                ('business_date', models.DateField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=8)),
                ('subtotal_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('seller_discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('platform_discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('shipping_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('order_total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('buyer_reference_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'commerce_sales_order',
                'ordering': ['-created_at_utc', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_line_id', models.CharField(max_length=191)),
                ('platform_product_id', models.CharField(max_length=191)),
                ('platform_variant_id', models.CharField(blank=True, max_length=191)),
                ('seller_sku', models.CharField(blank=True, max_length=191)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=240)),
                ('variation_snapshot', models.CharField(blank=True, max_length=240)),
                ('quantity', models.PositiveIntegerField()),
                ('original_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sale_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('line_total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(max_length=8)),
                ('raw_line_status', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'commerce_sales_order_item',
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('platform_product_id', models.CharField(blank=True, max_length=191)),
                ('platform_variant_id', models.CharField(blank=True, max_length=191)),
                ('seller_sku', models.CharField(blank=True, max_length=191)),
                ('snapshot_key', models.CharField(blank=True, editable=False, max_length=64)),
                ('on_hand_qty', models.PositiveBigIntegerField(default=0)),
                ('available_qty', models.PositiveBigIntegerField(default=0)),
                ('reserved_qty', models.PositiveBigIntegerField(default=0)),
                ('in_transit_qty', models.PositiveBigIntegerField(default=0)),
                ('pending_putaway_qty', models.PositiveBigIntegerField(default=0)),
                ('defective_qty', models.PositiveBigIntegerField(default=0)),
                ('snapshot_at_utc', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('internal_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_inventory_snapshots', to='products.productsku')),
            ],
            options={
                'db_table': 'commerce_inventory_snapshot',
                'ordering': ['-snapshot_at_utc', '-id'],
            },
        ),
    ]
