# Generated by Django 5.2.17 on 2026-09-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_fact_tables_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderBundleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_order_bundle_snapshot',
            },
        ),
    ]
