# Generated by Django 5.2.17 on 2026-08-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('integrations', '0007_rawpayload_syncqualityresult'),
        ('masterdata', '0002_alter_suppliermaster_status'),
        ('products', '0013_productsku_product_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots', to='integrations.rawpayload'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_inventory_snapshots', to='integrations.syncrun'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_inventory_snapshots', to='masterdata.storemaster'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_inventory_snapshots', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_inventory_snapshots', to='masterdata.warehousemaster'),
        ),
        migrations.AddField(
            model_name='marketplaceproductmapping',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_commerce_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceproductmapping',
            name='internal_spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_marketplace_mappings', to='products.productspu'),
        ),
        migrations.AddField(
            model_name='marketplaceproductmapping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_product_mappings', to='masterdata.storemaster'),
        ),
        migrations.AddField(
            model_name='marketplaceproductmapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_product_mappings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='marketplaceskumapping',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_commerce_skus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceskumapping',
            name='internal_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_marketplace_mappings', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='marketplaceskumapping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_sku_mappings', to='masterdata.storemaster'),
        ),
        migrations.AddField(
            model_name='marketplaceskumapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_sku_mappings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='refundreturn',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_returns', to='integrations.rawpayload'),
        ),
        migrations.AddField(
            model_name='refundreturn',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_refund_returns', to='integrations.syncrun'),
        ),
        migrations.AddField(
            model_name='refundreturn',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_refund_returns', to='masterdata.storemaster'),
        ),
        migrations.AddField(
            model_name='refundreturn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_refund_returns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='refundreturnitem',
            name='internal_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_refund_items', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='refundreturnitem',
            name='refund_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.refundreturn'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='integration_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_sales_orders', to='integrations.platformintegrationconfig'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='integrations.rawpayload'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_sales_orders', to='integrations.syncrun'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_sales_orders', to='masterdata.storemaster'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_sales_orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='refundreturn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_returns', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='internal_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_order_items', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='internal_spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_order_items', to='products.productspu'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='refundreturnitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_items', to='commerce.salesorderitem'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['tenant', 'store', 'snapshot_at_utc'], name='idx_comm_inventory_store'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['tenant', 'seller_sku', 'snapshot_at_utc'], name='idx_comm_inventory_sku'),
        ),
        migrations.AddConstraint(
            model_name='inventorysnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'snapshot_key', 'snapshot_at_utc'), name='uniq_comm_inventory_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceproductmapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'platform', 'platform_product_id'), name='uniq_comm_product_mapping'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceskumapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'platform', 'platform_variant_id'), name='uniq_comm_sku_mapping'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'store', 'created_at_utc'], name='idx_comm_order_store_time'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'canonical_status', 'updated_at_utc'], name='idx_comm_order_status_time'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'store', 'external_order_id'), name='uniq_comm_order_ext'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0), ('seller_discount_amount__gte', 0), ('platform_discount_amount__gte', 0), ('shipping_amount__gte', 0), ('tax_amount__gte', 0), ('order_total_amount__gte', 0)), name='comm_order_amounts_nonneg'),
        ),
        migrations.AddIndex(
            model_name='refundreturn',
            index=models.Index(fields=['tenant', 'store', 'requested_at_utc'], name='idx_comm_return_store_time'),
        ),
        migrations.AddIndex(
            model_name='refundreturn',
            index=models.Index(fields=['tenant', 'canonical_status'], name='idx_comm_return_status'),
        ),
        migrations.AddIndex(
            model_name='refundreturn',
            index=models.Index(fields=['tenant', 'source_updated_at_utc'], name='idx_comm_return_updated'),
        ),
        migrations.AddConstraint(
            model_name='refundreturn',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'store', 'external_return_id'), name='uniq_comm_return_ext'),
        ),
        migrations.AddConstraint(
            model_name='refundreturn',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0), ('refund_subtotal__gte', 0), ('refund_shipping_fee__gte', 0), ('refund_tax__gte', 0)), name='comm_return_amounts_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'external_line_id'), name='uniq_comm_order_line_ext'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_unit_price__gte', 0), ('sale_unit_price__gte', 0), ('discount_amount__gte', 0), ('tax_amount__gte', 0), ('line_total_amount__gte', 0)), name='comm_order_item_amt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='refundreturnitem',
            constraint=models.UniqueConstraint(fields=('refund_return', 'external_return_item_id'), name='uniq_comm_return_item_ext'),
        ),
        migrations.AddConstraint(
            model_name='refundreturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='comm_return_item_amt_nonneg'),
        ),
    ]
