# Generated by Django 5.2.17 on 2026-09-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_salesorderbundlesnapshot'),
        ('products', '0022_productbundlemigrationbatch_productbundleversion_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderbundlesnapshot',
            name='bundle_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_snapshots', to='products.productbundleversion'),
        ),
        migrations.AddField(
            model_name='salesorderbundlesnapshot',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_snapshot', to='commerce.salesorderitem'),
        ),
        migrations.AddField(
            model_name='salesorderbundlesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_bundle_snapshots', to='tenants.tenant'),
        ),
    ]
