# Generated by Django 5.2.17 on 2026-08-10 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0013_authorization_reauthorization_bindings'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('tiktok', 'TikTok')], max_length=30)),
                ('resource_type', models.CharField(choices=[('orders', 'Orders'), ('inventory', 'Inventory')], max_length=20)),
                ('import_mode', models.CharField(choices=[('initial', 'Initial'), ('incremental', 'Incremental')], max_length=20)),
                ('source_mode', models.CharField(choices=[('synthetic_contract', 'Synthetic normalized contract')], default='synthetic_contract', max_length=30)),
                ('contract_version', models.CharField(max_length=40)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('cursor_before', models.CharField(blank=True, max_length=500)),
                ('cursor_after', models.CharField(max_length=500)),
                ('watermark_before', models.DateTimeField(blank=True, null=True)),
                ('watermark_after', models.DateTimeField(blank=True, null=True)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('controlled_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_marketplace_import_batches', to=settings.AUTH_USER_MODEL)),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_batches', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceImportCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('orders', 'Orders'), ('inventory', 'Inventory')], max_length=20)),
                ('cursor', models.CharField(blank=True, max_length=500)),
                ('watermark', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advanced_cursors', to='marketplace_imports.marketplaceimportbatch')),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_cursors', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_cursors', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_variant_id', models.CharField(max_length=160)),
                ('platform_sku', models.CharField(blank=True, max_length=160)),
                ('mapping_status', models.CharField(choices=[('mapped', 'Mapped'), ('unmapped', 'Unmapped')], max_length=20)),
                ('on_hand', models.IntegerField()),
                ('reserved', models.IntegerField(default=0)),
                ('available', models.IntegerField()),
                ('incoming', models.IntegerField(default=0)),
                ('observed_at', models.DateTimeField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='marketplace_imports.marketplaceimportbatch')),
                ('product_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='integrations.marketplaceproductmapping')),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_inventory_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_order_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ordered_at', models.DateTimeField()),
                ('platform_updated_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('line_items', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace_imports.marketplaceimportbatch')),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-ordered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_refund_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('platform_updated_at', models.DateTimeField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='marketplace_imports.marketplaceimportbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='marketplace_imports.marketplaceorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_refunds', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='marketplaceimportbatch',
            index=models.Index(fields=['tenant', 'resource_type', 'status'], name='idx_market_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceimportbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'store_mapping', 'resource_type', 'idempotency_key_hash'), name='uniq_market_import_idempotency'),
        ),
        migrations.AddIndex(
            model_name='marketplaceimportcursor',
            index=models.Index(fields=['tenant', 'resource_type'], name='idx_market_cursor_resource'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceimportcursor',
            constraint=models.UniqueConstraint(fields=('tenant', 'store_mapping', 'resource_type'), name='uniq_market_import_cursor'),
        ),
        migrations.AddIndex(
            model_name='marketplaceinventorysnapshot',
            index=models.Index(fields=['tenant', 'platform_variant_id', 'observed_at'], name='idx_market_inventory_time'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinventorysnapshot',
            constraint=models.UniqueConstraint(fields=('store_mapping', 'platform_variant_id', 'observed_at'), name='uniq_market_inventory_observation'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinventorysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='market_inventory_on_hand_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinventorysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='market_inventory_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinventorysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('available__gte', 0)), name='market_inventory_available_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinventorysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('incoming__gte', 0)), name='market_inventory_incoming_gte_0'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['tenant', 'status', 'ordered_at'], name='idx_market_order_status'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(fields=('store_mapping', 'platform_order_id'), name='uniq_market_order_platform_id'),
        ),
        migrations.AddIndex(
            model_name='marketplacerefund',
            index=models.Index(fields=['tenant', 'status'], name='idx_market_refund_status'),
        ),
        migrations.AddConstraint(
            model_name='marketplacerefund',
            constraint=models.UniqueConstraint(fields=('order', 'platform_refund_id'), name='uniq_market_refund_platform_id'),
        ),
    ]
