# Generated by Django 5.2.17 on 2026-08-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_authorization_reauthorization_bindings'),
        ('marketplace_imports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceimportbatch',
            name='active_attempt_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceimportbatch',
            name='attempt_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MarketplaceImportBatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.UUIDField()),
                ('attempt_version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('import', 'Import'), ('retry', 'Retry')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('new_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('result', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('controlled_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_attempts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='marketplace_imports.marketplaceimportbatch')),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_attempts', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_attempts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'batch', 'attempt_version'], name='idx_market_attempt_batch')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'attempt_id', 'new_status'), name='uniq_market_attempt_transition')],
            },
        ),
    ]
