# Generated by Django 5.2.16 on 2026-07-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('placeholder', 'Placeholder'), ('review_pending', 'Review pending'), ('sandbox', 'Sandbox'), ('disabled', 'Disabled')], default='placeholder', max_length=30)),
                ('data_class', models.CharField(default='public_demo', max_length=40)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('output_types', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('human_confirmation_required', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_assistants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=240)),
                ('owner', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('permission_code', models.CharField(max_length=120)),
                ('data_scope_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mock', 'Mock'), ('sandbox', 'Sandbox'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('disabled', 'Disabled'), ('stale', 'Stale')], default='pending', max_length=20)),
                ('compatibility', models.CharField(choices=[('current', 'Current'), ('deprecated', 'Deprecated'), ('pending', 'Pending')], default='current', max_length=20)),
                ('deprecation_at', models.DateTimeField(blank=True, null=True)),
                ('request_fields', models.JSONField(blank=True, default=list)),
                ('response_fields', models.JSONField(blank=True, default=list)),
                ('error_codes', models.JSONField(blank=True, default=list)),
                ('change_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_api_contracts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['module', 'path', 'method', 'id'],
                'constraints': [models.UniqueConstraint(fields=('method', 'path', 'version'), name='uniq_governance_contract_version')],
            },
        ),
    ]
