# Generated by Django 5.2.17 on 2026-09-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantEvaluationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=40)),
                ('demo_input_ref', models.SlugField(max_length=110)),
                ('reason', models.CharField(max_length=500)),
                ('assistant_version', models.PositiveIntegerField()),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('response_id', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('result', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_jobs', to='governance.assistantdefinition')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_assistant_evaluation_jobs_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_assistant_evaluation_jobs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='idx_assistant_eval_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_assistant_eval_idempotency')],
            },
        ),
    ]
