# Generated by Django 5.2.17 on 2026-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_assistantevaluationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='assistant_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='result_summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assistantevaluationjob',
            name='test_input',
            field=models.TextField(blank=True),
        ),
    ]
