# Generated by Django 5.2.16 on 2026-07-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfigDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=120, unique=True)),
                ('scope_type', models.CharField(choices=[('tenant', 'Tenant'), ('system', 'System')], max_length=20)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=20)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope_type', 'config_key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=120)),
                ('scope_key', models.CharField(max_length=80)),
                ('from_version', models.PositiveIntegerField(blank=True, null=True)),
                ('to_version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create_version', 'Create version'), ('approve', 'Approve'), ('rollback', 'Rollback')], max_length=30)),
                ('masked_detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_change_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_change_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['scope_key', 'config_key', 'created_at', 'id'],
                'indexes': [models.Index(fields=['scope_key', 'config_key', 'created_at'], name='idx_config_change_log')],
            },
        ),
        migrations.CreateModel(
            name='TenantConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=120)),
                ('scope_key', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('value', models.JSONField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved for future activation'), ('effective', 'Effective'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], max_length=30)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_config_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_config_versions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='configcenter.systemconfigdefinition')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_versions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['scope_key', 'config_key', '-version'],
                'indexes': [models.Index(fields=['scope_key', 'config_key', 'status'], name='idx_config_scope_status'), models.Index(fields=['tenant', 'status', 'effective_at'], name='idx_tenant_config_effective')],
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'config_key', 'version'), name='uniq_config_scope_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='config_version_gte_1')],
            },
        ),
    ]
