from django.urls import path

from . import views


urlpatterns = [
    path("templates/", views.template_collection),
    path("templates/<int:pk>/", views.template_detail),
    path("profiles/", views.profile_collection),
    path("profiles/batch-generate/", views.profile_batch_generate),
    path("profiles/batch/", views.profile_batch_generate),
    path("profiles/<int:pk>/", views.profile_detail),
    path("profiles/<int:pk>/validate/", views.profile_validate),
    path("profiles/<int:pk>/submit/", views.profile_submit),
    path("profiles/<int:pk>/approve/", views.profile_approve),
    path("profiles/<int:pk>/publish/", views.profile_publish),
    path("workbench/options/", views.workbench_options),
    path("category-mappings/", views.category_mapping_collection),
    path("category-mappings/<int:pk>/", views.category_mapping_detail),
    path("mappings/categories/", views.category_mapping_collection),
    path("mappings/categories/<int:pk>/", views.category_mapping_detail),
    path("platform-category-mappings/", views.category_mapping_collection),
    path("platform-category-mappings/<int:pk>/", views.category_mapping_detail),
    path("attribute-mappings/", views.attribute_mapping_collection),
    path("attribute-mappings/<int:pk>/", views.attribute_mapping_detail),
    path("mappings/attributes/", views.attribute_mapping_collection),
    path("mappings/attributes/<int:pk>/", views.attribute_mapping_detail),
    path("product-attribute-mappings/", views.attribute_mapping_collection),
    path("product-attribute-mappings/<int:pk>/", views.attribute_mapping_detail),
    path("tasks/", views.task_collection),
    path("tasks/<int:pk>/", views.task_detail),
    path("publication-tasks/", views.task_collection),
    path("publication-tasks/<int:pk>/", views.task_detail),
    path("logs/", views.task_log_collection),
    path("tasks/logs/", views.task_log_collection),
    path("exceptions/", views.task_exception_collection),
    path("tasks/exceptions/", views.task_exception_collection),
    path("publication-logs/", views.task_log_collection),
    path("publication-exceptions/", views.task_exception_collection),
    path("product-details/", views.PlatformProductDetailCollectionView.as_view()),
    path("product-details/<int:pk>/", views.PlatformProductDetailView.as_view()),
    path("product-details/bulk-update/", views.platform_product_detail_bulk_update),
    path("product-details/import/", views.PlatformProductDetailImportView.as_view()),
    path("product-details/import-platform-product-ids/", views.PlatformProductIdImportView.as_view()),
]
