export const internalReadonlyModules = [
  { code: 'master_data', label: '基础档案' },
  { code: 'product_development', label: '产品开发' },
  { code: 'listing', label: '全球刊登' },
  { code: 'supply_chain', label: '供应链协同' },
  { code: 'inventory', label: '库存管理' },
  { code: 'sales', label: '销售管理' },
  { code: 'influencer_collaboration', label: '达人管理' },
  { code: 'advertising', label: '广告' },
  { code: 'analytics', label: '经营分析' },
  { code: 'business_decision', label: '经营决策' },
  { code: 'finance', label: '财务中心' },
  { code: 'reports', label: '报表中心' },
  { code: 'workflow', label: '流程协同' },
  { code: 'rpa', label: 'RPA协同' },
];

export const internalReadonlyResources = [
  { module: 'master_data', code: 'products', label: '商品主数据', fields: ['id', 'sku', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_details', label: '商品明细数据', fields: ['id', 'product_id', 'sku', 'name', 'specification', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_mappings', label: '商品映射数据', fields: ['id', 'product_id', 'platform', 'store_id', 'platform_sku', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_costs', label: '商品成本', fields: ['id', 'product_id', 'sku', 'currency', 'amount', 'effective_at', 'updated_at'] },
  { module: 'master_data', code: 'product_bundles', label: '组合商品', fields: ['id', 'product_id', 'sku', 'component_sku', 'quantity', 'status', 'updated_at'] },
  { module: 'master_data', code: 'platform_products', label: '平台商品明细数据', fields: ['id', 'platform', 'store_id', 'platform_sku', 'title', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_categories', label: '分类设置', fields: ['id', 'code', 'name', 'parent_id', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_attributes', label: '属性设置', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_colors', label: '颜色设置', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'product_specifications', label: '规格设置', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'platforms', label: '平台档案', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'country_sites', label: '国家信息', fields: ['id', 'platform_id', 'country_code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'foundation_settings', label: '基础档案设置', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'suppliers', label: '供应商档案', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'stores', label: '店铺档案', fields: ['id', 'platform', 'code', 'name', 'status', 'updated_at'] },
  { module: 'master_data', code: 'warehouses', label: '仓库档案', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'product_development', code: 'product_research', label: '新品市调', fields: ['id', 'name', 'status', 'updated_at'] },
  { module: 'product_development', code: 'selection_requirements', label: '选品提报', fields: ['id', 'name', 'owner_id', 'status', 'updated_at'] },
  { module: 'product_development', code: 'requirement_reviews', label: '需求审核', fields: ['id', 'requirement_id', 'status', 'updated_at'] },
  { module: 'product_development', code: 'development_projects', label: '开发项目', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: 'product_development', code: 'development_archives', label: '开发产品档案', fields: ['id', 'project_id', 'sku', 'status', 'updated_at'] },
  { module: 'product_development', code: 'development_costs', label: '成本核算', fields: ['id', 'project_id', 'currency', 'amount', 'updated_at'] },
  { module: 'product_development', code: 'development_sales', label: '销售数据', fields: ['id', 'project_id', 'period', 'amount', 'updated_at'] },
  { module: 'product_development', code: 'selection_retrospectives', label: '选品复盘', fields: ['id', 'project_id', 'status', 'updated_at'] },
  { module: 'product_development', code: 'development_dashboard', label: '效能看板', fields: ['id', 'period', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_tasks', label: '刊登任务', fields: ['id', 'platform', 'store_id', 'product_id', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_workbench', label: '全球刊登工作台', fields: ['id', 'platform', 'store_id', 'status', 'updated_at'] },
  { module: 'listing', code: 'online_products', label: '在线商品', fields: ['id', 'platform', 'store_id', 'platform_sku', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_category_mappings', label: '平台类目映射', fields: ['id', 'platform', 'category_id', 'platform_category_id', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_attribute_mappings', label: '商品属性映射', fields: ['id', 'platform', 'attribute_id', 'platform_attribute_id', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_logs', label: '刊登日志', fields: ['id', 'task_id', 'status', 'created_at', 'updated_at'] },
  { module: 'listing', code: 'listing_exceptions', label: '刊登异常', fields: ['id', 'task_id', 'code', 'status', 'created_at', 'updated_at'] },
  { module: 'listing', code: 'listing_profiles', label: '刊登资料', fields: ['id', 'platform', 'site_id', 'name', 'status', 'updated_at'] },
  { module: 'listing', code: 'listing_templates', label: '刊登模板', fields: ['id', 'platform', 'name', 'status', 'updated_at'] },
  { module: 'supply_chain', code: 'consolidations', label: '集货管理', fields: ['id', 'supplier_id', 'warehouse_id', 'status', 'updated_at'] },
  { module: 'supply_chain', code: 'purchase_orders', label: '采购订单', fields: ['id', 'order_number', 'supplier_id', 'status', 'ordered_at', 'updated_at'] },
  { module: 'supply_chain', code: 'supplier_shipments', label: '供应商发货', fields: ['id', 'purchase_order_id', 'tracking_number', 'status', 'shipped_at', 'updated_at'] },
  { module: 'supply_chain', code: 'supplier_performance', label: '供应商绩效', fields: ['id', 'supplier_id', 'period', 'score', 'updated_at'] },
  { module: 'sales', code: 'sales_orders', label: '销售订单', fields: ['id', 'order_number', 'store_id', 'status', 'ordered_at', 'updated_at'] },
  { module: 'sales', code: 'sales_overview', label: '销售总览', fields: ['id', 'store_id', 'period', 'quantity', 'amount', 'updated_at'] },
  { module: 'sales', code: 'sales_returns', label: '退款退货', fields: ['id', 'sales_order_id', 'return_number', 'status', 'created_at', 'updated_at'] },
  { module: 'sales', code: 'store_sales', label: '门店销售', fields: ['id', 'store_id', 'period', 'amount', 'currency', 'updated_at'] },
  { module: 'sales', code: 'sku_sales', label: 'SKU销售', fields: ['id', 'sku', 'store_id', 'period', 'quantity', 'amount', 'updated_at'] },
  { module: 'sales', code: 'sales_exports', label: '销售明细导出', fields: ['id', 'period', 'status', 'created_at', 'updated_at'] },
  { module: 'sales', code: 'sales_data_quality', label: '数据同步与质量', fields: ['id', 'store_id', 'period', 'status', 'updated_at'] },
  { module: 'inventory', code: 'inventory_snapshots', label: '库存快照', fields: ['id', 'warehouse_id', 'sku', 'available_quantity', 'reserved_quantity', 'snapshot_at', 'updated_at'] },
  { module: 'inventory', code: 'inventory_workbench', label: '库存工作台', fields: ['id', 'warehouse_id', 'sku', 'available_quantity', 'updated_at'] },
  { module: 'inventory', code: 'inventory_alerts', label: '库存预警', fields: ['id', 'warehouse_id', 'sku', 'alert_type', 'status', 'updated_at'] },
  { module: 'inventory', code: 'replenishment_suggestions', label: '补货建议', fields: ['id', 'warehouse_id', 'sku', 'suggested_quantity', 'status', 'updated_at'] },
  { module: 'sales', code: 'prices', label: '价格中心', fields: ['id', 'sku', 'store_id', 'currency', 'amount', 'effective_at', 'updated_at'] },
  { module: 'supply_chain', code: 'shipments', label: '发运管理', fields: ['id', 'shipment_number', 'warehouse_id', 'tracking_number', 'status', 'shipped_at', 'updated_at'] },
  { module: 'influencer_collaboration', code: 'influencers', label: '达人档案', fields: ['id', 'platform', 'handle', 'display_name', 'status', 'updated_at'] },
  { module: 'influencer_collaboration', code: 'outreach_tasks', label: '建联任务', fields: ['id', 'influencer_id', 'owner_id', 'status', 'due_at', 'updated_at'] },
  { module: 'influencer_collaboration', code: 'sample_fulfillments', label: '送样履约', fields: ['id', 'influencer_id', 'sku', 'tracking_number', 'status', 'shipped_at', 'updated_at'] },
  { module: 'influencer_collaboration', code: 'influencer_performance', label: 'BD绩效', fields: ['id', 'owner_id', 'period', 'score', 'updated_at'] },
  { module: 'influencer_collaboration', code: 'influencer_bd_config', label: 'BD配置', fields: ['id', 'code', 'name', 'status', 'updated_at'] },
  { module: ['advertising', 'analytics'], code: 'advertising_overview', label: '广告总览', fields: ['id', 'platform', 'store', 'spend', 'attributed_sales', 'orders', 'roas', 'acos', 'quality_status', 'updated_at'] },
  { module: ['advertising', 'analytics'], code: 'advertising_performance', label: '广告投放分析', fields: ['id', 'campaign', 'product', 'sku', 'impressions', 'clicks', 'ctr', 'cpc', 'orders', 'quality_status', 'updated_at'] },
  { module: ['advertising', 'finance'], code: 'advertising_reconciliation', label: '广告费用对账', fields: ['id', 'platform', 'account', 'period_start', 'period_end', 'currency', 'report_spend', 'statement_charge', 'booked_amount', 'difference_amount', 'reconciliation_status', 'updated_at'] },
  { module: 'analytics', code: 'analytics_overview', label: '经营总览', fields: ['id', 'period', 'amount', 'status', 'updated_at'] },
  { module: 'analytics', code: 'analytics_sales', label: '销售分析', fields: ['id', 'period', 'amount', 'status', 'updated_at'] },
  { module: 'analytics', code: 'analytics_inventory', label: '库存分析', fields: ['id', 'period', 'quantity', 'status', 'updated_at'] },
  { module: 'business_decision', code: 'lifecycle_reviews', label: '生命周期复盘', fields: ['id', 'product_id', 'status', 'updated_at'] },
  { module: 'business_decision', code: 'lifecycle_history', label: '复盘历史', fields: ['id', 'product_id', 'status', 'updated_at'] },
  { module: 'business_decision', code: 'clearance_requests', label: '清仓申请', fields: ['id', 'product_id', 'status', 'updated_at'] },
  { module: 'business_decision', code: 'business_alerts', label: '经营预警', fields: ['id', 'code', 'status', 'updated_at'] },
  { module: 'finance', code: 'finance_imports', label: '财务导入', fields: ['id', 'platform', 'period', 'status', 'updated_at'] },
  { module: 'finance', code: 'finance_analytics', label: '财务分析', fields: ['id', 'period', 'currency', 'amount', 'updated_at'] },
  { module: 'finance', code: 'platform_statements', label: '平台账单', fields: ['id', 'platform', 'period', 'currency', 'amount', 'updated_at'] },
  { module: 'finance', code: 'withdrawal_records', label: '提现记录', fields: ['id', 'platform', 'currency', 'amount', 'status', 'updated_at'] },
  { module: 'finance', code: 'bank_receipts', label: '银行到账', fields: ['id', 'currency', 'amount', 'status', 'updated_at'] },
  { module: 'finance', code: 'reconciliation_exceptions', label: '对账异常', fields: ['id', 'platform', 'currency', 'amount', 'status', 'updated_at'] },
  { module: 'finance', code: 'reconciliation_matches', label: '对账差异', fields: ['id', 'platform', 'currency', 'amount', 'status', 'updated_at'] },
  { module: 'reports', code: 'basic_reports', label: '基础报表', fields: ['id', 'code', 'name', 'period', 'updated_at'] },
  { module: 'reports', code: 'report_exports', label: '报表导出', fields: ['id', 'report_id', 'status', 'created_at', 'updated_at'] },
  { module: 'workflow', code: 'approval_records', label: '审批中心', fields: ['id', 'subject_id', 'status', 'updated_at'] },
  { module: 'workflow', code: 'workflow_exceptions', label: '异常中心', fields: ['id', 'code', 'status', 'updated_at'] },
  { module: 'workflow', code: 'collaboration_events', label: '协同回填', fields: ['id', 'subject_id', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_tasks', label: '任务中心', fields: ['id', 'code', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_runs', label: '运行记录', fields: ['id', 'task_id', 'status', 'created_at', 'updated_at'] },
  { module: 'rpa', code: 'rpa_devices', label: '设备管理', fields: ['id', 'code', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_manual_queue', label: '人工队列', fields: ['id', 'task_id', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_stability', label: '稳定性', fields: ['id', 'period', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_account_locks', label: '账号串行锁', fields: ['id', 'status', 'updated_at'] },
  { module: 'rpa', code: 'rpa_page_signatures', label: '页面签名', fields: ['id', 'status', 'updated_at'] },
];

export const internalReadonlyResourceFields = Object.fromEntries(
  internalReadonlyResources.map(({ code, fields }) => [code, fields]),
);
