import { describe, it, expect } from 'vitest';
import { buildEditorPermissionGroups, permissionAssignmentAvailability, permissionChanges } from '../src/utils/permissionEditor';
const pages=[{key:'foundation',label:'基础档案',children:[{key:'details',code:'menu.listings.products_platform_details.view',label:'平台商品明细',path:'/products/platform-details',module:'listings',action_codes:['listings.product_detail.view']} ]}, {key:'listing',label:'全球刊登',children:[{key:'online',code:'menu.listings.online.view',label:'在线商品',path:'/listings/online-products',module:'listings',action_codes:['listings.products.view']}]}];
const permissions=[{code:'listings.product_detail.view',module:'listings',permission_type:'action'},{code:'listings.product_detail.manage',module:'listings',permission_type:'action'},{code:'listings.products.view',module:'listings',permission_type:'action'},{code:'listings.products.manage',module:'listings',permission_type:'action'},{code:'rpa.devices.manage',module:'rpa',permission_type:'action'}];
describe('角色权限模块编辑',()=>{
  it('停用刊登页面不会隐藏仍启用的基础档案平台明细及共用维护权限',()=>{const hidden=permissionAssignmentAvailability(permissions,pages,{global_listing:'disabled',masterdata:'enabled',rpa:'disabled'});expect(hidden.has('listings.products.manage')).toBe(true);expect(hidden.has('menu.listings.online.view')).toBe(true);expect(hidden.has('listings.product_detail.manage')).toBe(false);expect(hidden.has('rpa.devices.manage')).toBe(true);});
  it('维护权限与查看权限归入同一真实页面，停用页面不会重新回到其他权限',()=>{const unavailable=permissionAssignmentAvailability(permissions,pages,{global_listing:'disabled',masterdata:'enabled',rpa:'disabled'});const groups=buildEditorPermissionGroups({permissions,menuTree:pages,type:'action',unavailable});expect(groups.map(group=>group.label)).toEqual(['基础档案']);expect(groups[0].children[0].permissions.map(permission=>permission.code)).toEqual(['listings.product_detail.view','listings.product_detail.manage']);});
  it('变更计数基于去重后的实际权限集合',()=>{expect(permissionChanges(['a','a','b'],['b','c','c'])).toEqual({added:1,removed:1});});
});
