<template>
  <section class="detail-page">
    <header class="page-header"><div><p class="eyebrow">UI-P5 · 商品主数据</p><h1 class="page-title">商品详情</h1><p>编码冻结是独立授权动作，不改变商品生命周期或销售状态。</p></div><el-tag :type="stateTagType(state)">{{ state }}</el-tag></header>
    <el-alert v-if="message" :title="message" :type="state==='error'?'error':'warning'" show-icon :closable="false"/>
    <el-card v-loading="loading" shadow="never"><template #header>基础属性</template><el-descriptions :column="2" border><el-descriptions-item label="SPU">{{detail.spu_code||'-'}}</el-descriptions-item><el-descriptions-item label="商品名称">{{detail.product_name||'-'}}</el-descriptions-item><el-descriptions-item label="类目">{{detail.category||'-'}}</el-descriptions-item><el-descriptions-item label="生命周期">{{detail.lifecycle_status||'-'}}</el-descriptions-item><el-descriptions-item label="销售状态">{{detail.sales_status||'-'}}</el-descriptions-item><el-descriptions-item label="编码状态">{{detail.is_code_frozen?'已冻结':'未冻结'}}</el-descriptions-item></el-descriptions></el-card>
    <el-card shadow="never"><template #header>授权范围内的 SKU</template><el-table :data="relatedSkus" border empty-text="暂无可见 SKU"><el-table-column prop="sku_code" label="SKU" min-width="150"/><el-table-column prop="size" label="尺码"/><el-table-column prop="material" label="材质"/><el-table-column prop="package_weight" label="重量"/><el-table-column label="编码冻结"><template #default="{row}">{{row.is_code_frozen?'是':'否'}}</template></el-table-column></el-table></el-card>
    <div class="actions"><el-button v-if="canFreeze" type="primary" :disabled="loading||!detail.id||detail.is_code_frozen" :loading="freezing" @click="handleFreeze">冻结编码</el-button><el-alert v-else title="当前角色没有 products.master.freeze 权限，仅可查看。" type="info" :closable="false"/></div>
  </section>
</template>
<script setup>
import{computed,onMounted,ref}from'vue';import{useRoute}from'vue-router';import{useAuthStore}from'../../stores/auth';import{fetchProductMasterDetail,fetchProductSkuList,freezeProductCode}from'../../api/products';import{apiState,collectionRows,detailData,stateTagType}from'../../utils/businessResponse';
const route=useRoute(),auth=useAuthStore();const detail=ref({}),skus=ref([]),loading=ref(false),freezing=ref(false),state=ref('loading'),message=ref('');const canFreeze=computed(()=>auth.hasPermission('products.master.freeze'));const relatedSkus=computed(()=>skus.value.filter(sku=>sku.spu===detail.value.id));
async function load(){loading.value=true;message.value='';const[d,s]=await Promise.all([fetchProductMasterDetail(route.params.id||1),fetchProductSkuList({spu_id:route.params.id||1,page:1,page_size:100})]);if(d.success&&s.success){detail.value=detailData(d.data);skus.value=collectionRows(s.data);state.value=apiState(d.data)}else{state.value='error';message.value=d.message||s.message}loading.value=false}
async function handleFreeze(){freezing.value=true;const response=await freezeProductCode(detail.value.id);if(response.success){detail.value={...detail.value,...detailData(response.data)};state.value=apiState(response.data)}else{state.value='error';message.value=response.message}freezing.value=false}
onMounted(load);
</script>
<style scoped>.detail-page{display:grid;gap:16px}.page-header{display:flex;justify-content:space-between;gap:16px}.page-header p{margin:4px 0 0;color:#64748b}.eyebrow{font-size:12px;font-weight:700;color:#0f766e!important}.actions{display:flex;align-items:center;gap:12px}</style>
