<template>
  <section class="business-page">
    <header class="page-header"><div><h1>{{ title }}</h1><p>{{ subtitle }}</p></div><el-button v-if="!isDimensionMode&&canManage" type="primary" @click="openCreate">{{mode==='category'?'新增一级分类':mode==='color'?'设置颜色':'新增'}}</el-button></header>
    <el-alert v-if="mode==='category'" title="分类按 L1、L2、L3 树状展示；点击“新增下级”可在当前目录下建立子分类，只有 L3 可用于新增商品。" type="info" :closable="false" />
    <div v-if="mode==='category'" class="category-tree-panel" v-loading="loading">
      <el-tree :data="categoryTree" node-key="id" default-expand-all :expand-on-click-node="true" :props="{children:'children',label:'name'}">
        <template #default="{data}">
          <div class="category-tree-node">
            <div class="category-tree-node__label"><span class="folder-icon">{{data.level<3?'📁':'📄'}}</span><el-tag size="small" effect="plain">L{{data.level}}</el-tag><span class="category-code">{{data.code}}</span><strong>{{data.name}}</strong><span class="category-status">{{data.is_active?'启用':'停用'}}</span></div>
            <div class="category-tree-node__actions" @click.stop><el-button v-if="canManage&&data.level<3" link type="success" @click="openCreate(data)">新增下级</el-button><el-button v-if="canManage" link type="primary" @click="edit(data)">编辑</el-button><el-button v-if="canManage" link type="danger" @click="remove(data)">删除</el-button></div>
          </div>
        </template>
      </el-tree>
      <el-empty v-if="!loading&&!categoryTree.length" description="暂无分类目录，请先新增一级分类"/>
    </div>
    <el-table v-else :data="displayRows" row-key="id" border v-loading="loading">
      <el-table-column v-if="mode==='category'" prop="level" label="层级" width="80"/><el-table-column v-if="mode!=='color'" prop="code" label="编码"/><el-table-column prop="name" :label="mode==='color'?'颜色内容':'中文名称'"/>
      <el-table-column v-if="isDimensionMode" label="规格内容" min-width="300"><template #default="{row}">{{ specificationValues(row).join('、')||'未设置' }}</template></el-table-column>
      <el-table-column label="状态" width="90"><template #default="{row}">{{row.is_active?'启用':'停用'}}</template></el-table-column>
      <el-table-column v-if="mode!=='color'" label="操作" :width="mode==='category'?230:150"><template #default="{row}"><el-button v-if="canManage&&mode==='category'&&row.level<3" link type="success" @click="openCreate(row)">新增下级</el-button><el-button v-if="canManage" link type="primary" @click="edit(row)">{{isDimensionMode?(mode==='specification'?'设置规格':'设置属性'):'编辑'}}</el-button><el-button v-if="canManage&&!isDimensionMode" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="visible" :title="dialogTitle" width="560px"><el-form label-position="top"><template v-if="mode==='category'"><el-form-item label="层级"><el-select v-model="form.level" :disabled="!!form.id"><el-option v-for="n in 3" :key="n" :label="`L${n}`" :value="n"/></el-select></el-form-item><el-form-item v-if="form.level>1" label="上级分类"><el-select v-model="form.parent"><el-option v-for="x in parents" :key="x.id" :label="`L${x.level} ${x.code} ${x.name}`" :value="x.id"/></el-select></el-form-item></template><el-form-item v-if="!isDimensionMode&&mode!=='color'" label="编码"><el-input v-model="form.code" :disabled="!!form.id||mode==='attribute'" :placeholder="mode==='attribute'?'保存后自动生成 1 位流水号':''"/></el-form-item><el-form-item v-if="!isDimensionMode&&mode!=='color'" label="中文名称"><el-input v-model="form.name"/></el-form-item><el-form-item v-if="mode==='color'" label="颜色内容（每行一个颜色）"><el-input v-model="form.contents" type="textarea" :rows="8" placeholder="白色&#10;黑色&#10;藏青色"/></el-form-item><el-form-item v-if="isDimensionMode" label="规格内容（每行一个规格）"><el-input v-model="form.dimensions" type="textarea" :rows="8" placeholder="150cm×220cm&#10;180cm×200cm&#10;200cm×230cm"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import{computed,onMounted,reactive,ref,watch}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{useAuthStore}from'../../stores/auth';import{createProductAttribute,createProductCategory,createProductColor,deleteProductAttribute,deleteProductCategory,deleteProductColor,fetchProductAttributes,fetchProductCategories,fetchProductColors,updateProductAttribute,updateProductAttributes,updateProductCategory,updateProductColor}from'../../api/products';import{collectionRows}from'../../utils/businessResponse';
const props=defineProps({mode:{type:String,required:true}}),auth=useAuthStore(),rows=ref([]),loading=ref(false),visible=ref(false),form=reactive({});const isDimensionMode=computed(()=>props.mode==='specification');const cfg=computed(()=>({category:['分类设置','维护三级商品分类与编码','products.category.manage'],color:['颜色设置','直接维护可用于生成 SKU 的颜色内容','products.color.manage'],attribute:['属性设置','维护独立商品属性，编码由系统按 1-9 自动生成','products.attribute.manage'],specification:['规格设置','为末级分类直接维护可用于生成 SKU 的规格内容','products.specification.manage']}[props.mode]));const title=computed(()=>cfg.value[0]),subtitle=computed(()=>cfg.value[1]),canManage=computed(()=>auth.hasPermission(cfg.value[2])),dialogTitle=computed(()=>props.mode==='color'?'设置 SKU 颜色':isDimensionMode.value?'设置 SKU 规格':`${form.id?'编辑':'新增'}${title.value.replace('设置','')}`),parents=computed(()=>rows.value.filter(x=>x.level===form.level-1));
const categoryTree=computed(()=>{const map=new Map(rows.value.map(item=>[item.id,{...item,children:[]}])) ;const roots=[];for(const item of map.values()){if(item.parent&&map.has(item.parent))map.get(item.parent).children.push(item);else roots.push(item)}const sort=items=>{items.sort((a,b)=>String(a.code).localeCompare(String(b.code),undefined,{numeric:true}));items.forEach(x=>sort(x.children));return items};return sort(roots)});
const displayRows=computed(()=>props.mode==='category'?categoryTree.value:rows.value);
function specificationValues(row){const dims=row.spec_dimensions||[];if(dims.length===1&&dims[0].code==='spec')return dims[0].values||[];return dims.flatMap(x=>x.values?.length?x.values:[x.name]).filter(Boolean)}
async function load(){loading.value=true;let r;if(props.mode==='color')r=await fetchProductColors();else if(props.mode==='attribute')r=await fetchProductAttributes();else r=await fetchProductCategories(isDimensionMode.value?{level:3}:{});rows.value=r.success?collectionRows(r.data):[];loading.value=false}function openCreate(parent=null){Object.assign(form,{id:null,level:parent?parent.level+1:1,parent:parent?.id||null,code:'',name:'',contents:props.mode==='color'?rows.value.filter(x=>x.is_active).map(x=>x.name).join('\n'):''});visible.value=true}function edit(row){Object.assign(form,row,{dimensions:specificationValues(row).join('\n')});visible.value=true}
async function saveColors(){const values=[...new Set(form.contents.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];const desired=new Set(values),byName=new Map(rows.value.map(x=>[x.name,x]));for(const name of values){const current=byName.get(name);const r=current?(current.is_active?{success:true}:await updateProductColor(current.id,{is_active:true})):await createProductColor({code:name,name});if(!r.success)return r}for(const item of rows.value.filter(x=>x.is_active&&!desired.has(x.name))){const removed=await deleteProductColor(item.id);if(!removed.success){const disabled=await updateProductColor(item.id,{is_active:false});if(!disabled.success)return disabled}}return{success:true}}
async function save(){if(props.mode==='category'&&form.level>1&&!form.parent)return ElMessage.warning('请选择上级分类');let r;if(isDimensionMode.value){const values=[...new Set(form.dimensions.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];const dims=values.length?[{code:'spec',name:'规格',values}]:[];r=await updateProductAttributes(form.id,dims)}else if(props.mode==='attribute')r=form.id?await updateProductAttribute(form.id,{name:form.name,is_active:form.is_active}):await createProductAttribute({name:form.name});else if(props.mode==='color')r=await saveColors();else r=form.id?await updateProductCategory(form.id,{name:form.name,is_active:form.is_active}):await createProductCategory({level:form.level,parent:form.parent,code:form.code,name:form.name});if(!r.success)return ElMessage.error(r.message||'保存失败');ElMessage.success('保存成功');visible.value=false;load()}
async function remove(row){await ElMessageBox.confirm(`确认删除“${row.name}”？仅无关联业务数据时允许删除。`,'删除确认',{type:'warning'});const r=props.mode==='color'?await deleteProductColor(row.id):props.mode==='attribute'?await deleteProductAttribute(row.id):await deleteProductCategory(row.id);if(!r.success)return ElMessage.error(r.message||'删除失败');ElMessage.success('删除成功');load()}
watch(()=>props.mode,load);onMounted(load)
</script>

<style scoped>
.category-tree-panel{min-height:240px;padding:12px 16px;border:1px solid #d9e2ec;border-radius:8px;background:#fff}.category-tree-panel :deep(.el-tree-node__content){height:46px;border-bottom:1px solid #edf2f7}.category-tree-node{display:flex;flex:1;align-items:center;justify-content:space-between;min-width:0;padding-right:12px}.category-tree-node__label,.category-tree-node__actions{display:flex;align-items:center;gap:10px}.folder-icon{font-size:18px}.category-code{min-width:38px;color:#64748b;font-family:monospace}.category-status{margin-left:8px;color:#64748b;font-size:12px}@media(max-width:760px){.category-tree-node__actions{gap:2px}.category-status{display:none}}
</style>
