# Generated by Django 5.2.15 on 2026-07-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPAAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=128)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_agents', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RPATask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=80)),
                ('business_type', models.CharField(max_length=80)),
                ('business_id', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('manual_required', 'Manual required'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('priority', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('screenshot_url', models.URLField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retry_count', models.PositiveIntegerField(default=3)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to='rpa.rpaagent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_tasks', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RPATaskStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('screenshot_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='rpa.rpatask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_task_step_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RPATool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_tools', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BigSellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_identifier', models.CharField(max_length=100)),
                ('credential_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_seller_accounts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'account_identifier'), name='uniq_bigseller_account_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='rpatask',
            index=models.Index(fields=['tenant', 'status'], name='idx_rpa_task_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='rpatask',
            index=models.Index(fields=['business_type', 'business_id'], name='idx_rpa_task_business_ref'),
        ),
        migrations.AddConstraint(
            model_name='rpatool',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_rpa_tool_code_per_tenant'),
        ),
    ]
