# Generated by Django 5.2.16 on 2026-07-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_rpaagent_user'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPAPageSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('page_type', models.CharField(max_length=80)),
                ('signature_hash', models.CharField(max_length=128)),
                ('detected_status', models.CharField(choices=[('stable', 'Stable'), ('changed', 'Changed')], default='stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_page_signatures', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'page_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RPATaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('manual_required', 'Manual required'), ('cancelled', 'Cancelled')], default='claimed', max_length=30)),
                ('failed_step', models.CharField(blank=True, max_length=120)),
                ('last_success_step', models.CharField(blank=True, max_length=120)),
                ('masked_error', models.TextField(blank=True)),
                ('manual_required', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attempts', to='rpa.rpaagent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='rpa.rpatask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_task_attempts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['task_id', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='RPAEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('page_snapshot', 'Page snapshot'), ('log_reference', 'Log reference')], max_length=30)),
                ('placeholder_url', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='rpa.rpatask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_evidence', to='tenants.tenant')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='rpa.rpataskattempt')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('placeholder_url__startswith', 'demo'), ('placeholder_url__startswith', 'example'), ('placeholder_url__startswith', 'local-placeholder'), _connector='OR'), name='rpa_evidence_placeholder_only')],
            },
        ),
        migrations.CreateModel(
            name='RPAAccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('account_alias', models.CharField(max_length=120)),
                ('lock_status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('expired', 'Expired')], default='held', max_length=20)),
                ('acquired_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_locks', to='rpa.rpatask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_account_locks', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'account_alias', '-acquired_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('lock_status', 'held')), fields=('tenant', 'platform', 'account_alias'), name='uniq_held_rpa_platform_account')],
            },
        ),
        migrations.AddConstraint(
            model_name='rpataskattempt',
            constraint=models.UniqueConstraint(fields=('task', 'attempt_no'), name='uniq_rpa_task_attempt_no'),
        ),
    ]
