# Generated by Django 5.2.16 on 2026-07-17 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='controlled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rpo_minutes', models.PositiveIntegerField()),
                ('rto_minutes', models.PositiveIntegerField()),
                ('backup_summary', models.CharField(max_length=500)),
                ('backup_checksum_masked', models.CharField(max_length=128)),
                ('approval_ref', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review_pending', 'Review pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('manual_required', 'Manual required'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilot_recovery_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_recovery_plans_created', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_plans', to='pilot.pilotenvironment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_recovery_plans', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review_pending', 'Review pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('manual_required', 'Manual required'), ('cancelled', 'Cancelled')], default='running', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actual_rpo_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_rto_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('result_summary', models.CharField(blank=True, max_length=1000)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_recovery_drills', to='tenants.tenant')),
                ('recovery_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drills', to='pilot.recoveryplan')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReleasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_channel', models.CharField(max_length=30)),
                ('commit_sha', models.CharField(max_length=64)),
                ('tag', models.CharField(blank=True, max_length=120)),
                ('demo_tenant_refs', models.JSONField(default=list)),
                ('observation_minutes', models.PositiveIntegerField()),
                ('stop_conditions', models.JSONField(default=list)),
                ('rollback_point', models.CharField(max_length=200)),
                ('database_compatibility', models.CharField(max_length=20)),
                ('approval_ref', models.CharField(blank=True, max_length=160)),
                ('rollback_approval_ref', models.CharField(blank=True, max_length=160)),
                ('rollback_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_approval_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review_pending', 'Review pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('rollback_required', 'Rollback required'), ('rolled_back', 'Rolled back'), ('manual_required', 'Manual required'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('manual_context', models.CharField(blank=True, max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('result_summary', models.CharField(blank=True, max_length=1000)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilot_release_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_release_plans_created', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_plans', to='pilot.pilotenvironment')),
                ('rollback_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilot_rollbacks_approved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_release_plans', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PilotAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('permission_code', models.CharField(max_length=120)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(max_length=500)),
                ('approval_ref', models.CharField(blank=True, max_length=160)),
                ('rollback_approval_ref', models.CharField(blank=True, max_length=160)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('version', models.PositiveIntegerField()),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_audit_events', to='tenants.tenant')),
                ('recovery_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='pilot.recoveryplan')),
                ('release_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='pilot.releaseplan')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TopologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('host_role', models.CharField(max_length=30)),
                ('network_zone', models.CharField(max_length=30)),
                ('exposure', models.CharField(max_length=20)),
                ('host_ref_masked', models.CharField(max_length=120)),
                ('port_hint', models.CharField(blank=True, max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_services', to='pilot.pilotenvironment')),
            ],
            options={
                'ordering': ['environment_id', 'host_role', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='CapacityObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('metric_code', models.CharField(max_length=40)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('partial', 'Partial'), ('missing', 'Missing'), ('stale', 'Stale')], default='missing', max_length=20)),
                ('source', models.CharField(default='fixed_demo', max_length=80)),
                ('observed_at', models.DateTimeField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_observations', to='pilot.pilotenvironment')),
            ],
            options={
                'ordering': ['-observed_at', 'service_name', 'metric_code', 'id'],
                'indexes': [models.Index(fields=['environment', 'metric_code', 'observed_at'], name='idx_pilot_capacity')],
            },
        ),
        migrations.CreateModel(
            name='ReadinessGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('evidence_ref', models.CharField(blank=True, max_length=160)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_gates', to='pilot.pilotenvironment')),
            ],
            options={
                'ordering': ['environment_id', 'code'],
                'constraints': [models.UniqueConstraint(fields=('environment', 'code'), name='uniq_pilot_readiness_gate')],
            },
        ),
        migrations.AddConstraint(
            model_name='recoveryplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_recovery_plan_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='releaseplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_release_plan_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='pilotauditevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_pilot_audit_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='topologyservice',
            constraint=models.UniqueConstraint(fields=('environment', 'service_name'), name='uniq_pilot_topology_service'),
        ),
    ]
