# Generated by Django 5.2.16 on 2026-07-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_pilotauditevent_actor_type_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('status', models.CharField(default='controlled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='pilot.pilotenvironment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_evidence_references', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'environment_id', 'reference'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'environment', 'reference'), name='uniq_pilot_evidence_ref')],
            },
        ),
        migrations.CreateModel(
            name='PilotTargetAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=64)),
                ('status', models.CharField(default='controlled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_aliases', to='pilot.pilotenvironment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_target_aliases', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'environment_id', 'alias'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'environment', 'alias'), name='uniq_pilot_target_alias')],
            },
        ),
    ]
