# Generated by Django 5.2.17 on 2026-09-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_pilotevidencereference_pilottargetalias'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(choices=[('performance', 'Performance'), ('deploy', 'Deploy'), ('recovery', 'Recovery'), ('rollback', 'Rollback')], max_length=20)),
                ('request_version', models.PositiveIntegerField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_id', models.CharField(max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('manual_required', 'Manual required')], default='queued', max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('runner_job_id', models.CharField(blank=True, max_length=160)),
                ('runner_reference', models.CharField(blank=True, max_length=240)),
                ('result_metrics', models.JSONField(blank=True, default=dict)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('result_summary', models.CharField(blank=True, max_length=1000)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='pilot.performancerun')),
                ('recovery_drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='pilot.recoverydrill')),
                ('recovery_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='pilot.recoveryplan')),
                ('release_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='pilot.releaseplan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_executions_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_executions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'execution_type', 'status'], name='idx_pilot_execution_state'), models.Index(fields=['tenant', 'request_id'], name='idx_pilot_execution_request')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_pilot_execution_idempotency')],
            },
        ),
    ]
