# Generated by Django 5.2.17 on 2026-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0006_pilotexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerun',
            name='target_alias',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
