# Generated by Django 5.2.17 on 2026-09-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0007_performancerun_target_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotexecution',
            name='runner_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
