# Generated by Django 5.2.16 on 2026-08-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_no', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(max_length=8)),
                ('category_code', models.CharField(blank=True, max_length=120)),
                ('field_schema', models.JSONField(default=dict)),
                ('default_values', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_listing_templates', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_templates', to='masterdata.platformmaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_templates', to='tenants.tenant')),
            ],
            options={'ordering': ['tenant_id', 'template_no', '-version']},
        ),
        migrations.CreateModel(
            name='ListingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_no', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category_code', models.CharField(blank=True, max_length=120)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('media', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('external_listing_id', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_listing_profiles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_listing_profiles', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_profiles', to='products.productspu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_profiles', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_profiles', to='tenants.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='listings.listingtemplate')),
            ],
            options={'ordering': ['tenant_id', '-updated_at']},
        ),
        migrations.CreateModel(
            name='ListingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_sku', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('external_variant_id', models.CharField(blank=True, max_length=160)),
                ('is_enabled', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='listings.listingprofile')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_variants', to='products.productsku')),
            ],
            options={'ordering': ['profile_id', 'seller_sku']},
        ),
        migrations.CreateModel(
            name='ListingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_changes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='listings.listingprofile')),
            ],
            options={'ordering': ['profile_id', '-created_at'], 'indexes': [models.Index(fields=['profile', 'created_at'], name='idx_listing_change')]},
        ),
        migrations.CreateModel(
            name='ListingPublicationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('pause', 'Pause')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_jobs', to='listings.listingprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_listing_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_publication_jobs', to='tenants.tenant')),
            ],
            options={'ordering': ['tenant_id', '-created_at'], 'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='idx_listing_job_status')], 'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_listing_job_key')]},
        ),
        migrations.AddIndex(model_name='listingtemplate', index=models.Index(fields=['tenant', 'platform', 'country_code'], name='idx_listing_template_site')),
        migrations.AddConstraint(model_name='listingtemplate', constraint=models.UniqueConstraint(fields=('tenant', 'template_no', 'version'), name='uniq_listing_template_ver')),
        migrations.AddIndex(model_name='listingprofile', index=models.Index(fields=['tenant', 'store', 'status'], name='idx_listing_store_status')),
        migrations.AddIndex(model_name='listingprofile', index=models.Index(fields=['tenant', 'product'], name='idx_listing_product')),
        migrations.AddConstraint(model_name='listingprofile', constraint=models.UniqueConstraint(fields=('tenant', 'profile_no'), name='uniq_listing_profile_no')),
        migrations.AddConstraint(model_name='listingvariant', constraint=models.UniqueConstraint(fields=('profile', 'seller_sku'), name='uniq_listing_seller_sku')),
    ]
