# Generated by Django 5.2.16 on 2026-07-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productstatustransition_uniq_product_status_transition_recommendation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=80)),
                ('alert_type', models.CharField(choices=[('stockout_risk', 'Stockout risk'), ('overstock_risk', 'Overstock risk'), ('low_coverage', 'Low coverage'), ('slow_moving', 'Slow moving')], max_length=30)),
                ('threshold_config', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('silence_minutes', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alert_rules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'rule_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('alert_type', models.CharField(choices=[('stockout_risk', 'Stockout risk'), ('overstock_risk', 'Overstock risk'), ('low_coverage', 'Low coverage'), ('slow_moving', 'Slow moving')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('available_stock', models.DecimalField(decimal_places=4, max_digits=16)),
                ('in_transit_stock', models.DecimalField(decimal_places=4, max_digits=16)),
                ('average_daily_sales', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('coverage_days', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dedup_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('silenced', 'Silenced'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reason', models.TextField()),
                ('source_summary', models.JSONField(default=dict)),
                ('triggered_at', models.DateTimeField()),
                ('silenced_until', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_inventory_alerts', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_alerts', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_alerts', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='tenants.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.inventoryalertrule')),
            ],
            options={
                'ordering': ['tenant_id', '-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('deduplicated', 'Deduplicated'), ('assigned', 'Assigned'), ('silenced', 'Silenced'), ('closed', 'Closed')], max_length=30)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_alert_events', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.inventoryalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alert_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'alert_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'alert', 'event_type'], name='idx_inventory_alert_event')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryalertrule',
            index=models.Index(fields=['tenant', 'alert_type', 'is_enabled'], name='idx_inventory_rule_type'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalertrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'rule_code', 'version'), name='uniq_inventory_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='inventory_rule_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='idx_inventory_alert_state'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['tenant', 'sku', 'alert_type'], name='idx_inventory_alert_sku'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalert',
            constraint=models.UniqueConstraint(fields=('tenant', 'dedup_key'), name='uniq_inventory_alert_dedup'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalert',
            constraint=models.CheckConstraint(condition=models.Q(('spu__isnull', False), ('sku__isnull', False), _connector='OR'), name='inventory_alert_has_product'),
        ),
    ]
