# Generated by Django 5.2.16 on 2026-07-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=80)),
                ('alert_type', models.CharField(choices=[('sales_drop', 'Sales drop'), ('slow_moving', 'Slow moving'), ('reconciliation_difference', 'Reconciliation difference'), ('supplier_overdue', 'Supplier overdue'), ('rpa_failure', 'RPA failure'), ('page_signature_change', 'Page signature change'), ('sync_failure', 'Sync failure'), ('stale_data', 'Stale data')], max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('condition_config', models.JSONField(default=dict)),
                ('silence_minutes', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alert_rules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'rule_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=80)),
                ('business_id', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dedup_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('silenced', 'Silenced'), ('closed', 'Closed')], default='open', max_length=20)),
                ('triggered_at', models.DateTimeField()),
                ('silenced_until', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_business_alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='tenants.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.businessalertrule')),
            ],
            options={
                'ordering': ['tenant_id', '-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAlertActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('triggered', 'Triggered'), ('deduplicated', 'Deduplicated'), ('assigned', 'Assigned'), ('silenced', 'Silenced'), ('closed', 'Closed')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_alert_action_logs', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='alerts.businessalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alert_action_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'alert_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'alert', 'action'], name='idx_business_alert_action')],
            },
        ),
        migrations.AddIndex(
            model_name='businessalertrule',
            index=models.Index(fields=['tenant', 'alert_type', 'is_enabled'], name='idx_business_alert_rule'),
        ),
        migrations.AddConstraint(
            model_name='businessalertrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'rule_code', 'version'), name='uniq_business_alert_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='businessalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='business_alert_rule_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='businessalert',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='idx_business_alert_state'),
        ),
        migrations.AddIndex(
            model_name='businessalert',
            index=models.Index(fields=['tenant', 'business_type', 'business_id'], name='idx_business_alert_target'),
        ),
        migrations.AddConstraint(
            model_name='businessalert',
            constraint=models.UniqueConstraint(fields=('tenant', 'dedup_key'), name='uniq_business_alert_dedup'),
        ),
    ]
