from django.urls import path

from .views import (
    CapacityObservationListView,
    CapacitySummaryView,
    ReadinessView,
    RecoveryDrillListView,
    RecoveryDrillResultView,
    RecoveryPlanActionView,
    RecoveryPlanCollectionView,
    RecoveryPlanDetailView,
    ReleasePlanActionView,
    ReleasePlanCollectionView,
    ReleasePlanDetailView,
    TopologyVerifyMockView,
    TopologyView,
)
from .ui_p8_views import ControlRoomView, ResourceActionView, ResourceCollectionView, ResourceDetailView


urlpatterns = [
    path("control-room/", ControlRoomView.as_view(), name="pilot-control-room"),
    path("security-reviews/", ResourceCollectionView.as_view(resource="security"), name="pilot-security-reviews"),
    path("security-reviews/<int:pk>/", ResourceDetailView.as_view(resource="security"), name="pilot-security-review-detail"),
    path("security-reviews/<int:pk>/submit/", ResourceActionView.as_view(resource="security", action_name="submit"), name="pilot-security-review-submit"),
    path("security-reviews/<int:pk>/approve/", ResourceActionView.as_view(resource="security", action_name="approve"), name="pilot-security-review-approve"),
    path("security-reviews/<int:pk>/reject/", ResourceActionView.as_view(resource="security", action_name="reject"), name="pilot-security-review-reject"),
    path("verification-runs/", ResourceCollectionView.as_view(resource="verification"), name="pilot-verification-runs"),
    path("verification-runs/<int:pk>/", ResourceDetailView.as_view(resource="verification"), name="pilot-verification-run-detail"),
    path("verification-runs/<int:pk>/submit/", ResourceActionView.as_view(resource="verification", action_name="submit"), name="pilot-verification-submit"),
    path("verification-runs/<int:pk>/approve/", ResourceActionView.as_view(resource="verification", action_name="approve"), name="pilot-verification-approve"),
    path("verification-runs/<int:pk>/record-result/", ResourceActionView.as_view(resource="verification", action_name="record-result"), name="pilot-verification-result"),
    path("verification-runs/<int:pk>/cancel/", ResourceActionView.as_view(resource="verification", action_name="cancel"), name="pilot-verification-cancel"),
    path("performance-runs/", ResourceCollectionView.as_view(resource="performance"), name="pilot-performance-runs"),
    path("performance-runs/<int:pk>/", ResourceDetailView.as_view(resource="performance"), name="pilot-performance-run-detail"),
    path("performance-runs/<int:pk>/submit/", ResourceActionView.as_view(resource="performance", action_name="submit"), name="pilot-performance-submit"),
    path("performance-runs/<int:pk>/approve/", ResourceActionView.as_view(resource="performance", action_name="approve"), name="pilot-performance-approve"),
    path("performance-runs/<int:pk>/record-result/", ResourceActionView.as_view(resource="performance", action_name="record-result"), name="pilot-performance-result"),
    path("performance-runs/<int:pk>/cancel/", ResourceActionView.as_view(resource="performance", action_name="cancel"), name="pilot-performance-cancel"),
    path("entry-decisions/", ResourceCollectionView.as_view(resource="entry"), name="pilot-entry-decisions"),
    path("entry-decisions/<int:pk>/", ResourceDetailView.as_view(resource="entry"), name="pilot-entry-decision-detail"),
    path("entry-decisions/<int:pk>/submit/", ResourceActionView.as_view(resource="entry", action_name="submit"), name="pilot-entry-submit"),
    path("entry-decisions/<int:pk>/approve/", ResourceActionView.as_view(resource="entry", action_name="approve"), name="pilot-entry-approve"),
    path("entry-decisions/<int:pk>/reject/", ResourceActionView.as_view(resource="entry", action_name="reject"), name="pilot-entry-reject"),
    path("readiness/", ReadinessView.as_view(), name="pilot-readiness"),
    path("topology/", TopologyView.as_view(), name="pilot-topology"),
    path("topology/verify-mock/", TopologyVerifyMockView.as_view(), name="pilot-topology-verify-mock"),
    path("capacity/summary/", CapacitySummaryView.as_view(), name="pilot-capacity-summary"),
    path("capacity/observations/", CapacityObservationListView.as_view(), name="pilot-capacity-observations"),
    path("recovery-plans/", RecoveryPlanCollectionView.as_view(), name="pilot-recovery-plans"),
    path("recovery-plans/<int:pk>/", RecoveryPlanDetailView.as_view(), name="pilot-recovery-plan-detail"),
    path("recovery-plans/<int:pk>/submit-review/", RecoveryPlanActionView.as_view(action_name="submit-review"), name="pilot-recovery-submit"),
    path("recovery-plans/<int:pk>/approve/", RecoveryPlanActionView.as_view(action_name="approve"), name="pilot-recovery-approve"),
    path("recovery-plans/<int:pk>/reject/", RecoveryPlanActionView.as_view(action_name="reject"), name="pilot-recovery-reject"),
    path("recovery-plans/<int:pk>/schedule/", RecoveryPlanActionView.as_view(action_name="schedule"), name="pilot-recovery-schedule"),
    path("recovery-plans/<int:pk>/start/", RecoveryPlanActionView.as_view(action_name="start"), name="pilot-recovery-start"),
    path("recovery-plans/<int:pk>/resume/", RecoveryPlanActionView.as_view(action_name="resume"), name="pilot-recovery-resume"),
    path("recovery-plans/<int:pk>/cancel/", RecoveryPlanActionView.as_view(action_name="cancel"), name="pilot-recovery-cancel"),
    path("recovery-drills/", RecoveryDrillListView.as_view(), name="pilot-recovery-drills"),
    path("recovery-drills/<int:pk>/record-result/", RecoveryDrillResultView.as_view(), name="pilot-recovery-result"),
    path("release-plans/", ReleasePlanCollectionView.as_view(), name="pilot-release-plans"),
    path("release-plans/<int:pk>/", ReleasePlanDetailView.as_view(), name="pilot-release-plan-detail"),
    path("release-plans/<int:pk>/submit-review/", ReleasePlanActionView.as_view(action_name="submit-review"), name="pilot-release-submit"),
    path("release-plans/<int:pk>/approve/", ReleasePlanActionView.as_view(action_name="approve"), name="pilot-release-approve"),
    path("release-plans/<int:pk>/reject/", ReleasePlanActionView.as_view(action_name="reject"), name="pilot-release-reject"),
    path("release-plans/<int:pk>/schedule/", ReleasePlanActionView.as_view(action_name="schedule"), name="pilot-release-schedule"),
    path("release-plans/<int:pk>/start/", ReleasePlanActionView.as_view(action_name="start"), name="pilot-release-start"),
    path("release-plans/<int:pk>/resume/", ReleasePlanActionView.as_view(action_name="resume"), name="pilot-release-resume"),
    path("release-plans/<int:pk>/cancel/", ReleasePlanActionView.as_view(action_name="cancel"), name="pilot-release-cancel"),
    path("release-plans/<int:pk>/record-result/", ReleasePlanActionView.as_view(action_name="record-result"), name="pilot-release-result"),
    path("release-plans/<int:pk>/approve-rollback/", ReleasePlanActionView.as_view(action_name="approve-rollback"), name="pilot-release-approve-rollback"),
    path("release-plans/<int:pk>/resume-rollback/", ReleasePlanActionView.as_view(action_name="resume-rollback"), name="pilot-release-resume-rollback"),
    path("release-plans/<int:pk>/record-rollback/", ReleasePlanActionView.as_view(action_name="record-rollback"), name="pilot-release-record-rollback"),
]
