# Generated by Django 5.2.16 on 2026-08-08 11:05



import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models





class Migration(migrations.Migration):



    initial = True



    dependencies = [

        ('consolidation', '0005_alter_consolidationevent_action'),

        ('packing', '0006_packingboxconsumptionaction'),

        ('tenants', '0001_initial'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]



    operations = [

        migrations.CreateModel(

            name='LooseCargoShipment',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('shipment_no', models.CharField(max_length=80)),

                ('route_type', models.CharField(choices=[('loose_cargo_groupage', 'Loose cargo groupage')], default='loose_cargo_groupage', max_length=32)),

                ('region_code', models.CharField(max_length=80)),

                ('origin_site_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),

                ('origin_site_snapshot', models.JSONField(blank=True, default=dict)),

                ('destination_country_code', models.CharField(blank=True, max_length=8)),

                ('destination_port_code', models.CharField(blank=True, max_length=32)),

                ('destination_warehouse_code', models.CharField(blank=True, max_length=64)),

                ('note', models.TextField(blank=True)),

                ('forwarder_reference', models.CharField(blank=True, max_length=128)),

                ('groupage_reference', models.CharField(blank=True, max_length=128)),

                ('container_reference', models.CharField(blank=True, max_length=128)),

                ('customs_reference', models.CharField(blank=True, max_length=128)),

                ('transport_reference', models.CharField(blank=True, max_length=128)),

                ('planned_dispatch_at', models.DateTimeField(blank=True, null=True)),

                ('actual_dispatch_at', models.DateTimeField(blank=True, null=True)),

                ('port_arrived_at', models.DateTimeField(blank=True, null=True)),

                ('warehouse_arrived_at', models.DateTimeField(blank=True, null=True)),

                ('cleared_at', models.DateTimeField(blank=True, null=True)),

                ('status', models.CharField(choices=[('draft', 'Draft'), ('loading', 'Loading'), ('customs_declared', 'Customs declared'), ('dispatched', 'Dispatched'), ('port_arrived', 'Port arrived'), ('warehouse_arrived', 'Warehouse arrived'), ('warehouse_cleared', 'Warehouse cleared'), ('cancelled', 'Cancelled')], default='draft', max_length=28)),

                ('version', models.PositiveIntegerField(default=1)),

                ('cancelled_at', models.DateTimeField(blank=True, null=True)),

                ('cancelled_reason', models.TextField(blank=True)),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('updated_at', models.DateTimeField(auto_now=True)),

                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_shipments', to=settings.AUTH_USER_MODEL)),

                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_shipments', to=settings.AUTH_USER_MODEL)),

                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),

                ('customs_declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_declared_shipments', to=settings.AUTH_USER_MODEL)),

                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_shipments', to=settings.AUTH_USER_MODEL)),

                ('port_arrived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='port_arrived_shipments', to=settings.AUTH_USER_MODEL)),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargo_shipments', to='tenants.tenant')),

                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_shipments', to=settings.AUTH_USER_MODEL)),

                ('warehouse_arrived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_arrived_shipments', to=settings.AUTH_USER_MODEL)),

            ],

            options={

                'ordering': ['tenant_id', '-created_at', '-id'],

            },

        ),

        migrations.CreateModel(

            name='ShipmentBoxAllocation',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('source_consolidation_version', models.PositiveIntegerField()),

                ('source_release_version', models.PositiveIntegerField()),

                ('supplier_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),

                ('order_ids_snapshot', models.JSONField(blank=True, default=list)),

                ('order_nos_snapshot', models.JSONField(blank=True, default=list)),

                ('batch_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),

                ('batch_no_snapshot', models.CharField(blank=True, max_length=80)),

                ('box_no_snapshot', models.CharField(max_length=100)),

                ('quantity_snapshot', models.PositiveBigIntegerField(default=0)),

                ('weight_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),

                ('volume_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),

                ('snapshot', models.JSONField(blank=True, default=dict)),

                ('state', models.CharField(choices=[('transferred', 'Transferred'), ('dispatched', 'Dispatched'), ('arrived_port', 'Arrived at port'), ('arrived_warehouse', 'Arrived at warehouse'), ('cleared', 'Cleared')], default='transferred', max_length=24)),

                ('version', models.PositiveIntegerField(default=1)),

                ('transferred_at', models.DateTimeField(auto_now_add=True)),

                ('dispatched_at', models.DateTimeField(blank=True, null=True)),

                ('arrived_port_at', models.DateTimeField(blank=True, null=True)),

                ('arrived_warehouse_at', models.DateTimeField(blank=True, null=True)),

                ('cleared_at', models.DateTimeField(blank=True, null=True)),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('updated_at', models.DateTimeField(auto_now=True)),

                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_allocations', to='packing.packingbox')),

                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_allocations', to='consolidation.loosecargoconsolidation')),

                ('consolidation_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_box_allocations', to='consolidation.consolidationboxallocation')),

                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipment_allocations', to=settings.AUTH_USER_MODEL)),

                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_shipment_allocations', to=settings.AUTH_USER_MODEL)),

                ('packing_box_consumption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_allocations', to='packing.packingboxconsumption')),

                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_allocations', to='shipping.loosecargoshipment')),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_box_allocations', to='tenants.tenant')),

            ],

            options={

                'ordering': ['shipment_id', 'box_id', 'id'],

            },

        ),

        migrations.CreateModel(

            name='ShipmentEvent',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('action', models.CharField(choices=[('create', 'Create shipment'), ('update', 'Update shipment'), ('allocate', 'Allocate boxes'), ('customs_declare', 'Customs declare'), ('dispatch', 'Dispatch'), ('port_arrival', 'Port arrival'), ('warehouse_arrival', 'Warehouse arrival'), ('clearance', 'Warehouse clearance'), ('exception', 'Shipment exception'), ('cancel', 'Cancel shipment')], max_length=32)),

                ('actor_type', models.CharField(max_length=32)),

                ('actor_id', models.PositiveBigIntegerField()),

                ('channel', models.CharField(default='internal', max_length=32)),

                ('expected_version', models.PositiveIntegerField(blank=True, null=True)),

                ('source_version', models.PositiveIntegerField(blank=True, null=True)),

                ('before', models.JSONField(blank=True, default=dict)),

                ('after', models.JSONField(blank=True, default=dict)),

                ('external_reference', models.CharField(blank=True, max_length=128)),

                ('reason', models.TextField(blank=True)),

                ('idempotency_key', models.CharField(max_length=128)),

                ('request_hash', models.CharField(max_length=64)),

                ('occurred_at', models.DateTimeField()),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shipping.shipmentboxallocation')),

                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_events', to='packing.packingbox')),

                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shipping.loosecargoshipment')),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_events', to='tenants.tenant')),

            ],

            options={

                'ordering': ['tenant_id', 'created_at', 'id'],

            },

        ),

        migrations.AddIndex(

            model_name='loosecargoshipment',

            index=models.Index(fields=['tenant', 'region_code', 'status'], name='idx_shipping_scope'),

        ),

        migrations.AddConstraint(

            model_name='loosecargoshipment',

            constraint=models.UniqueConstraint(fields=('tenant', 'shipment_no'), name='uniq_shipping_shipment_no'),

        ),

        migrations.AddConstraint(

            model_name='loosecargoshipment',

            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='shipping_shipment_version_gt_zero'),

        ),

        migrations.AddConstraint(

            model_name='loosecargoshipment',

            constraint=models.CheckConstraint(condition=models.Q(('route_type', 'loose_cargo_groupage')), name='shipping_shipment_route_loose'),

        ),

        migrations.AddIndex(

            model_name='shipmentboxallocation',

            index=models.Index(fields=['tenant', 'shipment', 'state'], name='idx_shipping_allocation_state'),

        ),

        migrations.AddIndex(

            model_name='shipmentboxallocation',

            index=models.Index(fields=['tenant', 'consolidation', 'state'], name='idx_shipping_source_scope'),

        ),

        migrations.AddConstraint(

            model_name='shipmentboxallocation',

            constraint=models.UniqueConstraint(fields=('tenant', 'box'), name='uniq_shipping_active_box'),

        ),

        migrations.AddConstraint(

            model_name='shipmentboxallocation',

            constraint=models.UniqueConstraint(fields=('tenant', 'consolidation_allocation'), name='uniq_shipping_source_allocation'),

        ),

        migrations.AddConstraint(

            model_name='shipmentboxallocation',

            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='shipping_allocation_version_gt_zero'),

        ),

        migrations.AddConstraint(

            model_name='shipmentboxallocation',

            constraint=models.CheckConstraint(condition=models.Q(('quantity_snapshot__gt', 0)), name='shipping_allocation_qty_gt_zero'),

        ),

        migrations.AddConstraint(

            model_name='shipmentboxallocation',

            constraint=models.CheckConstraint(condition=models.Q(('source_release_version__gt', 0)), name='shipping_source_release_version_gt_zero'),

        ),

        migrations.AddIndex(

            model_name='shipmentevent',

            index=models.Index(fields=['tenant', 'shipment', 'action', 'created_at'], name='idx_shipping_event'),

        ),

        migrations.AddConstraint(

            model_name='shipmentevent',

            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_shipping_event_key'),

        ),

        migrations.AddConstraint(

            model_name='shipmentevent',

            constraint=models.CheckConstraint(condition=models.Q(('request_hash__regex', '^[0-9a-fA-F]{64}$')), name='shipping_event_hash_hex'),

        ),

        migrations.AddConstraint(

            model_name='shipmentevent',

            constraint=models.CheckConstraint(condition=models.Q(('actor_id__gt', 0)), name='shipping_event_actor_positive'),

        ),

    ]
