# Generated by Django 5.2.16 on 2026-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentboxallocation',
            name='state',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('transferred', 'Transferred'), ('dispatched', 'Dispatched'), ('arrived_port', 'Arrived at port'), ('arrived_warehouse', 'Arrived at warehouse'), ('cleared', 'Cleared')], default='transferred', max_length=24),
        ),
    ]
