# Generated by Django 5.2.15 on 2026-07-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed'), ('retrying', 'Retrying')], max_length=30)),
                ('request_url', models.URLField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='APIDataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_data_quality_checks', to='tenants.tenant')),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='integrations.apisynclog')),
            ],
            options={
                'ordering': ['sync_log_id', 'check_type'],
            },
        ),
        migrations.CreateModel(
            name='APISyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=30)),
                ('sync_type', models.CharField(choices=[('sales_order', 'Sales order'), ('inventory', 'Inventory'), ('inbound', 'Inbound'), ('shipment', 'Shipment'), ('settlement_bill', 'Settlement bill'), ('withdrawal', 'Withdrawal')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=30)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retry_count', models.PositiveIntegerField(default=3)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_tasks', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'sync_type'],
            },
        ),
        migrations.AddField(
            model_name='apisynclog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.apisynctask'),
        ),
        migrations.CreateModel(
            name='APIIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=30)),
                ('shop_code', models.CharField(max_length=80)),
                ('api_base_url', models.URLField()),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('api_secret_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_integration_configs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'shop_code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform', 'shop_code'), name='uniq_api_config_shop_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='apisynctask',
            index=models.Index(fields=['tenant', 'platform', 'sync_type'], name='idx_api_task_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='apisynctask',
            index=models.Index(fields=['status', 'next_sync_at'], name='idx_api_task_schedule'),
        ),
    ]
