# Generated by Django 5.2.16 on 2026-07-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='auth_scheme',
            field=models.CharField(default='hmac_sha256', max_length=40),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='credential_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='credential_key_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='credential_ref',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='credential_status',
            field=models.CharField(choices=[('placeholder', 'Placeholder'), ('active', 'Active'), ('rotation_required', 'Rotation required'), ('revoked', 'Revoked')], default='placeholder', max_length=30),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='environment',
            field=models.CharField(choices=[('mock', 'Mock'), ('sandbox', 'Sandbox'), ('production', 'Production')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiintegrationconfig',
            name='least_privilege_scope',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
