# Generated by Django 5.2.16 on 2026-07-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_apiintegrationconfig_auth_scheme_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegrationconfig',
            name='platform',
            field=models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apisynctask',
            name='platform',
            field=models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlatformIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('account_alias', models.CharField(max_length=120)),
                ('environment', models.CharField(choices=[('mock', 'Mock'), ('sandbox', 'Sandbox'), ('production', 'Production')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending_review', 'Pending review')], default='disabled', max_length=30)),
                ('credential_ciphertext', models.TextField(blank=True)),
                ('credential_key_version', models.CharField(blank=True, max_length=40)),
                ('credential_fingerprint', models.CharField(blank=True, max_length=64)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_platform_integration_configs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_integration_configs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'account_alias'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=20)),
                ('masked_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_audit_logs', to='tenants.tenant')),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='integrations.platformintegrationconfig')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformintegrationconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'account_alias', 'environment'), name='uniq_platform_integration_per_tenant'),
        ),
    ]
