# Generated by Django 5.2.16 on 2026-07-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_apiintegrationconfig_platform_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('sales_order', 'Sales order'), ('inventory', 'Inventory'), ('settlement_bill', 'Settlement bill'), ('withdrawal', 'Withdrawal'), ('mock_record', 'Mock record')], max_length=40)),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual'), ('interval', 'Interval'), ('cron', 'Cron')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('disabled', 'Disabled'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_retry_count', models.PositiveIntegerField(default=3)),
                ('backoff_base_seconds', models.PositiveIntegerField(default=1)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_jobs', to='integrations.platformintegrationconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'resource_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_key', models.CharField(max_length=80)),
                ('cursor_value', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='tenants.tenant')),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to='integrations.syncjob')),
            ],
            options={
                'ordering': ['tenant_id', 'sync_job_id', 'cursor_key'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('masked_error_message', models.TextField(blank=True)),
                ('masked_log', models.JSONField(blank=True, default=dict)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.syncjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('signature_status', models.CharField(choices=[('mock_valid', 'Mock valid'), ('invalid', 'Invalid'), ('not_configured', 'Not configured')], max_length=30)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='received', max_length=30)),
                ('payload_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'status'], name='idx_sync_job_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'resource_type'], name='idx_sync_job_tenant_resource'),
        ),
        migrations.AddConstraint(
            model_name='synccursor',
            constraint=models.UniqueConstraint(fields=('tenant', 'sync_job', 'cursor_key'), name='uniq_sync_cursor_key'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['tenant', 'status'], name='idx_sync_run_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['run_id'], name='idx_sync_run_run_id'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_sync_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'event_id'), name='uniq_webhook_event_per_tenant'),
        ),
    ]
