# Generated by Django 5.2.16 on 2026-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_syncjob_synccursor_syncrun_webhookevent_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncrun',
            name='uniq_sync_run_idempotency',
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'sync_job', 'idempotency_key'), name='uniq_sync_run_job_idempotency'),
        ),
    ]
