# Generated by Django 5.2.16 on 2026-07-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_remove_syncrun_uniq_sync_run_idempotency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='lock_acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='lock_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='lock_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
