# Generated by Django 5.2.16 on 2026-08-04 01:57

import base64
import binascii
import hashlib
import json

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SAFE_MARKERS = ("mock", "demo", "synthetic", "placeholder", "not-a-real", "example")


def _is_safe_mock_value(value):
    if isinstance(value, dict):
        return bool(value) and all(_is_safe_mock_value(item) for item in value.values())
    if isinstance(value, list):
        return bool(value) and all(_is_safe_mock_value(item) for item in value)
    if not isinstance(value, str):
        return False
    lowered = value.lower()
    return bool(lowered) and any(marker in lowered for marker in SAFE_MARKERS)


def _is_safe_legacy_ciphertext(value):
    if not value:
        return True
    if not value.startswith("test-only:"):
        return False
    try:
        encoded = value.removeprefix("test-only:")
        payload = json.loads(base64.urlsafe_b64decode(encoded.encode()).decode())
    except (ValueError, UnicodeDecodeError, binascii.Error, json.JSONDecodeError):
        return False
    return isinstance(payload, dict) and _is_safe_mock_value(payload.get("credentials"))


def migrate_synthetic_credential_references(apps, schema_editor):
    PlatformIntegrationConfig = apps.get_model("integrations", "PlatformIntegrationConfig")
    APIIntegrationConfig = apps.get_model("integrations", "APIIntegrationConfig")
    blocked_count = 0

    for config in PlatformIntegrationConfig.objects.all().iterator():
        if not config.credential_ciphertext:
            continue
        if not _is_safe_legacy_ciphertext(config.credential_ciphertext):
            blocked_count += 1
            continue
        credential_id = f"synthetic-legacy-config-{config.pk}-credential"
        token_id = f"synthetic-legacy-config-{config.pk}-token"
        config.credential_id = credential_id
        config.token_id = token_id
        config.credential_mask = {"credential": "synthetic-legacy-***", "token": "synthetic-legacy-***"}
        config.credential_reference_version = 1
        config.credential_key_version = "reference-v1"
        config.credential_fingerprint = hashlib.sha256(f"{credential_id}:{token_id}".encode()).hexdigest()
        config.save(
            update_fields=[
                "credential_id",
                "token_id",
                "credential_mask",
                "credential_reference_version",
                "credential_key_version",
                "credential_fingerprint",
            ]
        )

    for config in APIIntegrationConfig.objects.all().iterator():
        legacy_values = [config.api_key_encrypted, config.api_secret_encrypted]
        if not any(legacy_values):
            continue
        if any(value and not _is_safe_mock_value(value) for value in legacy_values):
            blocked_count += 1
            continue
        if not config.credential_ref:
            config.credential_ref = f"synthetic-legacy-api-config-{config.pk}"
        config.credential_status = "rotation_required"
        config.credential_key_version = "reference-v1"
        config.save(update_fields=["credential_ref", "credential_status", "credential_key_version"])

    if blocked_count:
        raise RuntimeError(
            f"Credential reference migration blocked for {blocked_count} record(s); key-custody approval is required."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_syncjob_lock_acquired_at_syncjob_lock_expires_at_and_more'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiintegrationconfig',
            options={'ordering': ['tenant_id', 'platform', 'shop_code'], 'verbose_name': 'Legacy API integration config', 'verbose_name_plural': 'Legacy API integration configs'},
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_mask',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_reference_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='token_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(migrate_synthetic_credential_references, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='apiintegrationconfig',
            name='api_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='apiintegrationconfig',
            name='api_secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='platformintegrationconfig',
            name='credential_ciphertext',
        ),
        migrations.AlterField(
            model_name='integrationauditlog',
            name='integration_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='integrations.platformintegrationconfig'),
        ),
        migrations.AlterField(
            model_name='integrationauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_audit_logs', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='MarketplaceStoreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('region', models.CharField(max_length=8)),
                ('platform_store_id', models.CharField(max_length=120)),
                ('platform_identity_key', models.CharField(max_length=64)),
                ('merchant_subject_id', models.CharField(max_length=160)),
                ('shop_cipher', models.CharField(blank=True, max_length=255)),
                ('credential_id', models.CharField(max_length=160)),
                ('token_id', models.CharField(max_length=160)),
                ('credential_mask', models.JSONField(blank=True, default=dict)),
                ('credential_reference_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_marketplace_store_authorizations', to=settings.AUTH_USER_MODEL)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_authorizations', to='integrations.platformintegrationconfig')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_authorizations', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_store_authorizations', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_marketplace_store_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'store_id'],
            },
        ),
        migrations.AddField(
            model_name='integrationauditlog',
            name='store_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='integrations.marketplacestoreauthorization'),
        ),
        migrations.AddIndex(
            model_name='marketplacestoreauthorization',
            index=models.Index(fields=['tenant', 'status'], name='idx_market_auth_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='marketplacestoreauthorization',
            index=models.Index(fields=['tenant', 'store'], name='idx_market_auth_tenant_store'),
        ),
        migrations.AddConstraint(
            model_name='marketplacestoreauthorization',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_identity_key'), name='uniq_market_store_global_identity'),
        ),
        migrations.AddConstraint(
            model_name='marketplacestoreauthorization',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'store'), name='uniq_market_store_tenant_link'),
        ),
    ]
