# Generated by Django 5.2.17 on 2026-08-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_syncjob_lock_acquired_at_syncjob_lock_expires_at_and_more'),
        ('masterdata', '0002_alter_suppliermaster_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='resource_type',
            field=models.CharField(choices=[('sales_order', 'Sales order'), ('refund_return', 'Refund or return'), ('inventory', 'Inventory'), ('settlement_bill', 'Settlement bill'), ('withdrawal', 'Withdrawal'), ('mock_record', 'Mock record')], max_length=40),
        ),
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('resource_type', models.CharField(max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=191)),
                ('schema_version', models.CharField(max_length=40)),
                ('content_hash', models.CharField(max_length=64)),
                ('object_reference', models.CharField(blank=True, max_length=500)),
                ('pii_classification', models.CharField(choices=[('none', 'None'), ('masked', 'Masked'), ('restricted', 'Restricted')], default='restricted', max_length=20)),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_raw_payloads', to='masterdata.storemaster')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_payloads', to='integrations.syncrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_raw_payloads', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-fetched_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'fetched_at'], name='idx_raw_payload_resource'), models.Index(fields=['tenant', 'expires_at'], name='idx_raw_payload_expiry')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform', 'store', 'resource_type', 'external_id', 'content_hash'), name='uniq_raw_payload_identity')],
            },
        ),
        migrations.CreateModel(
            name='SyncQualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=40)),
                ('check_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail')], max_length=20)),
                ('expected_count', models.PositiveBigIntegerField(default=0)),
                ('actual_count', models.PositiveBigIntegerField(default=0)),
                ('missing_count', models.PositiveBigIntegerField(default=0)),
                ('duplicate_count', models.PositiveBigIntegerField(default=0)),
                ('invalid_count', models.PositiveBigIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField()),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_results', to='integrations.syncrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_quality_results', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'checked_at'], name='idx_sync_quality_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sync_run', 'resource_type', 'check_code'), name='uniq_sync_quality_check')],
            },
        ),
    ]
