# Generated by Django 5.2.16 on 2026-08-03 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def block_unmigrated_legacy_credentials(apps, schema_editor):
    PlatformIntegrationConfig = apps.get_model("integrations", "PlatformIntegrationConfig")
    if PlatformIntegrationConfig.objects.exclude(credential_ciphertext="").exists():
        raise RuntimeError(
            "Legacy integration credential ciphertext exists. Migrate each value to an approved external "
            "credential reference before applying integrations.0007. No legacy value was changed or displayed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_syncjob_lock_acquired_at_syncjob_lock_expires_at_and_more'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_mask',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_reference_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='token_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(block_unmigrated_legacy_credentials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='integrationauditlog',
            name='integration_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='integrations.platformintegrationconfig'),
        ),
        migrations.AlterField(
            model_name='integrationauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_audit_logs', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='MarketplaceStoreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('tiktok', 'TikTok Shop')], max_length=30)),
                ('region', models.CharField(max_length=8)),
                ('platform_store_id', models.CharField(max_length=160)),
                ('platform_identity_key', models.CharField(max_length=64)),
                ('merchant_subject_id', models.CharField(max_length=160)),
                ('shop_cipher', models.CharField(blank=True, max_length=255)),
                ('credential_id', models.CharField(blank=True, max_length=160)),
                ('token_id', models.CharField(blank=True, max_length=160)),
                ('credential_mask', models.JSONField(blank=True, default=dict)),
                ('credential_reference_version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_due_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('masked_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_marketplace_store_authorizations', to=settings.AUTH_USER_MODEL)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_authorizations', to='integrations.platformintegrationconfig')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_authorizations', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_store_authorizations', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_marketplace_store_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant_id', 'platform', 'store_id'],
            },
        ),
        migrations.AddField(
            model_name='integrationauditlog',
            name='store_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='integrations.marketplacestoreauthorization'),
        ),
        migrations.AddIndex(
            model_name='marketplacestoreauthorization',
            index=models.Index(fields=['tenant', 'status'], name='idx_market_auth_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='marketplacestoreauthorization',
            index=models.Index(fields=['tenant', 'platform'], name='idx_market_auth_platform'),
        ),
        migrations.AddConstraint(
            model_name='marketplacestoreauthorization',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_identity_key'), name='uniq_marketplace_store_global_identity'),
        ),
        migrations.AddConstraint(
            model_name='marketplacestoreauthorization',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'store'), name='uniq_marketplace_auth_internal_store'),
        ),
    ]
