# Generated by Django 5.2.16 on 2026-08-04 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_remove_legacy_credential_columns'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOAuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('region', models.CharField(max_length=8)),
                ('redirect_target_code', models.CharField(max_length=40)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_fingerprint_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('callback_received', 'Callback received'), ('exchanged', 'Exchanged'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=24)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField()),
                ('operation_id_hash', models.CharField(max_length=64)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('contract_version', models.CharField(default='a2-synthetic-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_attempts', to='integrations.platformintegrationconfig')),
                ('internal_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_attempts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_attempts', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_attempts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_oauth_tenant_status'), models.Index(fields=['expires_at'], name='idx_oauth_expires')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_oauth_attempt_tenant_idempotency')],
            },
        ),
    ]
