# Generated by Django 5.2.16 on 2026-08-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_remove_legacy_credential_columns'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthStateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('region', models.CharField(max_length=8)),
                ('state_hash', models.CharField(max_length=64)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('requested_scopes', models.JSONField(blank=True, default=list)),
                ('session_binding', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_oauth_state_sessions', to=settings.AUTH_USER_MODEL)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_state_sessions', to='integrations.platformintegrationconfig')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oauth_state_sessions', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_state_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'platform', 'status'], name='idx_oauth_state_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('state_hash',), name='uniq_oauth_state_hash')],
            },
        ),
    ]

