# Generated by Django 5.2.16 on 2026-08-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_marketplaceoauthattempt'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacestoreauthorization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoking', 'Revoking'), ('reconcile_required', 'Reconcile required'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceOAuthAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('initiate', 'Initiate'), ('refresh', 'Refresh'), ('revoke', 'Revoke'), ('retry', 'Retry')], max_length=20)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('session_hash', models.CharField(max_length=64)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_fingerprint_hash', models.CharField(max_length=64)),
                ('operation_id_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reconcile_required', 'Reconcile required')], default='pending', max_length=24)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('contract_version', models.CharField(default='a2-synthetic-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='integrations.marketplaceoauthattempt')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oauth_actions', to='integrations.marketplacestoreauthorization')),
                ('internal_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_actions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_oauth_action_status'), models.Index(fields=['operation_id_hash'], name='idx_oauth_action_operation')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'internal_user', 'action', 'idempotency_key_hash'), name='uniq_oauth_action_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOAuthOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('operation_id_hash', models.CharField(max_length=64, unique=True)),
                ('phase', models.CharField(default='created', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('compensation_required', 'Compensation required'), ('reconcile_required', 'Reconcile required')], default='pending', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('contract_version', models.CharField(default='a2-synthetic-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='integrations.marketplaceoauthattempt')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oauth_operations', to='integrations.marketplacestoreauthorization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_operations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_oauth_op_status'), models.Index(fields=['authorization', 'status'], name='idx_oauth_op_auth_status')],
            },
        ),
    ]
