# Generated by Django 5.2.16 on 2026-08-07 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_oauth_state_session'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceStoreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('platform_store_id', models.CharField(max_length=160)),
                ('platform_identity_key', models.CharField(max_length=64)),
                ('platform_subject_id', models.CharField(blank=True, max_length=160)),
                ('region', models.CharField(max_length=8)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('mapping_source', models.CharField(choices=[('oauth_callback', 'OAuth callback'), ('manual', 'Manual'), ('synthetic_fixture', 'Synthetic fixture')], max_length=30)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_mappings', to='integrations.marketplacestoreauthorization')),
                ('mapped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapped_store_mappings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_mappings', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_mappings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'platform', 'status'], name='idx_store_map_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform', 'platform_store_id'), name='uniq_store_mapping_tenant_platform_store')],
            },
        ),
    ]
