# Generated by Django 5.2.16 on 2026-08-04 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_alter_marketplacestoreauthorization_status_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketplaceoauthaction',
            name='uniq_oauth_action_scope_key',
        ),
        migrations.AddField(
            model_name='marketplaceoauthaction',
            name='execution_owner',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketplaceoauthaction',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceoauthaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reconcile_required', 'Reconcile required')], default='pending', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='marketplaceoauthaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_user', 'action', 'object_type', 'object_id', 'idempotency_key_hash'), name='uniq_oauth_action_scope_key'),
        ),
    ]
