# Generated by Django 5.2.16 on 2026-08-07 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_store_mapping'),
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('mock', 'Mock'), ('other', 'Other')], max_length=30)),
                ('platform_product_id', models.CharField(max_length=160)),
                ('platform_variant_id', models.CharField(max_length=160)),
                ('platform_sku', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('unmapped', 'Unmapped'), ('suggested', 'Suggested'), ('mapped', 'Mapped'), ('conflict', 'Conflict'), ('inactive', 'Inactive')], default='unmapped', max_length=20)),
                ('mapping_source', models.CharField(choices=[('synthetic_discovery', 'Synthetic discovery'), ('manual', 'Manual'), ('suggested', 'Suggested')], max_length=30)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manually_confirmed', models.BooleanField(default=False)),
                ('result_code', models.CharField(blank=True, max_length=80)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_mappings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_mappings', to='products.productspu')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_mappings', to='products.productsku')),
                ('store_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_mappings', to='integrations.marketplacestoremapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_mappings', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_product_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'platform', 'status'], name='idx_prod_map_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('store_mapping', 'platform_variant_id'), name='uniq_product_mapping_variant')],
            },
        ),
    ]

