# Generated by Django 5.2.16 on 2026-08-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def preflight_global_idempotency_key(apps, schema_editor):
    action = apps.get_model('integrations', 'MarketplaceOAuthAction')
    duplicate_exists = action.objects.values(
        'tenant_id',
        'internal_user_id',
        'action',
        'idempotency_key_hash',
    ).annotate(row_count=Count('id')).filter(row_count__gt=1).exists()
    if duplicate_exists:
        raise RuntimeError(
            'OAuth action idempotency-key duplicates must be reconciled before migration 0013.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_remove_marketplaceoauthaction_uniq_oauth_action_scope_key_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight_global_idempotency_key, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MarketplaceOAuthResourceLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=80)),
                ('execution_owner', models.CharField(blank=True, max_length=64)),
                ('fence_token', models.PositiveBigIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='marketplaceoauthaction',
            name='uniq_oauth_action_scope_key',
        ),
        migrations.AddField(
            model_name='marketplaceoauthaction',
            name='execution_fence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplaceoauthoperation',
            name='execution_fence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplaceoauthoperation',
            name='execution_owner',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketplaceoauthoperation',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='marketplaceoauthaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_user', 'action', 'idempotency_key_hash'), name='uniq_oauth_action_scope_key'),
        ),
        migrations.AddField(
            model_name='marketplaceoauthresourcelease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_oauth_resource_leases', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceoauthresourcelease',
            constraint=models.UniqueConstraint(fields=('tenant', 'object_type', 'object_id'), name='uniq_oauth_resource_lease'),
        ),
    ]
