# Generated by Django 5.2.16 on 2026-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_marketplaceoauthresourcelease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOAuthEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_key', models.CharField(choices=[('a2_00_app_identity', 'Approved application identity'), ('a2_00_endpoint_contract', 'Console endpoint contract'), ('a2_00_callback_url', 'Registered HTTPS callback URL'), ('a2_00_custody_contract', 'Credential custody contract'), ('a2_00_network_egress', 'Network egress plan'), ('a2_00_security_confirmation', 'Security confirmation trail')], max_length=40)),
                ('platform', models.CharField(max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('pilot', 'Pilot'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('readiness', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=20)),
                ('masked_value', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('confirmed_by', models.CharField(blank=True, max_length=120)),
                ('contract_version', models.CharField(blank=True, max_length=40)),
                ('is_current', models.BooleanField(default=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['evidence_key', 'platform', 'environment', '-id'],
            },
        ),
    ]
