# Generated by Django 5.2.17 on 2026-08-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_authorization_reauthorization_bindings'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformintegrationconfig',
            name='environment',
            field=models.CharField(choices=[('mock', 'Mock'), ('sandbox', 'Sandbox'), ('pilot', 'Pilot'), ('production', 'Production')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='callback_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='config_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='connect_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='contract_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='credential_status',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('configured', 'Configured'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('reconcile_required', 'Reconcile required')], default='unconfigured', max_length=30),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='network_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='platform_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='proxy_profile',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='read_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='sync_read_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='sync_write_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformintegrationconfig',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('verified', 'Verified'), ('error', 'Error'), ('active', 'Active'), ('disabled', 'Disabled'), ('pending_review', 'Pending review')], default='disabled', max_length=30),
        ),
        migrations.CreateModel(
            name='CredentialMutationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rotate', 'Rotate'), ('clear', 'Clear')], max_length=20)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('payload_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_mutation_requests', to='integrations.platformintegrationconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_mutation_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key_hash'), name='uniq_tenant_credential_mutation_key')],
            },
        ),
    ]

