# Generated by Django 5.2.17 on 2026-09-14 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_oauth_configuration_digest'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegrationconfig',
            name='active_uniqueness_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(deleted_at__isnull=True, then=models.Value(1)), default=models.Value(None)), output_field=models.PositiveSmallIntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='platformintegrationconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'account_alias', 'environment', 'active_uniqueness_marker'), name='uniq_active_platform_integration_per_tenant'),
        ),
        migrations.RemoveConstraint(
            model_name='platformintegrationconfig',
            name='uniq_platform_integration_per_tenant',
        ),
    ]
