# Generated by Django 5.2.17 on 2026-09-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_feishu_collaboration'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAPIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('caller_type', models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('internal_system', 'Internal system')], max_length=32)),
                ('client_id', models.CharField(max_length=80, unique=True)),
                ('secret_hash', models.CharField(max_length=256)),
                ('secret_prefix', models.CharField(max_length=16)),
                ('secret_fingerprint', models.CharField(max_length=64)),
                ('resources', models.JSONField(default=dict)),
                ('allowed_cidrs', models.JSONField(default=list)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('page_size_limit', models.PositiveIntegerField(default=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_rotation_operation_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_internal_api_clients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_api_clients', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_internal_api_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InternalAPIClientAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('config_version', models.PositiveIntegerField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_api_client_audits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='integrations.internalapiclient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_api_client_audits', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='internalapiclient',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_internal_api_client_name_tenant'),
        ),
    ]
