# Generated by Django 5.2.17 on 2026-09-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0034_authorization_api_type_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalapiclient',
            name='allow_sso_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalapiclient',
            name='sso_redirect_uris',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='InternalSSOAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.URLField(max_length=2048)),
                ('code_challenge', models.CharField(max_length=43)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_codes', to='integrations.internalapiclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
