# Generated by Django 5.2.17 on 2026-09-30 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_internal_sso_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('browser_digest', models.CharField(max_length=64)),
                ('configuration_digest', models.CharField(max_length=64)),
                ('identity_digest', models.CharField(blank=True, max_length=64)),
                ('handoff_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stage', models.CharField(default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.feishuconnection')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.feishuidentity')),
            ],
        ),
    ]
