# Generated by Django 5.2.17 on 2026-09-30 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_internal_sso_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReadonlyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('redirect_uri', models.URLField(max_length=2048)),
                ('state_hash', models.CharField(max_length=64)),
                ('code_challenge', models.CharField(max_length=43)),
                ('audience', models.CharField(max_length=64)),
                ('authorization_fingerprint', models.CharField(max_length=64)),
                ('code_expires_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.internalapiclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
