# Generated by Django 5.2.17 on 2026-09-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_internal_sso_login'),
        ('masterdata', '0014_country_exchange_rate'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAdsAdvertiserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_id', models.CharField(max_length=64)),
                ('token_id', models.CharField(max_length=160)),
                ('currency', models.CharField(max_length=8)),
                ('timezone', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_ads_advertisers', to='integrations.platformintegrationconfig')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TikTokAdsSyncLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_token', models.CharField(blank=True, default='', max_length=32)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_ads_sync_lease', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TikTokAdsDailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(max_length=8)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.tiktokadsadvertisermapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tiktokadsadvertisermapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'advertiser_id'), name='uniq_ads_tenant_advertiser'),
        ),
        migrations.AddConstraint(
            model_name='tiktokadsdailyspend',
            constraint=models.UniqueConstraint(fields=('mapping', 'date'), name='uniq_ads_mapping_day'),
        ),
    ]
