# Generated by Django 5.2.17 on 2026-10-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_merge_feishu_delivery_employee_readonly'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySyncSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('scope', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='integrations.historysyncbatch')),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_segments', to='integrations.syncjob')),
            ],
        ),
        migrations.AddField(
            model_name='syncrun',
            name='history_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='integrations.historysyncsegment'),
        ),
        migrations.AddConstraint(
            model_name='historysyncbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_history_batch_request'),
        ),
        migrations.AddIndex(
            model_name='historysyncsegment',
            index=models.Index(fields=['status', 'sync_job'], name='idx_history_segment_status'),
        ),
        migrations.AddConstraint(
            model_name='historysyncsegment',
            constraint=models.UniqueConstraint(fields=('batch', 'sync_job', 'sequence'), name='uniq_history_job_segment'),
        ),
    ]
