# Generated by Django 5.2.17 on 2026-10-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0041_automatic_refresh_recovery'),
        ('masterdata', '0014_country_exchange_rate'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='resource_type',
            field=models.CharField(choices=[('platform_product', 'Platform product'), ('sales_order', 'Sales order'), ('refund_return', 'Refund or return'), ('inventory_snapshot', 'Inventory snapshot'), ('inbound', 'Inbound'), ('shipment', 'Shipment'), ('settlement_bill', 'Settlement bill'), ('advertising_report', 'Shopee advertising data'), ('withdrawal', 'Withdrawal'), ('mock_record', 'Mock record')], max_length=40),
        ),
        migrations.CreateModel(
            name='ShopeeAdvertisingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shop_daily', 'Shop daily'), ('campaign_daily', 'Campaign daily'), ('campaign', 'Campaign settings'), ('balance', 'Balance snapshot')], max_length=24)),
                ('record_key', models.CharField(max_length=160)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(max_length=8)),
                ('report_timezone', models.CharField(max_length=64)),
                ('dimensions', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.syncrun')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'kind', 'report_date'], name='idx_shopee_ads_date')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'store', 'record_key'), name='uniq_shopee_ads_record')],
            },
        ),
    ]
