# Generated by Django 5.2.17 on 2026-08-10 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('batch_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_import_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=160)),
                ('record_type', models.CharField(max_length=60)),
                ('payload_hash', models.CharField(max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='influencers.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blacklisted', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_restrictions', to=settings.AUTH_USER_MODEL)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='influencers.influencer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_outreach_tasks', to=settings.AUTH_USER_MODEL)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_tasks', to='influencers.influencer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_outreach_tasks', to=settings.AUTH_USER_MODEL)),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='influencer_outreach_tasks', to='products.productspu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_outreach_tasks', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SampleFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_no', models.CharField(max_length=80)),
                ('request_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_fulfillments', to='influencers.influencer')),
                ('outreach_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_fulfillments', to='influencers.outreachtask')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_sample_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_sample_fulfillments', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_status_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='influencers.samplefulfillment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(blank=True, max_length=120)),
                ('site_code', models.CharField(max_length=16)),
                ('requested_sku', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(blank=True, max_length=240)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('price_match_status', models.CharField(default='not_imported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='influencers.samplefulfillment')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_items', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(max_length=120)),
                ('parent_sku', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(max_length=240)),
                ('site_code', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=40)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_listings', to='products.productspu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_product_listings', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SkuPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sku', models.CharField(max_length=120)),
                ('variant_id', models.CharField(blank=True, max_length=120)),
                ('variant_name', models.CharField(blank=True, max_length=160)),
                ('original_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('effective_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('inbound_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(max_length=8)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=40)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cost_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_price_snapshots', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_prices', to='influencers.storeproductlisting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'batch_key'), name='uniq_influencer_import_batch'),
        ),
        migrations.AddConstraint(
            model_name='externalsourcerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'record_type', 'external_id'), name='uniq_influencer_source_record'),
        ),
        migrations.AddConstraint(
            model_name='influencerrestriction',
            constraint=models.UniqueConstraint(fields=('tenant', 'influencer'), name='uniq_influencer_restriction'),
        ),
        migrations.AddIndex(
            model_name='outreachtask',
            index=models.Index(fields=['tenant', 'owner', 'status'], name='idx_outreach_owner_status'),
        ),
        migrations.AddConstraint(
            model_name='outreachtask',
            constraint=models.UniqueConstraint(fields=('tenant', 'task_no'), name='uniq_outreach_task_no'),
        ),
        migrations.AddConstraint(
            model_name='outreachtask',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('tenant', 'source', 'external_id'), name='uniq_outreach_external'),
        ),
        migrations.AddIndex(
            model_name='samplefulfillment',
            index=models.Index(fields=['tenant', 'owner', 'status'], name='idx_sample_owner_status'),
        ),
        migrations.AddConstraint(
            model_name='samplefulfillment',
            constraint=models.UniqueConstraint(fields=('tenant', 'fulfillment_no'), name='uniq_sample_fulfillment_no'),
        ),
        migrations.AddConstraint(
            model_name='samplefulfillment',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_key'), name='uniq_sample_request_key'),
        ),
        migrations.AddConstraint(
            model_name='samplefulfillment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('tenant', 'source', 'external_id'), name='uniq_sample_external'),
        ),
        migrations.AddConstraint(
            model_name='sampleitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'fulfillment', 'requested_sku'), name='uniq_sample_item_requested_sku'),
        ),
        migrations.AddIndex(
            model_name='storeproductlisting',
            index=models.Index(fields=['tenant', 'external_product_id'], name='idx_listing_product_id'),
        ),
        migrations.AddConstraint(
            model_name='storeproductlisting',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'site_code', 'external_product_id'), name='uniq_store_external_product'),
        ),
        migrations.AddIndex(
            model_name='skupricesnapshot',
            index=models.Index(fields=['tenant', 'external_sku'], name='idx_snapshot_external_sku'),
        ),
        migrations.AddConstraint(
            model_name='skupricesnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'listing', 'external_sku', 'variant_id'), name='uniq_listing_external_sku'),
        ),
    ]
