# Generated by Django 5.2.17 on 2026-08-11 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def create_targets_for_legacy_tasks(apps, schema_editor):
    OutreachTask = apps.get_model('influencers', 'OutreachTask')
    OutreachTarget = apps.get_model('influencers', 'OutreachTarget')
    alias = schema_editor.connection.alias
    for task in OutreachTask.objects.using(alias).exclude(influencer_id__isnull=True).iterator():
        OutreachTarget.objects.using(alias).get_or_create(
            tenant_id=task.tenant_id,
            task_id=task.pk,
            influencer_id=task.influencer_id,
            defaults={'first_linked_at': task.created_at},
        )


def reject_schema_downgrade(apps, schema_editor):
    raise IrreversibleError(
        'influencers.0004 is forward-only because multi-target tasks cannot be '
        'losslessly reduced to the legacy required influencer field. Roll back '
        'the application image while retaining this additive schema, then use a '
        'forward repair migration if needed.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_sampleitem_requested_sku_nullable'),
        ('tenants', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='outreachtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='dispatch_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='outreach_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='sku_prefix',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='target_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachtask',
            name='task_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='sample_order_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='sample_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outreachtask',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outreach_tasks', to='influencers.influencer'),
        ),
        migrations.AlterField(
            model_name='samplefulfillment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('creating', 'Creating'), ('published', 'Published'), ('live_creator', 'Live creator'), ('overdue', 'Overdue'), ('blank', 'Blank')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OutreachTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outreach_result', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected'), ('no_response', 'No response'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_targets', to='influencers.influencer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='influencers.outreachtask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'task_id', 'first_linked_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='samplefulfillment',
            name='outreach_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_fulfillments', to='influencers.outreachtarget'),
        ),
        migrations.AddIndex(
            model_name='outreachtarget',
            index=models.Index(fields=['tenant', 'task', 'is_deleted'], name='idx_target_task_active'),
        ),
        migrations.AddConstraint(
            model_name='outreachtarget',
            constraint=models.UniqueConstraint(fields=('tenant', 'task', 'influencer'), name='uniq_outreach_target_relation'),
        ),
        # Keep this guard last so reverse execution rejects before any MySQL DDL.
        migrations.RunPython(
            create_targets_for_legacy_tasks,
            reject_schema_downgrade,
        ),
    ]
