# Generated by Django 5.2.17 on 2026-08-19 01:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_affiliate_orders_and_bd_attribution'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('external_influencer_id', models.CharField(blank=True, max_length=160)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('tier', models.CharField(blank=True, max_length=40)),
                ('average_video_views', models.PositiveBigIntegerField(default=0)),
                ('average_live_views', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.CharField(blank=True, max_length=40)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('content_types', models.JSONField(blank=True, default=list)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('duplicate_reason', models.CharField(blank=True, max_length=240)),
                ('product_cooperation_count', models.PositiveIntegerField(default=0)),
                ('first_cooperation_at', models.DateTimeField(blank=True, null=True)),
                ('cooperation_count', models.PositiveIntegerField(default=0)),
                ('completed_cooperation_count', models.PositiveIntegerField(default=0)),
                ('fulfilled_cooperation_count', models.PositiveIntegerField(default=0)),
                ('fulfillment_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('content_completion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('historical_gmv', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('historical_orders', models.PositiveBigIntegerField(default=0)),
                ('historical_performance', models.JSONField(blank=True, default=dict)),
                ('profile_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='influencers.influencer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fulfillment_rate__isnull', True), models.Q(('fulfillment_rate__gte', 0), ('fulfillment_rate__lte', 1)), _connector='OR'), name='chk_inf_fulfill_rate'), models.CheckConstraint(condition=models.Q(('content_completion_rate__isnull', True), models.Q(('content_completion_rate__gte', 0), ('content_completion_rate__lte', 1)), _connector='OR'), name='chk_inf_content_rate')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=8)),
                ('quote_currency', models.CharField(max_length=8)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('effective_from', models.DateField()),
                ('source', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'base_currency', 'quote_currency', 'effective_from', 'is_active'], name='idx_fx_pair_effective')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'base_currency', 'quote_currency', 'effective_from', 'source'), name='uniq_fx_pair_start_src'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='chk_fx_rate_positive')],
            },
        ),
        migrations.CreateModel(
            name='InfluencerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=240)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_contacts_created', to=settings.AUTH_USER_MODEL)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='influencers.influencer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'influencer', 'is_active'], name='idx_inf_contact_active')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'influencer', 'channel', 'value'), name='uniq_inf_contact_value')],
            },
        ),
        migrations.CreateModel(
            name='InfluencerRestrictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('blacklist', 'Blacklist'), ('unblacklist', 'Unblacklist')], max_length=20)),
                ('reason', models.CharField(max_length=240)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_restrict_events', to=settings.AUTH_USER_MODEL)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restrict_events', to='influencers.influencer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_restrict_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'influencer_id', 'occurred_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'influencer', 'occurred_at'], name='idx_inf_restrict_time')],
            },
        ),
        migrations.CreateModel(
            name='VideoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('live', 'Live')], max_length=20)),
                ('platform', models.CharField(max_length=40)),
                ('external_content_id', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metric_date', models.DateField()),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('live_views', models.PositiveBigIntegerField(default=0)),
                ('orders', models.PositiveBigIntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(max_length=8)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_results', to='influencers.influencer')),
                ('outreach_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_results', to='influencers.outreachtask')),
                ('sample_fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_results', to='influencers.samplefulfillment')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='influencer_video_results', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'metric_date', 'id'],
                'indexes': [models.Index(fields=['tenant', 'influencer', 'metric_date'], name='idx_vres_creator_date'), models.Index(fields=['tenant', 'outreach_task', 'metric_date'], name='idx_vres_task_date')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform', 'external_content_id'), name='uniq_vres_platform_ext')],
            },
        ),
    ]
