# Generated by Django 5.2.17 on 2026-08-22 03:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_samplefulfillment_optional_outreach_task'),
        ('masterdata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BDVideoAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ineligible', 'Ineligible'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rule_version', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bd_video_attributions', to=settings.AUTH_USER_MODEL)),
                ('sample_fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bd_video_attributions', to='influencers.samplefulfillment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'video_id', 'rule_version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokShopVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_video_id', models.CharField(max_length=160)),
                ('creator_id', models.CharField(blank=True, default='', max_length=160)),
                ('creator_open_id', models.CharField(blank=True, default='', max_length=160)),
                ('creator_username', models.CharField(blank=True, default='', max_length=160)),
                ('creator_username_normalized', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('self_operated', 'Self operated'), ('creator', 'Creator')], default='creator', max_length=30)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_api', models.CharField(default='tiktok_shop', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_shop_videos', to='influencers.influencer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_shop_videos', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-last_seen_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BDVideoAttributionCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_pointers', to='influencers.bdvideoattribution')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_bd_attributions', to='influencers.tiktokshopvideo')),
            ],
            options={
                'ordering': ['tenant_id', 'video_id', 'rule_version'],
            },
        ),
        migrations.AddField(
            model_name='bdvideoattribution',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bd_video_attributions', to='influencers.tiktokshopvideo'),
        ),
        migrations.CreateModel(
            name='TikTokVideoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(max_length=160)),
                ('name', models.CharField(blank=True, default='', max_length=240)),
                ('source', models.CharField(default='api', max_length=40)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_products', to='influencers.tiktokshopvideo')),
            ],
            options={
                'ordering': ['tenant_id', 'video_id', 'external_product_id'],
            },
        ),
        migrations.AddField(
            model_name='bdvideoattribution',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bd_video_attributions', to='influencers.tiktokvideoproduct'),
        ),
        migrations.CreateModel(
            name='TikTokVideoSyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('api_version', models.CharField(max_length=20)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('detail_requested_count', models.PositiveIntegerField(default=0)),
                ('detail_succeeded_count', models.PositiveIntegerField(default=0)),
                ('detail_failed_count', models.PositiveIntegerField(default=0)),
                ('request_cursor', models.TextField(blank=True, default='')),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('latest_available_date', models.DateField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_video_sync_batches', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'window_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TikTokVideoDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('currency', models.CharField(max_length=8)),
                ('currency_basis', models.CharField(default='api_original', max_length=40)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('comments', models.PositiveBigIntegerField(default=0)),
                ('shares', models.PositiveBigIntegerField(default=0)),
                ('new_followers', models.PositiveBigIntegerField(default=0)),
                ('v_to_l_clicks', models.PositiveBigIntegerField(default=0)),
                ('product_impressions', models.PositiveBigIntegerField(default=0)),
                ('product_clicks', models.PositiveBigIntegerField(default=0)),
                ('unique_customers', models.PositiveBigIntegerField(default=0)),
                ('orders', models.PositiveBigIntegerField(default=0)),
                ('items_sold', models.PositiveBigIntegerField(default=0)),
                ('attributed_gmv', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('direct_gmv', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('indirect_gmv', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gpm', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ctr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('v_to_l_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('finish_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('click_to_order_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('quality_status', models.CharField(choices=[('passed', 'Passed'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('row_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_video_daily_metrics', to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_metrics', to='influencers.tiktokshopvideo')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_metrics', to='influencers.tiktokvideosyncbatch')),
            ],
            options={
                'ordering': ['tenant_id', 'metric_date', 'video_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tiktokshopvideo',
            index=models.Index(fields=['tenant', 'store', 'last_seen_at'], name='idx_tk_video_store_seen'),
        ),
        migrations.AddIndex(
            model_name='tiktokshopvideo',
            index=models.Index(fields=['tenant', 'creator_username_normalized'], name='idx_tk_video_creator'),
        ),
        migrations.AddConstraint(
            model_name='tiktokshopvideo',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'external_video_id'), name='uniq_tk_video_external_id'),
        ),
        migrations.AddIndex(
            model_name='bdvideoattributioncurrent',
            index=models.Index(fields=['tenant', 'rule_version'], name='idx_tk_bd_current_rule'),
        ),
        migrations.AddConstraint(
            model_name='bdvideoattributioncurrent',
            constraint=models.UniqueConstraint(fields=('tenant', 'video', 'rule_version'), name='uniq_tk_bd_current_pointer'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideoproduct',
            index=models.Index(fields=['tenant', 'video', 'parse_status'], name='idx_tk_vprod_parse'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideoproduct',
            index=models.Index(fields=['tenant', 'external_product_id'], name='idx_tk_vprod_ext_id'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideoproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'video', 'external_product_id'), name='uniq_tk_vprod_external'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideoproduct',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='chk_tk_vprod_confidence'),
        ),
        migrations.AddIndex(
            model_name='bdvideoattribution',
            index=models.Index(fields=['tenant', 'video', 'status'], name='idx_tk_bd_video_state'),
        ),
        migrations.AddIndex(
            model_name='bdvideoattribution',
            index=models.Index(fields=['tenant', 'owner', 'eligible_at'], name='idx_tk_bd_owner_date'),
        ),
        migrations.AddIndex(
            model_name='bdvideoattribution',
            index=models.Index(fields=['tenant', 'rule_version', 'created_at'], name='idx_tk_bd_rule_created'),
        ),
        migrations.AddConstraint(
            model_name='bdvideoattribution',
            constraint=models.UniqueConstraint(fields=('tenant', 'video', 'rule_version', 'input_fingerprint'), name='uniq_tk_bd_attr_evidence'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideosyncbatch',
            index=models.Index(fields=['tenant', 'store', 'status', 'window_start'], name='idx_tk_batch_store_state'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideosyncbatch',
            index=models.Index(fields=['tenant', 'store', 'window_start', 'window_end'], name='idx_tk_batch_store_window'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideosyncbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'idempotency_key'), name='uniq_tk_batch_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideosyncbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'window_start', 'window_end', 'api_version'), name='uniq_tk_batch_window_job'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideosyncbatch',
            constraint=models.CheckConstraint(condition=models.Q(('window_start__lt', models.F('window_end'))), name='chk_tk_batch_window'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideosyncbatch',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts')), ('max_attempts__gte', 1)), name='chk_tk_batch_attempts'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideosyncbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'running'), _negated=True), models.Q(('heartbeat_at__isnull', False), ('lease_expires_at__gt', models.F('heartbeat_at')), ('lease_expires_at__isnull', False), ('lease_token__gt', '')), _connector='OR'), name='chk_tk_batch_running_lease'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideodailymetric',
            index=models.Index(fields=['tenant', 'store', 'metric_date'], name='idx_tk_vmetric_store'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideodailymetric',
            index=models.Index(fields=['tenant', 'batch'], name='idx_tk_vmetric_batch'),
        ),
        migrations.AddIndex(
            model_name='tiktokvideodailymetric',
            index=models.Index(fields=['tenant', 'quality_status', 'metric_date'], name='idx_tk_vmetric_quality'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideodailymetric',
            constraint=models.UniqueConstraint(fields=('tenant', 'video', 'metric_date'), name='uniq_tk_vmetric_day'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideodailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('attributed_gmv__gte', 0), ('direct_gmv__gte', 0), ('indirect_gmv__gte', 0), ('gpm__gte', 0)), name='chk_tk_vmetric_amounts'),
        ),
        migrations.AddConstraint(
            model_name='tiktokvideodailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('ctr__gte', 0), ('ctr__lte', 1), ('v_to_l_rate__gte', 0), ('v_to_l_rate__lte', 1), ('finish_rate__gte', 0), ('finish_rate__lte', 1), ('click_to_order_rate__gte', 0), ('click_to_order_rate__lte', 1)), name='chk_tk_vmetric_rates'),
        ),
    ]
