# Generated by Django 5.2.17 on 2026-09-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0025_simplify_bd_config_and_add_overdue_notifications'),
        ('masterdata', '0014_country_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_items', to='masterdata.warehousemaster'),
        ),
    ]
