# Generated by Django 5.2.16 on 2026-07-16 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('platform_type', models.CharField(choices=[('bigseller', 'BigSeller'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_masters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=8)),
                ('currency', models.CharField(max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='masterdata.platformmaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_masters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('contact_alias', models.CharField(blank=True, max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_masters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=8)),
                ('warehouse_type', models.CharField(choices=[('owned', 'Owned'), ('third_party', 'Third party'), ('platform', 'Platform')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_masters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformmaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_platform_master_code'),
        ),
        migrations.AddConstraint(
            model_name='storemaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_store_master_code'),
        ),
        migrations.AddConstraint(
            model_name='suppliermaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_supplier_master_code'),
        ),
        migrations.AddConstraint(
            model_name='warehousemaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_warehouse_master_code'),
        ),
    ]
