# Generated by Django 5.2.16 on 2026-07-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.BigIntegerField()),
                ('shipment_no', models.CharField(max_length=80)),
                ('sku_code', models.CharField(max_length=80)),
                ('ship_quantity', models.PositiveIntegerField(default=0)),
                ('carton_count', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shipping_mark', models.CharField(blank=True, max_length=120)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('attachment_placeholder', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_shipments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'shipment_no'), name='uniq_supplier_shipment_no_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='SupplierTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.BigIntegerField()),
                ('task_no', models.CharField(max_length=80)),
                ('sku_code', models.CharField(max_length=80)),
                ('production_quantity', models.PositiveIntegerField(default=0)),
                ('completed_quantity', models.PositiveIntegerField(default=0)),
                ('expected_ship_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('partial', 'Partial'), ('completed', 'Completed'), ('exception', 'Exception'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('is_overdue', models.BooleanField(default=False)),
                ('feedback_note', models.TextField(blank=True)),
                ('exception_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tasks', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'expected_ship_date', 'task_no'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'task_no'), name='uniq_supplier_task_no_per_tenant')],
            },
        ),
    ]
