# Generated by Django 5.2.16 on 2026-07-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.BigIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('on_time_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('exception_tasks', models.PositiveIntegerField(default=0)),
                ('total_shipments', models.PositiveIntegerField(default=0)),
                ('accurate_shipments', models.PositiveIntegerField(default=0)),
                ('feedback_on_time_count', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overdue_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exception_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipment_accuracy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback_timeliness_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_performance_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'supplier_id', '-period_end'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('tenant', 'supplier_id', 'period_start', 'period_end'),
                        name='uniq_supplier_performance_period',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('period_start__lte', models.F('period_end'))),
                        name='supplier_performance_valid_period',
                    ),
                ],
            },
        ),
    ]
