# Generated by Django 5.2.16 on 2026-07-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productstatustransition_uniq_product_status_transition_recommendation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock', models.DecimalField(decimal_places=4, max_digits=16)),
                ('in_transit_stock', models.DecimalField(decimal_places=4, max_digits=16)),
                ('average_daily_sales', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('safety_stock_days', models.PositiveIntegerField()),
                ('supplier_lead_days', models.PositiveIntegerField()),
                ('replenishment_cycle_days', models.PositiveIntegerField()),
                ('suggested_quantity', models.PositiveIntegerField(default=0)),
                ('suggested_date', models.DateField()),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('reason_code', models.CharField(max_length=80)),
                ('reason_detail', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('source_summary', models.JSONField(default=dict)),
                ('formula_version', models.CharField(default='replenishment-v1', max_length=40)),
                ('dedup_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_replenishment_recommendations', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_recommendations', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_recommendations', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_recommendations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='idx_replenishment_status'), models.Index(fields=['tenant', 'sku', 'suggested_date'], name='idx_replenishment_sku')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dedup_key'), name='uniq_replenishment_dedup'), models.CheckConstraint(condition=models.Q(('spu__isnull', False), ('sku__isnull', False), _connector='OR'), name='replenishment_has_product')],
            },
        ),
    ]
