# Generated by Django 5.2.16 on 2026-07-09 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_code', models.CharField(max_length=80)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('lifecycle_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('discontinued', 'Discontinued')], default='draft', max_length=30)),
                ('sales_status', models.CharField(choices=[('not_listed', 'Not listed'), ('on_sale', 'On sale'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='not_listed', max_length=30)),
                ('is_code_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spus', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'spu_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=80)),
                ('size', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('selling_points', models.JSONField(blank=True, default=list)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('package_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_code_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='tenants.tenant')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.productspu')),
            ],
            options={
                'ordering': ['tenant_id', 'sku_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_no', models.CharField(max_length=80)),
                ('product_name', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('competitor_url', models.URLField(blank=True)),
                ('estimated_sales', models.PositiveIntegerField(default=0)),
                ('estimated_gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('risk_points', models.JSONField(blank=True, default=list)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_research_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_research_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'research_no'), name='uniq_research_no_per_tenant')],
            },
        ),
        migrations.AddConstraint(
            model_name='productspu',
            constraint=models.UniqueConstraint(fields=('tenant', 'spu_code'), name='uniq_spu_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku_code'), name='uniq_sku_code_per_tenant'),
        ),
    ]
