# Generated by Django 5.2.16 on 2026-07-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API'), ('rpa_readback', 'RPA readback'), ('manual', 'Manual'), ('system_rule', 'System rule')], max_length=30)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('metrics_payload', models.JSONField(blank=True, default=dict)),
                ('calculated_status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('slow_moving', 'Slow moving'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_snapshots', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_snapshots', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-calculated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatusRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('slow_moving', 'Slow moving'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('reason_code', models.CharField(max_length=80)),
                ('reason_detail', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_product_status_recommendations', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_recommendations', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_recommendations', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status_recommendations', to='tenants.tenant')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='products.productstatussnapshot')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('slow_moving', 'Slow moving'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('slow_moving', 'Slow moving'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('trigger_type', models.CharField(choices=[('manual_confirm', 'Manual confirm'), ('manual_reject', 'Manual reject'), ('system_rule', 'System rule')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_product_status_transitions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='products.productstatusrecommendation')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status_transitions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='productstatussnapshot',
            index=models.Index(fields=['tenant', 'source'], name='idx_product_snapshot_source'),
        ),
        migrations.AddIndex(
            model_name='productstatussnapshot',
            index=models.Index(fields=['tenant', 'calculated_status'], name='idx_product_snapshot_status'),
        ),
        migrations.AddIndex(
            model_name='productstatusrecommendation',
            index=models.Index(fields=['tenant', 'status'], name='idx_product_reco_status'),
        ),
        migrations.AddIndex(
            model_name='productstatusrecommendation',
            index=models.Index(fields=['tenant', 'recommended_status'], name='idx_product_reco_target'),
        ),
        migrations.AddIndex(
            model_name='productstatustransition',
            index=models.Index(fields=['tenant', 'from_status', 'to_status'], name='idx_product_transition_status'),
        ),
    ]
