# Generated by Django 5.2.16 on 2026-07-10 11:28

from django.conf import settings
from django.db import migrations, models


def assert_no_duplicate_recommendation_transitions(apps, schema_editor):
    transition_model = apps.get_model("products", "ProductStatusTransition")
    duplicates = (
        transition_model.objects.exclude(recommendation_id=None)
        .values("recommendation_id")
        .annotate(transition_count=models.Count("id"))
        .filter(transition_count__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            "Duplicate product status transitions exist. Reconcile them before applying the unique constraint."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productstatussnapshot_productstatusrecommendation_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assert_no_duplicate_recommendation_transitions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productstatustransition',
            constraint=models.UniqueConstraint(fields=('recommendation',), name='uniq_product_status_transition_recommendation'),
        ),
    ]
