# Generated by Django 5.2.16 on 2026-07-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productstatustransition_uniq_product_status_transition_recommendation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLifecycleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('new_observation', 'New observation'), ('growth', 'Growth'), ('stable', 'Stable'), ('slow_moving_observation', 'Slow moving observation'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('recommended_stage', models.CharField(choices=[('new_observation', 'New observation'), ('growth', 'Growth'), ('stable', 'Stable'), ('slow_moving_observation', 'Slow moving observation'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('reason_code', models.CharField(max_length=80)),
                ('reason_detail', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('source_metrics', models.JSONField(default=dict)),
                ('source_type', models.CharField(choices=[('mock', 'Mock'), ('api', 'API'), ('rpa_readback', 'RPA readback'), ('manual', 'Manual')], default='mock', max_length=30)),
                ('rule_version', models.CharField(default='lifecycle-v1', max_length=40)),
                ('dedup_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_product_lifecycle_reviews', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_reviews', to='products.productsku')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_reviews', to='products.productspu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lifecycle_reviews', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', '-review_period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductLifecycleDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirm', 'Confirm'), ('reject', 'Reject')], max_length=20)),
                ('from_stage', models.CharField(choices=[('new_observation', 'New observation'), ('growth', 'Growth'), ('stable', 'Stable'), ('slow_moving_observation', 'Slow moving observation'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('to_stage', models.CharField(choices=[('new_observation', 'New observation'), ('growth', 'Growth'), ('stable', 'Stable'), ('slow_moving_observation', 'Slow moving observation'), ('clearance_candidate', 'Clearance candidate'), ('clearance', 'Clearance'), ('stopped', 'Stopped'), ('archived', 'Archived')], max_length=40)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_lifecycle_decisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lifecycle_decisions', to='tenants.tenant')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision_record', to='products.productlifecyclereview')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='productlifecyclereview',
            index=models.Index(fields=['tenant', 'status', 'review_period_end'], name='idx_lifecycle_review_status'),
        ),
        migrations.AddIndex(
            model_name='productlifecyclereview',
            index=models.Index(fields=['tenant', 'sku', 'recommended_stage'], name='idx_lifecycle_review_sku'),
        ),
        migrations.AddConstraint(
            model_name='productlifecyclereview',
            constraint=models.UniqueConstraint(fields=('tenant', 'dedup_key'), name='uniq_lifecycle_review_dedup'),
        ),
        migrations.AddConstraint(
            model_name='productlifecyclereview',
            constraint=models.CheckConstraint(condition=models.Q(('spu__isnull', False), ('sku__isnull', False), _connector='OR'), name='lifecycle_review_has_product'),
        ),
        migrations.AddConstraint(
            model_name='productlifecyclereview',
            constraint=models.CheckConstraint(condition=models.Q(('review_period_start__lte', models.F('review_period_end'))), name='lifecycle_review_valid_period'),
        ),
        migrations.AddIndex(
            model_name='productlifecycledecision',
            index=models.Index(fields=['tenant', 'to_stage', 'created_at'], name='idx_lifecycle_decision_stage'),
        ),
    ]
