# Generated by Django 5.2.16 on 2026-08-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_product_sales_summary_view'),
        ('products', '0012_product_volume_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspu',
            name='development_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_spus', to='development.developmentproject'),
        ),
        migrations.AddField(
            model_name='productspu',
            name='development_source',
            field=models.CharField(blank=True, choices=[('operation', 'Operation submission'), ('internal', 'Internal development'), ('supplier', 'Supplier recommendation')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productspu',
            name='erp_product_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='productspu',
            name='first_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productspu',
            name='platform_listing_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
