# Generated by Django 5.2.16 on 2026-08-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlifecyclereview_productlifecycledecision_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='color_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productsku',
            name='spec_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productsku',
            name='specification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productspu',
            name='l1_code',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='productspu',
            name='l2_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='productspu',
            name='l3_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='productspu',
            name='product_type',
            field=models.CharField(choices=[('standard', 'Standard product'), ('bundle', 'Bundle product')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='productspu',
            name='season_code',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3')])),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('english_name', models.CharField(blank=True, max_length=160)),
                ('platform_category_id', models.CharField(blank=True, max_length=80)),
                ('spec_dimensions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'level', 'code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productspu',
            name='category_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_code', models.CharField(max_length=1)),
                ('l2_code', models.CharField(max_length=2)),
                ('l3_code', models.CharField(max_length=2)),
                ('season_code', models.CharField(max_length=1)),
                ('current_value', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_code_sequences', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='products.productsku')),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_components', to='tenants.tenant')),
            ],
            options={
                'ordering': ['bundle_sku_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('bundle_sku', 'component_sku'), name='uniq_component_per_bundle_sku'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='bundle_component_quantity_positive'), models.CheckConstraint(condition=models.Q(('bundle_sku', models.F('component_sku')), _negated=True), name='bundle_component_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'code'), name='uniq_product_category_sibling_code'),
        ),
        migrations.AddConstraint(
            model_name='productcodesequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'l1_code', 'l2_code', 'l3_code', 'season_code'), name='uniq_product_code_sequence_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productcodesequence',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0), ('current_value__lte', 999)), name='product_code_sequence_range'),
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_product_color_per_tenant'),
        ),
    ]
