# Generated by Django 5.2.17 on 2026-09-20 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productsku_product_name_source'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundleMigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('confirmed', 'Confirmed'), ('expired', 'Expired')], default='previewed', max_length=20)),
                ('normalized_rows', models.JSONField(default=list)),
                ('preview_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_migrations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_migration_batches', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('effective_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_versions', to='products.productsku')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_bundle_versions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_versions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['bundle_sku_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundleChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='components_updated', max_length=40)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('before_payload', models.JSONField(default=list)),
                ('after_payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_audits', to=settings.AUTH_USER_MODEL)),
                ('bundle_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_change_audits', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_change_audits', to='tenants.tenant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='products.productbundleversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundleVersionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_sku_code', models.CharField(max_length=80)),
                ('component_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_version_components', to='products.productsku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.productbundleversion')),
            ],
            options={
                'ordering': ['version_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productbundleversion',
            constraint=models.UniqueConstraint(fields=('bundle_sku', 'version'), name='uniq_bundle_sku_version'),
        ),
        migrations.AddConstraint(
            model_name='productbundleversioncomponent',
            constraint=models.UniqueConstraint(fields=('version', 'component_sku'), name='uniq_bundle_version_component'),
        ),
        migrations.AddConstraint(
            model_name='productbundleversioncomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='bundle_version_component_qty_positive'),
        ),
    ]
