# Generated by Django 5.2.17 on 2026-09-21 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productbundlemigrationbatch_productbundleversion_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed')], default='pending', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System generated'), ('import', 'Import')], default='manual', max_length=16)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('purchase_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('freight_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('duty_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('packaging_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('other_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('system_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('confirmed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_cost_versions', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_versions', to='products.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost_versions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'sku_id', '-effective_from', '-version_no'],
                'indexes': [models.Index(fields=['tenant', 'sku', 'status', 'effective_from'], name='idx_cost_tenant_sku_asof')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku', 'version_no'), name='uniq_cost_version_per_sku'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='product_cost_valid_interval'), models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0), ('freight_cost__gte', 0), ('duty_cost__gte', 0), ('packaging_cost__gte', 0), ('other_cost__gte', 0), models.Q(('system_cost__isnull', True), ('system_cost__gte', 0), _connector='OR'), models.Q(('confirmed_cost__isnull', True), ('confirmed_cost__gte', 0), _connector='OR')), name='product_cost_amounts_nonnegative')],
            },
        ),
    ]
