# Generated by Django 5.2.17 on 2026-10-01 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_country_exchange_rate'),
        ('products', '0026_product_cost_warehouse'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKUAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(max_length=160)),
                ('code_key', models.CharField(editable=False, max_length=64)),
                ('scope_type', models.CharField(choices=[('tenant', '内部旧码'), ('store', '店铺来源码'), ('warehouse', '仓库来源码')], default='tenant', max_length=10)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('reason', models.CharField(max_length=400)),
                ('version_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_aliases', to='products.productsku')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.storemaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.warehousemaster')),
            ],
            options={
                'ordering': ['-version_no', '-id'],
                'indexes': [models.Index(fields=['tenant', 'code_key', 'scope_type', 'effective_from'], name='idx_sku_alias_lookup')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku', 'version_no'), name='uniq_sku_alias_version'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='sku_alias_positive_interval'), models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'tenant'), ('store__isnull', True), ('warehouse__isnull', True)), models.Q(('scope_type', 'store'), ('store__isnull', False), ('warehouse__isnull', True)), models.Q(('scope_type', 'warehouse'), ('store__isnull', True), ('warehouse__isnull', False)), _connector='OR'), name='sku_alias_valid_scope')],
            },
        ),
    ]
