<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { createInternalReadonlyClient, fetchInternalReadonlyAudit, fetchInternalReadonlyCapabilities, fetchInternalReadonlyClients, reviewInternalReadonlyClient, rotateInternalReadonlyCredential, setInternalReadonlyClientStatus, updateInternalReadonlyClient } from '../../api/internalReadonly';
import { internalReadonlyModules, internalReadonlyResources } from '../../config/internalReadonlyResources';
import { internalReadonlyFieldErrors, validateSourceCidrs } from '../../utils/internalReadonlyValidation';
import { safeSsoCallback } from '../../utils/ssoRedirect';
import { buildInternalApiHandoff } from '../../utils/internalApiHandoff';

const activeSection=ref('clients'), clients=ref([]), auditRows=ref([]), loading=ref(false), saving=ref(false);
const editorVisible=ref(false), auditVisible=ref(false), secretVisible=ref(false), editingId=ref(null), oneTimeCredential=ref(null), formRef=ref();
const capabilities=ref(null), reviewVisible=ref(false), reviewTarget=ref(null), reviewDecision=ref('approve'), reviewReason=ref('');
const handoffVisible=ref(false), handoffTarget=ref(null);
const safeMethods = ['GET', 'HEAD', 'OPTIONS'];
const blockedMethods = ['POST', 'PUT', 'PATCH', 'DELETE'];
const resources=internalReadonlyResources;
const modules=internalReadonlyModules;
const resourceModules=(item)=>Array.isArray(item.module)?item.module:[item.module];
const blank=()=>({name:'',caller_type:'internal_system',modules:[],resources:[],allow_sso_login:false,sso_redirect_uris:[''],cidrs:[''],rate_limit:120,page_size:100,expires_at:''});
const form=reactive(blank());
const serverErrors=reactive({});
const rules={name:[{required:true,message:'请输入系统名称'}],caller_type:[{required:true,message:'请选择调用方类型'}],modules:[{validator:(_,v,done)=>done(v.length||form.allow_sso_login?undefined:new Error('请选择数据模块或启用共用登录'))}],resources:[{validator:(_,v,done)=>done(v.length||form.allow_sso_login?undefined:new Error('请选择数据块或启用共用登录'))}],sso_redirect_uris:[{validator:(_,v,done)=>{if(!form.allow_sso_login)return done();const uris=v.map(x=>x.trim());if(!uris.length||uris.some(x=>!x))return done(new Error('请填写回调地址'));if(new Set(uris).size!==uris.length)return done(new Error('回调地址不能重复'));if(uris.some(x=>!safeSsoCallback(x)))return done(new Error('回调地址须为无参数、含路径的 HTTPS 完整地址'));done()}}],cidrs:[{validator:(_,v,done)=>{const message=validateSourceCidrs(v);done(message?new Error(message):undefined)}}],rate_limit:[{type:'number',min:1,max:10000,message:'限流须为 1–10000'}],page_size:[{type:'number',min:1,max:1000,message:'分页上限须为 1–1000'}],expires_at:[{required:true,message:'请选择有效期'}]};
const availableResources=computed(()=>resources.filter(item=>resourceModules(item).some(code=>form.modules.includes(code))));
const boundarySummary=computed(()=>`${safeMethods.join(' / ')} 只读，${blockedMethods.join(' / ')} 全部拒绝`);
const capabilityRows=[{capability:'已接入数据块查询',status:'允许',detail:'仅限服务端已上线且授权的数据块；按租户、来源地址和分页限制'},{capability:'未接入数据块查询',status:'待接入',detail:'目录可配置不代表业务只读端点已上线'},{capability:'业务内容写入',status:'禁止',detail:'不开放新增、修改、删除、审批、发布或任务触发'},{capability:'AI 生成内容回写',status:'禁止',detail:'摘要、标签、分类和提示词都不回写'}];
const safeFoundationCodes=['products','product_details','product_categories','platforms','country_sites','suppliers','stores','warehouses'];
const readyCodes=computed(()=>new Set((capabilities.value?.ready_resources||[]).map(item=>typeof item==='string'?item:item.code)));
const handoffInfo=computed(()=>handoffTarget.value?buildInternalApiHandoff(handoffTarget.value,[...readyCodes.value],window.location.origin):null);
const handoffText=computed(()=>handoffInfo.value?JSON.stringify(handoffInfo.value,null,2):'');
const readyResourceNames=computed(()=>resources.filter(item=>readyCodes.value.has(item.code)).map(item=>item.label).join('、'));
const pendingResourceNames=computed(()=>resources.filter(item=>!readyCodes.value.has(item.code)).map(item=>item.label).join('、'));
const readinessKnown=computed(()=>capabilities.value!==null);
const approvalLabel=(row)=>({pending:'待审核',approved:'已批准',rejected:'已驳回'})[row.approval_status]||'待核实';
const approvalTagType=(row)=>({pending:'warning',approved:'success',rejected:'danger'})[row.approval_status]||'info';
const contractFields=[['resource','数据块代码'],['items','当前页数据；字段以实时能力目录为准'],['next_cursor','下一页游标；为空表示已结束'],['has_more','是否还有下一页']];
async function load(){loading.value=true;const [r,c]=await Promise.all([fetchInternalReadonlyClients(),fetchInternalReadonlyCapabilities()]);loading.value=false;if(r.success)clients.value=r.data.items||[];else ElMessage.error(r.message);capabilities.value=c.success&&Array.isArray(c.data?.ready_resources)?c.data:null}
function resourceNames(value){return Object.keys(value||{}).join('、')}
function callerTypeName(value){return value==='knowledge_base'?'知识库（历史配置）':'内部业务系统'}
function edit(row){Object.keys(serverErrors).forEach(key=>delete serverErrors[key]);editingId.value=row?.id||null;const configured=row?.resources||{};const resourceCodes=Array.isArray(configured)?configured:Object.keys(configured);Object.assign(form,blank(),{...row,caller_type:'internal_system',modules:[...new Set(resources.filter(item=>resourceCodes.includes(item.code)).flatMap(resourceModules))],resources:resourceCodes,allow_sso_login:row?.allow_sso_login===true,sso_redirect_uris:row?.sso_redirect_uris?.length?[...row.sso_redirect_uris]:[''],cidrs:[...(row?.allowed_cidrs||[''])],rate_limit:row?.rate_limit_per_minute??120,page_size:row?.page_size_limit??100,expires_at:row?.expires_at?.slice?.(0,10)||''});editorVisible.value=true}
watch(()=>form.modules.slice(),()=>{const allowed=new Set(availableResources.value.map(item=>item.code));form.resources=form.resources.filter(code=>allowed.has(code))});
watch(()=>form.cidrs.slice(),()=>{delete serverErrors.allowed_cidrs});
watch(()=>form.resources.slice(),()=>{delete serverErrors.resources});
function payload(){return{name:form.name,caller_type:form.caller_type,resources:[...form.resources],allow_sso_login:form.allow_sso_login,sso_redirect_uris:form.allow_sso_login?form.sso_redirect_uris.map(x=>x.trim()):[],allowed_cidrs:form.cidrs,rate_limit_per_minute:form.rate_limit,page_size_limit:form.page_size,expires_at:`${form.expires_at}T23:59:59+08:00`}}
async function save(){Object.keys(serverErrors).forEach(key=>delete serverErrors[key]);if(!(await formRef.value.validate().catch(()=>false)))return;let data;try{data=payload()}catch(error){return ElMessage.error(error.message)}await ElMessageBox.confirm(`确认${editingId.value?'更新':'创建'}此只读调用系统？保存后将停用并进入待审核，须由另一位管理员审核通过后再启用。`,'二次确认',{type:'warning'});saving.value=true;const r=editingId.value?await updateInternalReadonlyClient(editingId.value,data):await createInternalReadonlyClient(data);saving.value=false;if(!r.success){Object.assign(serverErrors,internalReadonlyFieldErrors(r));return ElMessage.error(Object.values(serverErrors)[0]||r.message)}editorVisible.value=false;await load();const credential=r.data?.credential||r.data;if(credential?.client_secret){oneTimeCredential.value={client_id:credential.client_id,client_secret:credential.client_secret};secretVisible.value=true}else ElMessage.success('已提交审核；另一位管理员审核通过后方可启用')}
async function status(row){const next=row.status==='active'?'disabled':'active';if(next==='active'&&row.approval_status!=='approved')return ElMessage.warning('请先由另一位管理员审核通过');await ElMessageBox.confirm(`确认${next==='active'?'启用':'停用'}“${row.name}”？`,'二次确认',{type:'warning'});const r=await setInternalReadonlyClientStatus(row.id,next);if(r.success){ElMessage.success('状态已更新');await load()}else ElMessage.error(r.message)}
function openReview(row,decision){reviewTarget.value=row;reviewDecision.value=decision;reviewReason.value='';reviewVisible.value=true}
async function submitReview(){if(reviewDecision.value==='reject'&&!reviewReason.value.trim())return ElMessage.warning('驳回时请填写原因');saving.value=true;const r=await reviewInternalReadonlyClient(reviewTarget.value.id,reviewDecision.value,reviewReason.value.trim());saving.value=false;if(!r.success)return ElMessage.error(r.message);reviewVisible.value=false;ElMessage.success(reviewDecision.value==='approve'?'审核通过，请另行启用':'已驳回');await load()}
async function rotate(row){await ElMessageBox.confirm(`轮换“${row.name}”密钥后旧密钥立即失效，是否继续？`,'二次确认',{type:'warning'});saving.value=true;const key=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;const r=await rotateInternalReadonlyCredential(row.id,key);saving.value=false;if(r.success){oneTimeCredential.value={client_id:r.data.client_id,client_secret:r.data.client_secret};secretVisible.value=true}else ElMessage.error(r.message)}
async function audit(row){auditVisible.value=true;const r=await fetchInternalReadonlyAudit(row.id);auditRows.value=r.success?(r.data.items||[]).map(item=>({...item,client_name:row.name,method:'配置',source_ip:'--',result:'成功'})):[]}
function openHandoff(row){handoffTarget.value=row;handoffVisible.value=true}
async function copyHandoff(){try{await navigator.clipboard.writeText(handoffText.value);ElMessage.success('已复制接入参数（不含密钥）')}catch{ElMessage.warning('复制失败，请手动选中下方内容复制')}}
async function copySecret(){if(!oneTimeCredential.value?.client_secret)return;try{await navigator.clipboard.writeText(oneTimeCredential.value.client_secret);ElMessage.success('密钥已复制，请粘贴到调用方服务端的安全凭据库')}catch{ElMessage.error('复制失败，请在关闭窗口前手动复制密钥')}}
onMounted(load);
</script>
<template><main class="api-page">
 <header class="page-header"><div><p class="path">系统管理 · API 数据接入</p><h1>内部系统数据接口</h1><p>管理员可配置调用系统、最小读取范围和独立凭据；本系统不接收调用方回写，调用方始终不能回写业务数据。</p></div><el-tag type="success" size="large" effect="plain">强制只读</el-tag></header>
 <el-alert v-if="readinessKnown" :title="`业务只读 API 已接入 ${readyCodes.size} 个数据块；其他数据块仍可配置但尚不可读取。`" type="warning" :closable="false" show-icon/>
 <el-alert v-else title="无法核实业务只读 API 的实时状态；创建凭据和勾选数据块不代表已经可读取。首批计划范围为基础档案数据块。" type="warning" :closable="false" show-icon/>
 <el-tabs v-model="activeSection" class="content-tabs">
  <el-tab-pane label="调用系统配置" name="clients"><section class="panel"><header><div><h2>调用系统</h2><p>数据读取与共用登录分别授权；保存后由另一位管理员审核，审核通过仍须单独启用。通过“接入资料”向调用方交付参数。</p></div><el-button type="primary" @click="edit()">新增调用系统</el-button></header><el-table v-loading="loading" :data="clients" stripe><el-table-column prop="name" label="系统名称" min-width="160"/><el-table-column label="调用方类型" width="130"><template #default="s">{{ callerTypeName(s.row.caller_type) }}</template></el-table-column><el-table-column label="资源" min-width="170"><template #default="s">{{ resourceNames(s.row.resources) || '未授权数据读取' }}</template></el-table-column><el-table-column label="共用登录" width="100"><template #default="s"><el-tag :type="s.row.allow_sso_login?'success':'info'">{{s.row.allow_sso_login?'已配置':'未配置'}}</el-tag></template></el-table-column><el-table-column label="审核" width="110"><template #default="s"><el-tooltip :content="s.row.rejection_reason||'审核状态'"><el-tag :type="approvalTagType(s.row)">{{approvalLabel(s.row)}}</el-tag></el-tooltip></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='active'?'success':'info'">{{s.row.status==='active'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="expires_at" label="有效期" width="180"/><el-table-column label="操作" width="450" fixed="right"><template #default="s"><el-button link type="primary" @click="openHandoff(s.row)">接入资料</el-button><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button v-if="s.row.approval_status==='pending'" link type="success" @click="openReview(s.row,'approve')">审核通过</el-button><el-button v-if="s.row.approval_status==='pending'" link type="danger" @click="openReview(s.row,'reject')">驳回</el-button><el-button link :disabled="s.row.status!=='active'&&s.row.approval_status!=='approved'" @click="status(s.row)">{{s.row.status==='active'?'停用':'启用'}}</el-button><el-button link type="warning" :loading="saving" @click="rotate(s.row)">轮换密钥</el-button><el-button link @click="audit(s.row)">审计</el-button></template></el-table-column></el-table></section></el-tab-pane>
  <el-tab-pane label="读写边界" name="boundary"><section class="panel"><header><div><h2>只读能力矩阵</h2><p>{{boundarySummary}}</p></div></header><el-table :data="capabilityRows" stripe><el-table-column prop="capability" label="能力"/><el-table-column label="结论" width="100"><template #default="s"><el-tag :type="s.row.status==='禁止'?'danger':s.row.status==='待接入'?'warning':'success'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="detail" label="约束" min-width="300"/></el-table></section></el-tab-pane>
  <el-tab-pane label="数据合同" name="contract"><section class="panel"><h2>已接入数据块响应字段</h2><p>GET /api/internal-readonly/v1/&lt;数据块代码&gt;/?limit=100&amp;cursor=0；使用一次性 Client ID 与 Secret 组成 HTTP Basic 凭据。</p><dl class="contract-grid"><div v-for="f in contractFields" :key="f[0]"><dt>{{f[0]}}</dt><dd>{{f[1]}}</dd></div></dl></section></el-tab-pane>
  <el-tab-pane label="安全要求" name="security"><section class="panel"><h2>必须满足的安全门</h2><ul><li>凭据固定绑定租户、数据块与来源 IP/CIDR；字段由数据块的服务端可读目录限定。</li><li>业务只读路由拒绝 POST、PUT、PATCH 和 DELETE。</li><li>密钥仅在创建或轮换后显示一次，配置审计不保存明文。</li><li>配置审计记录审批、启停、修改与轮换；查询限流按分钟计数，不保存完整业务响应。</li></ul></section></el-tab-pane>
  <el-tab-pane label="实施状态" name="delivery"><section class="panel"><h2>交付状态</h2><el-steps direction="vertical" :active="readinessKnown?3:2" finish-status="success"><el-step title="管理入口" description="菜单、权限与只读原则已发布"/><el-step title="服务身份配置" description="创建或修改后待审核；另一位管理员审批通过后单独启用"/><el-step title="业务只读 API" :description="readinessKnown?`实时确认可读：${readyResourceNames||'无'}；路径 /api/internal-readonly/v1/`:'实时可用性未核实，不能宣称已开放'"/></el-steps><p v-if="readinessKnown" class="readiness-note">仍待接入：{{ pendingResourceNames || '无' }}</p><p v-else class="readiness-note">计划首批数据块：{{ resources.filter(item=>safeFoundationCodes.includes(item.code)).map(item=>item.label).join('、') }}。请以服务端实时目录为准。</p></section></el-tab-pane>
 </el-tabs>
 <el-dialog v-model="editorVisible" :title="editingId?'编辑调用系统':'新增调用系统'" width="760px" destroy-on-close>
  <el-form ref="formRef" :model="form" :rules="rules" label-width="110px">
   <el-form-item label="系统名称" prop="name" :error="serverErrors.name"><el-input v-model="form.name" maxlength="80"/></el-form-item>
   <el-form-item label="调用方类型" prop="caller_type" :error="serverErrors.caller_type"><div class="form-control"><el-select v-model="form.caller_type"><el-option label="内部业务系统" value="internal_system"/></el-select><span class="field-hint">知识库项目也按内部业务系统配置；读取范围由下方数据块及来源地址决定。</span></div></el-form-item>
   <el-form-item label="允许模块" prop="modules"><el-checkbox-group v-model="form.modules" class="resource-grid"><el-checkbox v-for="m in modules" :key="m.code" :value="m.code">{{m.label}}</el-checkbox></el-checkbox-group></el-form-item>
   <el-form-item label="允许数据块" prop="resources" :error="serverErrors.resources"><div class="form-control"><el-checkbox-group v-model="form.resources" class="resource-grid"><el-checkbox v-for="r in availableResources" :key="r.code" :value="r.code">{{r.label}} <small class="readiness-mark">{{!readinessKnown?'待核实':readyCodes.has(r.code)?'已接入':'待接入'}}</small></el-checkbox></el-checkbox-group><span v-if="!availableResources.length" class="field-hint">请先选择允许模块</span><span v-else class="field-hint">所有数据块均可由管理员选择；选中后默认包含该块服务端定义的全部可读字段，无需逐字段配置。只有标记“已接入”的数据块可实际读取。</span></div></el-form-item>
   <el-form-item label="共用登录"><div class="form-control"><el-switch v-model="form.allow_sso_login" active-text="允许跳转到本系统登录"/><span class="field-hint">默认关闭。调用系统只接收一次性授权码换得的基础身份，不接触密码，也不继承本系统角色或权限。可仅启用共用登录，不授权任何数据块。</span></div></el-form-item>
   <el-form-item v-if="form.allow_sso_login" label="登录回调地址" prop="sso_redirect_uris" :error="serverErrors.sso_redirect_uris"><div class="cidrs"><div v-for="(_,i) in form.sso_redirect_uris" :key="i"><el-input v-model.trim="form.sso_redirect_uris[i]" placeholder="https://other.example.com/login/callback"/><el-button link type="danger" @click="form.sso_redirect_uris.length>1&&form.sso_redirect_uris.splice(i,1)">移除</el-button></div><el-button link type="primary" @click="form.sso_redirect_uris.push('')">添加回调地址</el-button><span class="field-hint">须为完整 HTTPS 地址，按原样精确匹配；不允许通配符、查询参数或片段。</span></div></el-form-item>
   <el-form-item label="来源 IP/CIDR" prop="cidrs" :error="serverErrors.allowed_cidrs"><div class="cidrs"><div v-for="(_,i) in form.cidrs" :key="i"><el-input v-model="form.cidrs[i]" placeholder="10.20.0.0/16 或 27.154.92.194/32"/><el-button link type="danger" @click="form.cidrs.length>1&&form.cidrs.splice(i,1)">移除</el-button></div><el-button link type="primary" @click="form.cidrs.push('')">添加地址</el-button><span class="field-hint">内网网段可用 10.20.0.0/16；单个公网出口用 /32；整段 27.154.92.* 用 27.154.92.0/24。</span></div></el-form-item>
   <el-form-item label="每分钟限流" prop="rate_limit" :error="serverErrors.rate_limit_per_minute"><el-input-number v-model="form.rate_limit" :min="1" :max="10000"/></el-form-item>
   <el-form-item label="分页上限" prop="page_size" :error="serverErrors.page_size_limit"><el-input-number v-model="form.page_size" :min="1" :max="1000"/></el-form-item>
   <el-form-item label="凭据有效期" prop="expires_at" :error="serverErrors.expires_at"><el-date-picker v-model="form.expires_at" type="date" value-format="YYYY-MM-DD"/></el-form-item>
  </el-form><template #footer><el-button @click="editorVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">确认保存</el-button></template></el-dialog>
 <el-dialog v-model="reviewVisible" :title="reviewDecision==='approve'?'审核通过调用系统':'驳回调用系统'" width="520px"><p>调用系统：{{ reviewTarget?.name }}。审核人须与配置提交人不同；通过后仍需在列表单独启用。</p><el-input v-model="reviewReason" type="textarea" :rows="3" :placeholder="reviewDecision==='reject'?'请填写驳回原因':'审核说明（可选）'"/><template #footer><el-button @click="reviewVisible=false">取消</el-button><el-button :type="reviewDecision==='approve'?'primary':'danger'" :loading="saving" @click="submitReview">确认{{reviewDecision==='approve'?'通过':'驳回'}}</el-button></template></el-dialog>
 <el-dialog v-model="secretVisible" title="一次性凭据" width="560px" :close-on-click-modal="false" @closed="oneTimeCredential=null"><el-alert title="请立即复制并安全保管。关闭后系统不会再次显示密钥。" type="warning" :closable="false"/><el-descriptions v-if="oneTimeCredential" :column="1" border class="secret"><el-descriptions-item label="Client ID"><code>{{oneTimeCredential.client_id}}</code></el-descriptions-item><el-descriptions-item label="Client Secret"><code>{{oneTimeCredential.client_secret}}</code></el-descriptions-item></el-descriptions><p class="handoff-tip">将密钥通过安全渠道交给调用方技术人员，粘贴到调用方服务端的安全凭据库；不要写入网页或客户端。复制后密钥会暂留系统剪贴板，请妥善处理。</p><template #footer><el-button @click="copySecret">复制密钥</el-button><el-button type="primary" @click="secretVisible=false">我已保存并关闭</el-button></template></el-dialog>
 <el-dialog v-model="handoffVisible" :title="`${handoffTarget?.name||'调用系统'} · 接入资料`" width="720px"><el-alert v-if="handoffTarget?.status!=='active'||handoffTarget?.approval_status!=='approved'" title="当前尚未审核通过并启用，以下为配置资料，调用暂不可用。" type="warning" :closable="false"/><h3 class="handoff-heading">调用方需要修改或填写</h3><ol class="caller-steps"><li>在调用方服务端配置 <code>CLIENT_ID</code> 与 <code>CLIENT_SECRET</code>；密钥只在创建或轮换时显示一次，请单独安全交付。</li><li>向本系统管理员提供服务器实际出口 IP，由管理员登记来源 IP/CIDR；实际请求必须从该出口发起。</li><li v-if="handoffInfo?.data_read">将只读接口基址写入调用方配置，只查询 <code>ready_resources</code>；<code>pending_resources</code> 尚不可读取。</li><li v-if="handoffInfo?.shared_login">实现 HTTPS 登录回调并将精确地址交管理员登记；登录入口跳转本系统授权页，回调后由调用方服务端以一次性授权码和 PKCE S256 换取基础身份，再建立自己的会话与权限。</li></ol><p class="handoff-tip">下方为可交接的参数模板；真实 Client Secret 不在此重显，丢失时须轮换。状态不是“已批准 + 启用”前不可调用。</p><el-input :model-value="handoffText" type="textarea" :rows="16" readonly class="handoff-json"/><template #footer><el-button @click="handoffVisible=false">关闭</el-button><el-button type="primary" @click="copyHandoff">复制接入参数（不含密钥）</el-button></template></el-dialog>
 <el-drawer v-model="auditVisible" title="调用审计" size="60%"><el-table :data="auditRows"><el-table-column prop="created_at" label="时间" width="170"/><el-table-column prop="client_name" label="调用系统"/><el-table-column prop="method" label="方法" width="80"/><el-table-column prop="action" label="动作"/><el-table-column prop="source_ip" label="来源 IP"/><el-table-column prop="result" label="结果" width="80"/></el-table></el-drawer>
</main></template>
<style scoped>.api-page{display:grid;gap:20px;padding:4px 0 28px;color:#172033}.page-header{display:flex;justify-content:space-between;gap:24px}.page-header h1{margin:4px 0 8px;font-size:28px}.page-header p,.panel p,.path{margin:0;color:#667285;line-height:1.6}.content-tabs{padding:0 20px 20px;border:1px solid #e4e9f0;border-radius:10px;background:#fff}.panel{padding-top:8px}.panel>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.panel h2{margin:0 0 7px}.contract-grid{display:grid;grid-template-columns:repeat(2,1fr);border:1px solid #e4e9f0}.contract-grid div{display:grid;grid-template-columns:150px 1fr;padding:14px;border-bottom:1px solid #edf0f4}.contract-grid dt{font-family:monospace;color:#2457a7}.contract-grid dd{margin:0}.resource-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px 12px;width:100%}.form-control{display:grid;gap:4px;width:100%}.field-hint,.readiness-mark,.readiness-note,.handoff-tip{color:#909399;font-size:12px;line-height:1.5}.handoff-tip{margin:12px 0}.handoff-heading{font-size:15px;margin:18px 0 8px}.caller-steps{font-size:13px;line-height:1.7;color:#536174;padding-left:22px;margin:0 0 12px}.caller-steps li+li{margin-top:4px}.handoff-json :deep(textarea){font-family:monospace;font-size:12px}.cidrs{display:grid;gap:8px;width:100%}.cidrs>div{display:flex;gap:8px}.secret{margin-top:16px}code{word-break:break-all}@media(max-width:760px){.page-header{flex-direction:column}.contract-grid{grid-template-columns:1fr}.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
