<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { createInternalReadonlyClient, fetchInternalReadonlyAudit, fetchInternalReadonlyClients, rotateInternalReadonlyCredential, setInternalReadonlyClientStatus, updateInternalReadonlyClient } from '../../api/internalReadonly';
import { internalReadonlyModules, internalReadonlyResources, internalReadonlyResourceFields } from '../../config/internalReadonlyResources';

const activeSection=ref('clients'), clients=ref([]), auditRows=ref([]), loading=ref(false), saving=ref(false);
const editorVisible=ref(false), auditVisible=ref(false), secretVisible=ref(false), editingId=ref(null), oneTimeCredential=ref(null), formRef=ref();
const safeMethods = ['GET', 'HEAD', 'OPTIONS'];
const blockedMethods = ['POST', 'PUT', 'PATCH', 'DELETE'];
const resources=internalReadonlyResources;
const resourceFields=internalReadonlyResourceFields;
const modules=internalReadonlyModules;
const blank=()=>({name:'',caller_type:'internal_system',modules:[],resources:[],fields:[],cidrs:[''],rate_limit:120,page_size:100,expires_at:''});
const form=reactive(blank());
const cidr=/^(?:\d{1,3}\.){3}\d{1,3}(?:\/(?:[0-9]|[12][0-9]|3[0-2]))?$/;
const rules={name:[{required:true,message:'请输入系统名称'}],caller_type:[{required:true,message:'请选择调用方类型'}],modules:[{type:'array',required:true,min:1,message:'至少选择一个模块'}],resources:[{type:'array',required:true,min:1,message:'至少选择一个数据块'}],fields:[{type:'array',required:true,min:1,message:'至少选择一个字段'}],cidrs:[{validator:(_,v,done)=>v?.length&&v.every(x=>cidr.test(x))?done():done(new Error('请输入有效 IPv4 或 CIDR'))}],rate_limit:[{type:'number',min:1,max:10000,message:'限流须为 1–10000'}],page_size:[{type:'number',min:1,max:1000,message:'分页上限须为 1–1000'}],expires_at:[{required:true,message:'请选择有效期'}]};
const availableResources=computed(()=>resources.filter(item=>form.modules.includes(item.module)));
const fields=computed(()=>[...new Set(form.resources.flatMap(code=>resourceFields[code]||[]))]);
const boundarySummary=computed(()=>`${safeMethods.join(' / ')} 只读，${blockedMethods.join(' / ')} 全部拒绝`);
const capabilityRows=[{capability:'业务数据查询',status:'允许',detail:'按租户、资源、字段和时间范围限定'},{capability:'增量同步',status:'允许',detail:'使用 updated_at、deleted_at、version 和 next_cursor'},{capability:'业务内容写入',status:'禁止',detail:'不开放新增、修改、删除、审批、发布或任务触发'},{capability:'AI 生成内容回写',status:'禁止',detail:'摘要、标签、分类和提示词都不回写'}];
const contractFields=[['resource_type','资源类型'],['resource_id','资源稳定唯一标识'],['tenant_id','租户隔离标识'],['updated_at','增量同步水位'],['deleted_at','删除传播标识'],['version','数据版本'],['content_hash','内容幂等校验'],['next_cursor','分页与断点续传']];
async function load(){loading.value=true;const r=await fetchInternalReadonlyClients();loading.value=false;if(r.success)clients.value=r.data.items||[];else ElMessage.error(r.message)}
function resourceNames(value){return Object.keys(value||{}).join('、')}
function edit(row){editingId.value=row?.id||null;const configured=row?.resources&& !Array.isArray(row.resources)?row.resources:{};const resourceCodes=Object.keys(configured);Object.assign(form,blank(),{...row,modules:[...new Set(resources.filter(item=>resourceCodes.includes(item.code)).map(item=>item.module))],resources:resourceCodes,fields:[...new Set(Object.values(configured).flat())],cidrs:[...(row?.allowed_cidrs||[''])],rate_limit:row?.rate_limit_per_minute??120,page_size:row?.page_size_limit??100,expires_at:row?.expires_at?.slice?.(0,10)||''});editorVisible.value=true}
watch(()=>form.modules.slice(),()=>{const allowed=new Set(availableResources.value.map(item=>item.code));form.resources=form.resources.filter(code=>allowed.has(code));const allowedFields=new Set(fields.value);form.fields=form.fields.filter(field=>allowedFields.has(field))});
function payload(){const mapped=Object.fromEntries(form.resources.map(code=>[code,form.fields.filter(field=>resourceFields[code].includes(field))]));if(Object.values(mapped).some(items=>!items.length))throw new Error('每个资源至少选择一个适用字段');return{name:form.name,caller_type:form.caller_type,resources:mapped,allowed_cidrs:form.cidrs,rate_limit_per_minute:form.rate_limit,page_size_limit:form.page_size,expires_at:`${form.expires_at}T23:59:59+08:00`}}
async function save(){if(!(await formRef.value.validate().catch(()=>false)))return;let data;try{data=payload()}catch(error){return ElMessage.error(error.message)}await ElMessageBox.confirm(`确认${editingId.value?'更新':'创建'}此只读调用系统？`,'二次确认',{type:'warning'});saving.value=true;const r=editingId.value?await updateInternalReadonlyClient(editingId.value,data):await createInternalReadonlyClient(data);saving.value=false;if(!r.success)return ElMessage.error(r.message);editorVisible.value=false;await load();const credential=r.data?.credential||r.data;if(credential?.client_secret){oneTimeCredential.value={client_id:credential.client_id,client_secret:credential.client_secret};secretVisible.value=true}else ElMessage.success('配置已保存')}
async function status(row){const next=row.status==='active'?'disabled':'active';await ElMessageBox.confirm(`确认${next==='active'?'启用':'停用'}“${row.name}”？`,'二次确认',{type:'warning'});const r=await setInternalReadonlyClientStatus(row.id,next);if(r.success){ElMessage.success('状态已更新');await load()}else ElMessage.error(r.message)}
async function rotate(row){await ElMessageBox.confirm(`轮换“${row.name}”密钥后旧密钥立即失效，是否继续？`,'二次确认',{type:'warning'});saving.value=true;const key=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;const r=await rotateInternalReadonlyCredential(row.id,key);saving.value=false;if(r.success){oneTimeCredential.value={client_id:r.data.client_id,client_secret:r.data.client_secret};secretVisible.value=true}else ElMessage.error(r.message)}
async function audit(row){auditVisible.value=true;const r=await fetchInternalReadonlyAudit(row.id);auditRows.value=r.success?(r.data.items||[]).map(item=>({...item,client_name:row.name,method:'配置',source_ip:'--',result:'成功'})):[]}
onMounted(load);
</script>
<template><main class="api-page">
 <header class="page-header"><div><p class="path">系统管理 · API 数据接入</p><h1>内部系统数据接口</h1><p>管理员可配置调用系统、最小读取范围和独立凭据；本系统不接收调用方回写，调用方始终不能回写业务数据。</p></div><el-tag type="success" size="large" effect="plain">强制只读</el-tag></header>
 <el-alert title="配置管理能力已就绪；业务数据端点 /api/internal-readonly/v1/ 尚未上线，创建凭据不代表数据接口已开放。" type="warning" :closable="false" show-icon/>
 <el-tabs v-model="activeSection" class="content-tabs">
  <el-tab-pane label="调用系统配置" name="clients"><section class="panel"><header><div><h2>调用系统</h2><p>权限默认拒绝，按资源、字段和来源地址显式授权。</p></div><el-button type="primary" @click="edit()">新增调用系统</el-button></header><el-table v-loading="loading" :data="clients" stripe><el-table-column prop="name" label="系统名称" min-width="160"/><el-table-column prop="caller_type" label="调用方类型" width="130"/><el-table-column label="资源" min-width="170"><template #default="s">{{ resourceNames(s.row.resources) }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='active'?'success':'info'">{{s.row.status==='active'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="expires_at" label="有效期" width="180"/><el-table-column prop="last_rotated_at" label="最近轮换" width="180"/><el-table-column label="操作" width="290" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button link @click="status(s.row)">{{s.row.status==='active'?'停用':'启用'}}</el-button><el-button link type="warning" :loading="saving" @click="rotate(s.row)">轮换密钥</el-button><el-button link @click="audit(s.row)">审计</el-button></template></el-table-column></el-table></section></el-tab-pane>
  <el-tab-pane label="读写边界" name="boundary"><section class="panel"><header><div><h2>只读能力矩阵</h2><p>{{boundarySummary}}</p></div></header><el-table :data="capabilityRows" stripe><el-table-column prop="capability" label="能力"/><el-table-column label="结论" width="100"><template #default="s"><el-tag :type="s.row.status==='禁止'?'danger':'success'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="detail" label="约束" min-width="300"/></el-table></section></el-tab-pane>
  <el-tab-pane label="数据合同" name="contract"><section class="panel"><h2>增量同步字段</h2><dl class="contract-grid"><div v-for="f in contractFields" :key="f[0]"><dt>{{f[0]}}</dt><dd>{{f[1]}}</dd></div></dl></section></el-tab-pane>
  <el-tab-pane label="安全要求" name="security"><section class="panel"><h2>必须满足的安全门</h2><ul><li>凭据固定绑定租户、资源、字段与来源 IP/CIDR。</li><li>路由层与权限层同时拒绝 POST、PUT、PATCH 和 DELETE 业务写入。</li><li>密钥仅在创建或轮换后显示一次，列表和审计不保存明文。</li><li>审计只记录请求元数据，不记录完整业务响应。</li></ul></section></el-tab-pane>
  <el-tab-pane label="实施状态" name="delivery"><section class="panel"><h2>交付状态</h2><el-steps direction="vertical" :active="2" finish-status="success"><el-step title="管理入口" description="菜单、权限与只读原则已发布"/><el-step title="服务身份配置" description="调用系统、授权、启停、轮换与审计控制台已实现"/><el-step title="业务只读 API" description="/api/internal-readonly/v1/ 尚未上线，不得宣称可读取业务数据"/></el-steps></section></el-tab-pane>
 </el-tabs>
 <el-dialog v-model="editorVisible" :title="editingId?'编辑调用系统':'新增调用系统'" width="760px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="110px"><el-form-item label="系统名称" prop="name"><el-input v-model="form.name" maxlength="80"/></el-form-item><el-form-item label="调用方类型" prop="caller_type"><el-select v-model="form.caller_type"><el-option label="内部业务系统" value="internal_system"/><el-option label="知识库" value="knowledge_base"/></el-select></el-form-item><el-form-item label="允许模块" prop="modules"><el-checkbox-group v-model="form.modules" class="resource-grid"><el-checkbox v-for="m in modules" :key="m.code" :value="m.code">{{m.label}}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="允许数据块" prop="resources"><el-checkbox-group v-model="form.resources" class="resource-grid"><el-checkbox v-for="r in availableResources" :key="r.code" :value="r.code">{{r.label}}</el-checkbox></el-checkbox-group><span v-if="!availableResources.length" class="field-hint">请先选择允许模块</span></el-form-item><el-form-item label="允许字段" prop="fields"><el-select v-model="form.fields" multiple filterable style="width:100%" placeholder="请先选择允许数据块"><el-option v-for="f in fields" :key="f" :label="f" :value="f"/></el-select></el-form-item><el-form-item label="来源 IP/CIDR" prop="cidrs"><div class="cidrs"><div v-for="(_,i) in form.cidrs" :key="i"><el-input v-model="form.cidrs[i]" placeholder="10.20.0.0/16"/><el-button link type="danger" @click="form.cidrs.length>1&&form.cidrs.splice(i,1)">移除</el-button></div><el-button link type="primary" @click="form.cidrs.push('')">添加地址</el-button></div></el-form-item><el-form-item label="每分钟限流" prop="rate_limit"><el-input-number v-model="form.rate_limit" :min="1" :max="10000"/></el-form-item><el-form-item label="分页上限" prop="page_size"><el-input-number v-model="form.page_size" :min="1" :max="1000"/></el-form-item><el-form-item label="凭据有效期" prop="expires_at"><el-date-picker v-model="form.expires_at" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="editorVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">确认保存</el-button></template></el-dialog>
 <el-dialog v-model="secretVisible" title="一次性凭据" width="560px" :close-on-click-modal="false" @closed="oneTimeCredential=null"><el-alert title="请立即复制并安全保管。关闭后系统不会再次显示密钥。" type="warning" :closable="false"/><el-descriptions v-if="oneTimeCredential" :column="1" border class="secret"><el-descriptions-item label="Client ID"><code>{{oneTimeCredential.client_id}}</code></el-descriptions-item><el-descriptions-item label="Client Secret"><code>{{oneTimeCredential.client_secret}}</code></el-descriptions-item></el-descriptions><template #footer><el-button type="primary" @click="secretVisible=false">我已保存并关闭</el-button></template></el-dialog>
 <el-drawer v-model="auditVisible" title="调用审计" size="60%"><el-table :data="auditRows"><el-table-column prop="created_at" label="时间" width="170"/><el-table-column prop="client_name" label="调用系统"/><el-table-column prop="method" label="方法" width="80"/><el-table-column prop="action" label="动作"/><el-table-column prop="source_ip" label="来源 IP"/><el-table-column prop="result" label="结果" width="80"/></el-table></el-drawer>
</main></template>
<style scoped>.api-page{display:grid;gap:20px;padding:4px 0 28px;color:#172033}.page-header{display:flex;justify-content:space-between;gap:24px}.page-header h1{margin:4px 0 8px;font-size:28px}.page-header p,.panel p,.path{margin:0;color:#667285;line-height:1.6}.content-tabs{padding:0 20px 20px;border:1px solid #e4e9f0;border-radius:10px;background:#fff}.panel{padding-top:8px}.panel>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.panel h2{margin:0 0 7px}.contract-grid{display:grid;grid-template-columns:repeat(2,1fr);border:1px solid #e4e9f0}.contract-grid div{display:grid;grid-template-columns:150px 1fr;padding:14px;border-bottom:1px solid #edf0f4}.contract-grid dt{font-family:monospace;color:#2457a7}.contract-grid dd{margin:0}.resource-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px 12px;width:100%}.field-hint{color:#909399}.cidrs{display:grid;gap:8px;width:100%}.cidrs>div{display:flex;gap:8px}.secret{margin-top:16px}code{word-break:break-all}@media(max-width:760px){.page-header{flex-direction:column}.contract-grid{grid-template-columns:1fr}.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
