# Generated by Django 5.2.17 on 2026-08-14 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesexportrequest',
            name='uniq_sales_export_request',
        ),
        migrations.RemoveConstraint(
            model_name='syncrerunrequest',
            name='uniq_sales_sync_rerun',
        ),
        migrations.AddField(
            model_name='salesexportrequest',
            name='request_fingerprint',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='syncrerunrequest',
            name='data_scope',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='syncrerunrequest',
            name='request_fingerprint',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='salesexportrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'requested_by', 'request_key'), name='uniq_sales_export_request'),
        ),
        migrations.AddConstraint(
            model_name='syncrerunrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'requested_by', 'request_key'), name='uniq_sales_sync_rerun'),
        ),
    ]
