# Generated by Django 5.2.16 on 2026-08-08 10:08



import django.db.models.deletion

from django.db import migrations, models





class Migration(migrations.Migration):



    dependencies = [

        ('files', '0001_initial'),

        ('tenants', '0001_initial'),

    ]



    operations = [

        migrations.CreateModel(

            name='ControlledAttachment',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('attachment_no', models.CharField(max_length=96)),

                ('owner_type', models.CharField(max_length=32)),

                ('owner_id', models.PositiveBigIntegerField()),

                ('business_type', models.CharField(default='consolidation_handover', max_length=80)),

                ('business_id', models.CharField(max_length=128)),

                ('business_version', models.PositiveIntegerField()),

                ('file_name', models.CharField(blank=True, max_length=255)),

                ('extension', models.CharField(blank=True, max_length=12)),

                ('media_type', models.CharField(blank=True, max_length=80)),

                ('byte_size', models.PositiveBigIntegerField(default=0)),

                ('sha256', models.CharField(blank=True, max_length=64)),

                ('storage_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),

                ('state', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('scanning', 'Scanning'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined'), ('superseded', 'Superseded'), ('deleted', 'Deleted')], default='uploading', max_length=20)),

                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('passed', 'Passed'), ('failed', 'Failed'), ('quarantined', 'Quarantined')], default='pending', max_length=20)),

                ('scan_engine', models.CharField(blank=True, max_length=80)),

                ('scan_engine_version', models.CharField(blank=True, max_length=40)),

                ('scanned_at', models.DateTimeField(blank=True, null=True)),

                ('rejection_code', models.CharField(blank=True, max_length=80)),

                ('created_by_type', models.CharField(max_length=32)),

                ('created_by_id', models.PositiveBigIntegerField()),

                ('channel', models.CharField(default='internal', max_length=32)),

                ('accepted_at', models.DateTimeField(blank=True, null=True)),

                ('retention_policy_version', models.CharField(default='attach-v1', max_length=40)),

                ('upload_idempotency_key', models.CharField(max_length=128)),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('updated_at', models.DateTimeField(auto_now=True)),

                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_attachments', to='files.controlledattachment')),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_attachments', to='tenants.tenant')),

            ],

            options={

                'ordering': ['tenant_id', '-created_at', '-id'],

            },

        ),

        migrations.CreateModel(

            name='AttachmentUploadSession',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('upload_token_hash', models.CharField(max_length=64)),

                ('storage_key', models.CharField(max_length=255)),

                ('idempotency_key', models.CharField(max_length=128)),

                ('request_hash', models.CharField(max_length=64)),

                ('state', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16)),

                ('expires_at', models.DateTimeField()),

                ('created_by_type', models.CharField(max_length=32)),

                ('created_by_id', models.PositiveBigIntegerField()),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('finished_at', models.DateTimeField(blank=True, null=True)),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_sessions', to='tenants.tenant')),

                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='files.controlledattachment')),

            ],

            options={

                'ordering': ['-created_at', '-id'],

            },

        ),

        migrations.CreateModel(

            name='ControlledAttachmentEvent',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('action', models.CharField(choices=[('upload_session', 'Upload session'), ('finish', 'Finish upload'), ('scan_start', 'Start scan'), ('scan_result', 'Scan result'), ('accept', 'Accept'), ('reject', 'Reject'), ('quarantine', 'Quarantine'), ('supersede', 'Supersede'), ('delete', 'Delete')], max_length=32)),

                ('actor_type', models.CharField(max_length=32)),

                ('actor_id', models.PositiveBigIntegerField()),

                ('channel', models.CharField(default='internal', max_length=32)),

                ('before', models.JSONField(blank=True, default=dict)),

                ('after', models.JSONField(blank=True, default=dict)),

                ('reason', models.TextField(blank=True)),

                ('idempotency_key', models.CharField(max_length=128)),

                ('request_hash', models.CharField(max_length=64)),

                ('occurred_at', models.DateTimeField()),

                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='files.controlledattachment')),

                ('related_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_events', to='files.controlledattachment')),

                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_attachment_events', to='tenants.tenant')),

            ],

            options={

                'ordering': ['tenant_id', 'created_at', 'id'],

            },

        ),

        migrations.AddIndex(

            model_name='controlledattachment',

            index=models.Index(fields=['tenant', 'business_type', 'business_id', 'business_version', 'state'], name='idx_ctrl_attach_binding'),

        ),

        migrations.AddIndex(

            model_name='controlledattachment',

            index=models.Index(fields=['tenant', 'owner_type', 'owner_id', 'state'], name='idx_ctrl_attach_owner'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachment',

            constraint=models.UniqueConstraint(fields=('tenant', 'attachment_no'), name='uniq_controlled_attachment_no'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachment',

            constraint=models.UniqueConstraint(fields=('tenant', 'upload_idempotency_key'), name='uniq_controlled_attachment_upload_key'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachment',

            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sha256', ''), _negated=True), ('sha256__isnull', False)), fields=('tenant', 'sha256', 'business_type', 'business_id', 'business_version'), name='uniq_controlled_attachment_content_binding'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachment',

            constraint=models.CheckConstraint(condition=models.Q(('owner_id__gt', 0), ('business_version__gt', 0)), name='controlled_attachment_identity_positive'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachment',

            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='controlled_attachment_size_nonnegative'),

        ),

        migrations.AddConstraint(

            model_name='attachmentuploadsession',

            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_attachment_upload_session_key'),

        ),

        migrations.AddConstraint(

            model_name='attachmentuploadsession',

            constraint=models.UniqueConstraint(fields=('storage_key',), name='uniq_attachment_upload_session_storage_key'),

        ),

        migrations.AddIndex(

            model_name='controlledattachmentevent',

            index=models.Index(fields=['tenant', 'attachment', 'action', 'created_at'], name='idx_ctrl_attach_event'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachmentevent',

            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_controlled_attachment_event_key'),

        ),

        migrations.AddConstraint(

            model_name='controlledattachmentevent',

            constraint=models.CheckConstraint(condition=models.Q(('request_hash__regex', '^[0-9a-fA-F]{64}$')), name='controlled_attachment_event_hash_hex'),

        ),

    ]
