# Generated by Django 5.2.16 on 2026-08-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_controlledattachment_attachmentuploadsession_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='controlledattachment',
            name='uniq_controlled_attachment_content_binding',
        ),
        migrations.AlterField(
            model_name='controlledattachment',
            name='sha256',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='controlledattachment',
            constraint=models.UniqueConstraint(fields=('tenant', 'sha256', 'business_type', 'business_id', 'business_version'), name='uniq_controlled_attachment_content_binding'),
        ),
    ]
