PERMISSION_DEFINITIONS = (
    {
        "code": "development.product_archive.view",
        "name": "查看开发产品档案",
        "module": "development",
        "action": "product_archive.view",
        "description": "查看当前租户和数据范围内的开发产品档案。",
    },
    {
        "code": "development.product_archive.manage",
        "name": "维护开发产品档案",
        "module": "development",
        "action": "product_archive.manage",
        "description": "创建和维护虚拟测品阶段的开发产品档案。",
    },
    {
        "code": "development.product_archive.confirm",
        "name": "确认并转正开发产品档案",
        "module": "development",
        "action": "product_archive.confirm",
        "description": "确认测品并显式转为内部正式商品档案。",
    },
    {
        "code": "products.research.view",
        "name": "View product research",
        "module": "products",
        "action": "research.view",
        "description": "View tenant and data-scope filtered product research records.",
    },
    {
        "code": "products.research.manage",
        "name": "Manage product research",
        "module": "products",
        "action": "research.manage",
        "description": "Create and update authorized product research records.",
    },
    {
        "code": "products.master.view",
        "name": "View product master data",
        "module": "products",
        "action": "master.view",
        "description": "View tenant and data-scope filtered SPU and SKU records.",
    },
    {
        "code": "products.master.manage",
        "name": "Manage product master data",
        "module": "products",
        "action": "master.manage",
        "description": "Create and update authorized SPU and SKU records.",
    },
    {
        "code": "products.master.freeze",
        "name": "Freeze product codes",
        "module": "products",
        "action": "master.freeze",
        "description": "Freeze authorized SPU and SKU codes without changing lifecycle state.",
    },
    {
        "code": "products.category.view", "name": "查看商品分类", "module": "products",
        "action": "category.view", "description": "查看当前租户的商品分类。",
    },
    {
        "code": "products.category.manage", "name": "维护商品分类", "module": "products",
        "action": "category.manage", "description": "新增和维护商品三级分类。",
    },
    {
        "code": "products.color.view", "name": "查看颜色字典", "module": "products",
        "action": "color.view", "description": "查看当前租户的颜色编码字典。",
    },
    {
        "code": "products.color.manage", "name": "维护颜色字典", "module": "products",
        "action": "color.manage", "description": "新增和维护颜色编码。",
    },
    {
        "code": "products.attribute.view", "name": "查看商品属性", "module": "products",
        "action": "attribute.view", "description": "查看末级分类的 SKU 属性定义。",
    },
    {
        "code": "products.attribute.manage", "name": "维护商品属性", "module": "products",
        "action": "attribute.manage", "description": "维护末级分类的 SKU 属性及编码顺序。",
    },
    {
        "code": "products.specification.view", "name": "查看商品规格", "module": "products",
        "action": "specification.view", "description": "查看末级分类的 SKU 规格维度。",
    },
    {
        "code": "products.specification.manage", "name": "维护商品规格", "module": "products",
        "action": "specification.manage", "description": "维护末级分类的 SKU 规格维度及编码顺序。",
    },
    {
        "code": "products.bundle.view", "name": "查看组合商品", "module": "products",
        "action": "bundle.view", "description": "查看由现有 SKU 组成的组合 SKU。",
    },
    {
        "code": "products.bundle.manage", "name": "维护组合商品", "module": "products",
        "action": "bundle.manage", "description": "创建组合 SKU 并维护其现有 SKU 组成明细。",
    },
    {
        "code": "purchasing.orders.view",
        "name": "View purchase orders",
        "module": "purchasing",
        "action": "orders.view",
        "description": "View tenant and data-scope filtered purchase orders.",
    },
    {
        "code": "purchasing.orders.manage",
        "name": "Manage purchase orders",
        "module": "purchasing",
        "action": "orders.manage",
        "description": "Create and update authorized purchase order drafts; no automatic procurement.",
    },
    {
        "code": "workflow.approvals.view",
        "name": "View workflow approvals",
        "module": "workflow",
        "action": "approvals.view",
        "description": "View tenant and permission-specific data-scope filtered approvals.",
    },
    {
        "code": "workflow.approvals.submit",
        "name": "Submit mock workflow approvals",
        "module": "workflow",
        "action": "approvals.submit",
        "description": "Submit audited mock approval requests without executing business actions.",
    },
    {
        "code": "workflow.approvals.review",
        "name": "Review workflow approvals",
        "module": "workflow",
        "action": "approvals.review",
        "description": "Approve or reject authorized approvals with requester/reviewer separation.",
    },
    {
        "code": "workflow.approvals.withdraw",
        "name": "Withdraw workflow approvals",
        "module": "workflow",
        "action": "approvals.withdraw",
        "description": "Withdraw the actor's own pending approval requests.",
    },
    {
        "code": "workflow.exceptions.view",
        "name": "View workflow exceptions",
        "module": "workflow",
        "action": "exceptions.view",
        "description": "View tenant and module scoped exception records.",
    },
    {
        "code": "workflow.exceptions.manage",
        "name": "Manage workflow exceptions",
        "module": "workflow",
        "action": "exceptions.manage",
        "description": "Assign, resolve and close authorized exception records.",
    },
    {
        "code": "workflow.collaboration.view",
        "name": "View collaboration feedback",
        "module": "workflow",
        "action": "collaboration.view",
        "description": "View masked mock collaboration feedback awaiting confirmation.",
    },
    {
        "code": "workflow.collaboration.confirm",
        "name": "Confirm collaboration feedback",
        "module": "workflow",
        "action": "collaboration.confirm",
        "description": "Confirm or reject mock feedback without directly writing business state.",
    },
    {
        "code": "rpa.tasks.view",
        "name": "View RPA tasks and runs",
        "module": "rpa",
        "action": "tasks.view",
        "description": "View tenant and data-scope filtered RPA task and run metadata.",
    },
    {
        "code": "rpa.tasks.manage",
        "name": "Manage RPA manual queue",
        "module": "rpa",
        "action": "tasks.manage",
        "description": "Assign manual review and authorize mock-only retries without executing platform actions.",
    },
    {
        "code": "rpa.devices.view",
        "name": "View RPA devices",
        "module": "rpa",
        "action": "devices.view",
        "description": "View masked tenant and data-scope filtered RPA device metadata.",
    },
    {
        "code": "rpa.devices.dry_run",
        "name": "Run RPA device dry-run checks",
        "module": "rpa",
        "action": "devices.dry_run",
        "description": "Run audited local checks that never connect to a real platform or execute browser automation.",
    },
    {
        "code": "rpa.stability.view",
        "name": "View RPA stability evidence",
        "module": "rpa",
        "action": "stability.view",
        "description": "View account locks, masked page signatures, and task/run state summaries.",
    },
    {
        "code": "reports.view",
        "name": "View report catalog and exports",
        "module": "reports",
        "action": "view",
        "description": "View tenant and data-scope filtered report metadata.",
    },
    {
        "code": "reports.export",
        "name": "Request report exports",
        "module": "reports",
        "action": "export",
        "description": "Create audited placeholder report export requests.",
    },
    {
        "code": "reports.download",
        "name": "Download audited report placeholders",
        "module": "reports",
        "action": "download",
        "description": "Request short-lived placeholder download references with tenant, data-scope and audit checks.",
    },
    {
        "code": "config.view",
        "name": "View configuration",
        "module": "config",
        "action": "view",
        "description": "View authorized tenant configuration metadata and masked values.",
    },
    {
        "code": "config.manage",
        "name": "Manage tenant configuration",
        "module": "config",
        "action": "manage",
        "description": "Create versioned tenant configuration values.",
    },
    {
        "code": "config.approve",
        "name": "Approve configuration",
        "module": "config",
        "action": "approve",
        "description": "Approve configuration versions with creator/approver separation.",
    },
    {
        "code": "config.rollback",
        "name": "Rollback configuration",
        "module": "config",
        "action": "rollback",
        "description": "Create a new configuration version from authorized history.",
    },
    {
        "code": "config.system.manage",
        "name": "Manage system configuration",
        "module": "config",
        "action": "system.manage",
        "description": "Access restricted system-scope configuration versions.",
    },
    {
        "code": "products.lifecycle.view",
        "name": "View product lifecycle reviews",
        "module": "products",
        "action": "lifecycle.view",
        "description": "View tenant and data-scope filtered lifecycle reviews and decisions.",
    },
    {
        "code": "products.lifecycle.evaluate",
        "name": "Evaluate product lifecycle",
        "module": "products",
        "action": "lifecycle.evaluate",
        "description": "Generate mock product lifecycle recommendations.",
    },
    {
        "code": "products.lifecycle.confirm",
        "name": "Confirm product lifecycle reviews",
        "module": "products",
        "action": "lifecycle.confirm",
        "description": "Confirm or reject standard lifecycle recommendations.",
    },
    {
        "code": "products.lifecycle.high_risk_confirm",
        "name": "Confirm high-risk lifecycle reviews",
        "module": "products",
        "action": "lifecycle.high_risk_confirm",
        "description": "Confirm clearance, stopped, or archived lifecycle recommendations.",
    },
    {
        "code": "replenishment.view",
        "name": "View replenishment recommendations",
        "module": "replenishment",
        "action": "view",
        "description": "View tenant and data-scope filtered replenishment recommendations.",
    },
    {
        "code": "replenishment.evaluate",
        "name": "Evaluate replenishment recommendations",
        "module": "replenishment",
        "action": "evaluate",
        "description": "Generate mock replenishment recommendations without creating purchase orders.",
    },
    {
        "code": "replenishment.review",
        "name": "Review replenishment recommendations",
        "module": "replenishment",
        "action": "review",
        "description": "Accept or reject recommendations without executing procurement.",
    },
    {
        "code": "alerts.view",
        "name": "View operational alerts",
        "module": "alerts",
        "action": "view",
        "description": "View tenant and data-scope filtered operational alerts.",
    },
    {
        "code": "alerts.evaluate",
        "name": "Evaluate operational alerts",
        "module": "alerts",
        "action": "evaluate",
        "description": "Run mock tenant-scoped inventory alert evaluations.",
    },
    {
        "code": "alerts.manage",
        "name": "Manage operational alerts",
        "module": "alerts",
        "action": "manage",
        "description": "Assign, silence, handle, and close tenant-scoped operational alerts.",
    },
    {
        "code": "analytics.view",
        "name": "View analytics",
        "module": "analytics",
        "action": "view",
        "description": "View tenant-scoped metric definitions and read-only BI aggregates.",
    },
    {
        "code": "analytics.calculate",
        "name": "Calculate analytics",
        "module": "analytics",
        "action": "calculate",
        "description": "Run tenant-scoped mock BI metric aggregation.",
    },
    {
        "code": "analytics.manage",
        "name": "Manage analytics definitions",
        "module": "analytics",
        "action": "manage",
        "description": "Create audited versions of tenant-scoped analytics metric definitions.",
    },
    {
        "code": "sales_management.view",
        "name": "查看销售总览",
        "module": "sales_management",
        "action": "view",
        "description": "查看当前租户和数据范围内的销售总览指标。",
    },
    {
        "code": "sales_management.orders.view",
        "name": "查看销售订单",
        "module": "sales_management",
        "action": "orders.view",
        "description": "查看当前租户和数据范围内的销售订单及明细。",
    },
    {
        "code": "sales_management.returns.view",
        "name": "查看退款退货",
        "module": "sales_management",
        "action": "returns.view",
        "description": "查看当前租户和数据范围内的退款、退货及取消记录。",
    },
    {
        "code": "sales_management.stores.view",
        "name": "查看门店销售",
        "module": "sales_management",
        "action": "stores.view",
        "description": "查看当前租户和数据范围内的门店销售表现。",
    },
    {
        "code": "sales_management.skus.view",
        "name": "查看 SKU 销售",
        "module": "sales_management",
        "action": "skus.view",
        "description": "查看当前租户和数据范围内的 SKU 销售表现。",
    },
    {
        "code": "sales_management.export",
        "name": "导出销售明细",
        "module": "sales_management",
        "action": "export",
        "description": "按当前租户、角色和数据范围申请销售数据导出。",
    },
    {
        "code": "sales_management.data_quality.view",
        "name": "查看销售数据质量",
        "module": "sales_management",
        "action": "data_quality.view",
        "description": "查看销售同步新鲜度、失败、重复和映射质量问题。",
    },
    {
        "code": "sales_management.sync.view",
        "name": "查看销售数据同步",
        "module": "sales_management",
        "action": "sync.view",
        "description": "查看销售数据来源、同步运行和同步水位信息。",
    },
    {
        "code": "finance.view",
        "name": "View finance data",
        "module": "finance",
        "action": "view",
        "description": "View finance statements, withdrawals, receipts, matches, and exceptions.",
    },
    {
        "code": "finance.export",
        "name": "Export finance data",
        "module": "finance",
        "action": "export",
        "description": "Export authorized finance data.",
    },
    {
        "code": "finance.import",
        "name": "Import finance data",
        "module": "finance",
        "action": "import",
        "description": "Import authorized finance data, including phase 2 demo fixtures.",
    },
    {
        "code": "finance.reconcile",
        "name": "Reconcile finance data",
        "module": "finance",
        "action": "reconcile",
        "description": "Run and review finance reconciliation suggestions.",
    },
    {
        "code": "finance.exception.handle",
        "name": "Handle finance exceptions",
        "module": "finance",
        "action": "exception.handle",
        "description": "Handle finance reconciliation exceptions.",
    },
    {
        "code": "integrations.view",
        "name": "View integrations",
        "module": "integrations",
        "action": "view",
        "description": "View integration configuration metadata and synchronization runs.",
    },
    {
        "code": "integrations.manage",
        "name": "Manage integrations",
        "module": "integrations",
        "action": "manage",
        "description": "Create, update, verify, or disable integration configurations and jobs.",
    },
    {
        "code": "integrations.rotate",
        "name": "Rotate integration credentials",
        "module": "integrations",
        "action": "rotate",
        "description": "Rotate encrypted integration credentials.",
    },
    {
        "code": "integrations.run",
        "name": "Run integration synchronization",
        "module": "integrations",
        "action": "run",
        "description": "Run phase 2 mock integration synchronization jobs.",
    },
    {
        "code": "integrations.run_live_readonly",
        "name": "Run live readonly synchronization",
        "module": "integrations",
        "action": "run_live_readonly",
        "description": "Queue an approved production readonly synchronization job.",
    },
    *(
        {
            "code": f"integrations.{suffix}",
            "name": name,
            "module": "integrations",
            "action": suffix,
            "description": description,
        }
        for suffix, name, description in (
            ("store.view", "View marketplace store authorizations", "View tenant-scoped store authorization metadata."),
            ("store.authorize", "Authorize marketplace stores", "Create a controlled marketplace store authorization."),
            ("store.revoke", "Revoke marketplace store authorizations", "Revoke a store authorization with an audit record."),
            ("store.sync", "Synchronize marketplace stores", "Request an approved store synchronization action."),
            ("store.retry", "Retry marketplace store operations", "Retry a failed marketplace store operation."),
            ("credential.rotate", "Rotate marketplace credential references", "Rotate custody references without receiving platform secrets."),
            ("config.view", "View API platform configurations", "View tenant-scoped API platform configuration metadata."),
            ("config.create", "Create API platform configurations", "Create a tenant-scoped platform configuration."),
            ("config.update", "Update API platform configurations", "Update non-secret platform configuration fields."),
            ("config.verify", "Verify API platform configurations", "Verify an approved platform connection."),
            ("config.disable", "Disable API platform configurations", "Disable a tenant-scoped platform configuration."),
            ("credential.clear", "Clear API platform credentials", "Revoke and clear custody references after confirmation."),
            ("audit.view", "View integration audit logs", "View redacted tenant-scoped integration audit records."),
        )
    ),
    {
        "code": "suppliers.performance.view",
        "name": "View supplier performance",
        "module": "suppliers",
        "action": "performance.view",
        "description": "View supplier performance within the assigned data scope.",
    },
    {
        "code": "suppliers.performance.calculate",
        "name": "Calculate supplier performance",
        "module": "suppliers",
        "action": "performance.calculate",
        "description": "Calculate phase 2 mock supplier performance snapshots.",
    },
    {
        "code": "products.status.view",
        "name": "View product status",
        "module": "products",
        "action": "status.view",
        "description": "View product status recommendations and transitions.",
    },
    {
        "code": "products.status.evaluate",
        "name": "Evaluate product status",
        "module": "products",
        "action": "status.evaluate",
        "description": "Generate product status recommendations from phase 2 mock metrics.",
    },
    {
        "code": "products.status.confirm",
        "name": "Confirm product status",
        "module": "products",
        "action": "status.confirm",
        "description": "Confirm or reject standard product status recommendations.",
    },
    {
        "code": "products.status.high_risk_confirm",
        "name": "Confirm high-risk product status",
        "module": "products",
        "action": "status.high_risk_confirm",
        "description": "Confirm clearance, stopped, or archived product status recommendations.",
    },
    {
        "code": "system.organization.view",
        "name": "View organization directory",
        "module": "system",
        "action": "organization.view",
        "description": "View tenant-scoped departments and organization structure.",
    },
    {
        "code": "system.organization.manage",
        "name": "Manage organization directory",
        "module": "system",
        "action": "organization.manage",
        "description": "Create and update tenant-scoped departments.",
    },
    {
        "code": "system.users.view",
        "name": "View user directory",
        "module": "system",
        "action": "users.view",
        "description": "View masked tenant-scoped user account metadata.",
    },
    {
        "code": "system.users.manage",
        "name": "Manage user directory",
        "module": "system",
        "action": "users.manage",
        "description": "Create, activate, deactivate, and assign roles to tenant users.",
    },
    {
        "code": "system.roles.view",
        "name": "View roles and permissions",
        "module": "system",
        "action": "roles.view",
        "description": "View tenant roles, permission catalog, and data scopes.",
    },
    {
        "code": "system.roles.manage",
        "name": "Manage roles and permissions",
        "module": "system",
        "action": "roles.manage",
        "description": "Create roles and update tenant role permissions and data scopes.",
    },
    {
        "code": "masterdata.view",
        "name": "View master data",
        "module": "masterdata",
        "action": "view",
        "description": "View tenant-scoped platform, store, warehouse, and supplier archives.",
    },
    {
        "code": "masterdata.manage",
        "name": "Manage master data",
        "module": "masterdata",
        "action": "manage",
        "description": "Create, update, activate, and deactivate tenant master data.",
    },
    {
        "code": "influencers.view",
        "name": "View influencers",
        "module": "influencers",
        "action": "view",
        "description": "View tenant-scoped influencer profiles and masked contact details.",
    },
    {
        "code": "influencers.manage",
        "name": "Manage influencers",
        "module": "influencers",
        "action": "manage",
        "description": "Create, update, activate, and deactivate tenant-scoped influencer profiles.",
    },
    {
        "code": "influencers.outreach.view", "name": "View outreach tasks",
        "module": "influencers", "action": "outreach.view",
        "description": "View tenant-scoped influencer outreach tasks.",
    },
    {
        "code": "influencers.outreach.manage", "name": "Manage outreach tasks",
        "module": "influencers", "action": "outreach.manage",
        "description": "Create and transition audited tenant-scoped outreach tasks.",
    },
    {
        "code": "influencers.fulfillment.view", "name": "View sample fulfillment",
        "module": "influencers", "action": "fulfillment.view",
        "description": "View tenant-scoped sample fulfillment records.",
    },
    {
        "code": "influencers.fulfillment.manage", "name": "Manage sample fulfillment",
        "module": "influencers", "action": "fulfillment.manage",
        "description": "Create idempotent sample requests and transition fulfillment status.",
    },
    {
        "code": "influencers.catalog.view", "name": "View influencer product prices",
        "module": "influencers", "action": "catalog.view",
        "description": "Query tenant, store and site scoped SKU price snapshots.",
    },
    {
        "code": "security.operations.view",
        "name": "View security operations",
        "module": "security",
        "action": "operations.view",
        "description": "View masked credential metadata and tenant operation audit summaries.",
    },
    {
        "code": "governance.api.view", "name": "View API contracts", "module": "governance",
        "action": "api.view", "description": "View tenant and data-scope filtered API contracts.",
    },
    {
        "code": "governance.api.check", "name": "Check API contracts", "module": "governance",
        "action": "api.check", "description": "Run fixed dry-run API contract checks without business writes.",
    },
    {
        "code": "governance.assistants.view", "name": "View assistant governance", "module": "governance",
        "action": "assistants.view", "description": "View assistant capability and safety definitions.",
    },
    {
        "code": "governance.assistants.evaluate", "name": "Evaluate assistant definitions", "module": "governance",
        "action": "assistants.evaluate", "description": "Run fixed assistant governance dry-runs without tool execution.",
    },
    {
        "code": "pilot.readiness.view", "name": "View pilot readiness", "module": "pilot",
        "action": "readiness.view", "description": "View controlled pilot readiness evidence.",
    },
    {
        "code": "pilot.topology.view", "name": "View pilot topology", "module": "pilot",
        "action": "topology.view", "description": "View masked controlled-pilot topology metadata.",
    },
    {
        "code": "pilot.topology.verify", "name": "Verify pilot topology", "module": "pilot",
        "action": "topology.verify", "description": "Run fixed topology dry-run validation without remote execution.",
    },
    {
        "code": "pilot.recovery.view", "name": "View recovery plans", "module": "pilot",
        "action": "recovery.view", "description": "View authorized recovery plans and drill evidence.",
    },
    {
        "code": "pilot.recovery.plan", "name": "Plan recovery drills", "module": "pilot",
        "action": "recovery.plan", "description": "Create and submit recovery plans without executing infrastructure commands.",
    },
    {
        "code": "pilot.recovery.review", "name": "Review recovery plans", "module": "pilot",
        "action": "recovery.review", "description": "Approve or reject recovery plans with separation of duties.",
    },
    {
        "code": "pilot.recovery.record", "name": "Record recovery evidence", "module": "pilot",
        "action": "recovery.record", "description": "Record externally performed recovery drill outcomes.",
    },
    {
        "code": "pilot.release.view", "name": "View release plans", "module": "pilot",
        "action": "release.view", "description": "View authorized controlled-pilot release plans.",
    },
    {
        "code": "pilot.release.plan", "name": "Plan pilot releases", "module": "pilot",
        "action": "release.plan", "description": "Create release plans without performing deployment.",
    },
    {
        "code": "pilot.release.review", "name": "Review pilot releases", "module": "pilot",
        "action": "release.review", "description": "Approve or reject controlled-pilot release plans.",
    },
    {
        "code": "pilot.release.record", "name": "Record release evidence", "module": "pilot",
        "action": "release.record", "description": "Record externally performed release outcomes.",
    },
    {
        "code": "pilot.release.rollback", "name": "Review and record rollback", "module": "pilot",
        "action": "release.rollback", "description": "Approve and record externally performed rollback outcomes.",
    },
    {
        "code": "pilot.capacity.view", "name": "View pilot capacity", "module": "pilot",
        "action": "capacity.view", "description": "View tenant and scope filtered capacity observations.",
    },
    {
        "code": "pilot.control.view", "name": "View pilot control room", "module": "pilot",
        "action": "control.view", "description": "View masked production-pilot readiness evidence.",
    },
    {
        "code": "pilot.security_review.view", "name": "View pilot security reviews", "module": "pilot",
        "action": "security_review.view", "description": "View scoped security review evidence.",
    },
    {
        "code": "pilot.security_review.plan", "name": "Plan pilot security reviews", "module": "pilot",
        "action": "security_review.plan", "description": "Create and submit scoped security reviews.",
    },
    {
        "code": "pilot.security_review.review", "name": "Review pilot security reviews", "module": "pilot",
        "action": "security_review.review", "description": "Approve or reject security reviews with separation of duties.",
    },
    # Global listing workbench permissions.  Legacy profile/template codes are
    # retained and accepted by the listings permission adapters.
    {
        "code": "listings.workbench.view", "name": "查看全球刊登工作台", "module": "listings",
        "action": "workbench.view", "description": "查看租户范围内的全球刊登商品、店铺和模板选择器。",
    },
    {
        "code": "listings.workbench.manage", "name": "管理全球刊登工作台", "module": "listings",
        "action": "workbench.manage", "description": "批量生成租户范围内的刊登草稿。",
    },
    {
        "code": "listings.mapping.view", "name": "查看平台类目与属性映射", "module": "listings",
        "action": "mapping.view", "description": "查看租户范围内的平台类目及商品属性映射。",
    },
    {
        "code": "listings.mapping.manage", "name": "维护平台类目与属性映射", "module": "listings",
        "action": "mapping.manage", "description": "维护租户范围内的平台类目及商品属性映射。",
    },
    {
        "code": "listings.task.view", "name": "查看刊登任务与日志", "module": "listings",
        "action": "task.view", "description": "查看刊登任务、步骤日志和异常。",
    },
    {
        "code": "listings.task.manage", "name": "管理刊登任务", "module": "listings",
        "action": "task.manage", "description": "发起、重试或记录刊登执行任务；不代表已接通外部平台。",
    },
    {
        "code": "listings.publish.production", "name": "确认生产刊登", "module": "listings",
        "action": "publish.production", "description": "二次确认生产模式的刊登任务。",
    },
    *(
        {
            "code": f"pilot.{resource}.{action}",
            "name": f"{action.title()} pilot {resource.replace('_', ' ')}",
            "module": "pilot",
            "action": f"{resource}.{action}",
            "description": f"{action.title()} scoped pilot {resource.replace('_', ' ')} records without external execution.",
        }
        for resource, actions in (
            ("verification", ("view", "plan", "review", "record", "cancel")),
            ("performance", ("view", "plan", "review", "record", "cancel")),
            ("entry", ("view", "plan", "review")),
        )
        for action in actions
    ),
)


def permission_defaults(definition):
    return {key: value for key, value in definition.items() if key != "code"}


# ``Permission.name`` predates the Chinese administration UI and a number of
# migration increments still seed English names.  Keep the API/code contract
# stable, while exposing one canonical Chinese label for the permission
# matrix.  Codes that are added by a later increment can use the deterministic
# fallback in ``permission_display_name`` until their product label is added.
PERMISSION_DISPLAY_NAMES_ZH = {
    "products.research.view": "查看商品调研",
    "products.research.manage": "管理商品调研",
    "products.master.view": "查看商品主数据",
    "products.master.manage": "管理商品主数据",
    "products.master.freeze": "冻结商品编码",
    "products.category.view": "查看商品分类",
    "products.category.manage": "维护商品分类",
    "products.color.view": "查看颜色字典",
    "products.color.manage": "维护颜色字典",
    "products.attribute.view": "查看商品属性",
    "products.attribute.manage": "维护商品属性",
    "products.specification.view": "查看商品规格",
    "products.specification.manage": "维护商品规格",
    "products.bundle.view": "查看组合商品",
    "products.bundle.manage": "维护组合商品",
    "purchasing.orders.view": "查看采购订单",
    "purchasing.orders.manage": "管理采购订单",
    "workflow.approvals.view": "查看审批流程",
    "workflow.approvals.submit": "提交审批流程",
    "workflow.approvals.review": "审核审批流程",
    "workflow.approvals.withdraw": "撤回审批流程",
    "workflow.exceptions.view": "查看流程异常",
    "workflow.exceptions.manage": "处理流程异常",
    "workflow.collaboration.view": "查看协同反馈",
    "workflow.collaboration.confirm": "确认协同反馈",
    "rpa.tasks.view": "查看 RPA 任务",
    "rpa.tasks.manage": "管理 RPA 任务",
    "rpa.devices.view": "查看 RPA 设备",
    "rpa.devices.dry_run": "执行 RPA 演练",
    "rpa.stability.view": "查看 RPA 稳定性",
    "reports.view": "查看报表目录",
    "reports.export": "导出报表",
    "reports.download": "下载报表",
    "config.view": "查看系统配置",
    "config.manage": "管理系统配置",
    "config.approve": "审批系统配置",
    "config.rollback": "回滚系统配置",
    "config.system.manage": "管理系统级配置",
    "products.lifecycle.view": "查看商品生命周期",
    "products.lifecycle.evaluate": "评估商品生命周期",
    "products.lifecycle.confirm": "确认商品生命周期",
    "products.lifecycle.high_risk_confirm": "确认高风险生命周期",
    "replenishment.view": "查看补货建议",
    "replenishment.evaluate": "评估补货建议",
    "replenishment.review": "审核补货建议",
    "alerts.view": "查看运营预警",
    "alerts.evaluate": "评估运营预警",
    "alerts.manage": "管理运营预警",
    "analytics.view": "查看分析数据",
    "analytics.calculate": "计算分析数据",
    "analytics.manage": "管理分析定义",
    "sales_management.view": "查看销售总览",
    "sales_management.orders.view": "查看销售订单",
    "sales_management.returns.view": "查看退款退货",
    "sales_management.stores.view": "查看门店销售",
    "sales_management.skus.view": "查看 SKU 销售",
    "sales_management.export": "导出销售明细",
    "sales_management.data_quality.view": "查看销售数据质量",
    "sales_management.sync.view": "查看销售数据同步",
    "finance.view": "查看财务数据",
    "finance.export": "导出财务数据",
    "finance.import": "导入财务数据",
    "finance.reconcile": "对账财务数据",
    "finance.exception.handle": "处理财务异常",
    "integrations.view": "查看集成配置",
    "integrations.manage": "管理集成配置",
    "integrations.rotate": "轮换集成凭据",
    "integrations.run": "运行集成同步",
    "integrations.run_live_readonly": "运行生产只读同步",
    "integrations.store.view": "查看平台店铺授权",
    "integrations.store.authorize": "授权平台店铺",
    "integrations.store.revoke": "撤销平台店铺授权",
    "integrations.store.sync": "同步平台店铺",
    "integrations.store.retry": "重试平台店铺操作",
    "integrations.credential.rotate": "轮换平台凭据引用",
    "integrations.config.view": "查看 API 平台配置",
    "integrations.config.create": "创建 API 平台配置",
    "integrations.config.update": "更新 API 平台配置",
    "integrations.config.verify": "验证 API 平台配置",
    "integrations.config.disable": "停用 API 平台配置",
    "integrations.credential.clear": "清理 API 平台凭据",
    "integrations.audit.view": "查看集成审计日志",
    "suppliers.performance.view": "查看供应商绩效",
    "suppliers.performance.calculate": "计算供应商绩效",
    "products.status.view": "查看商品状态",
    "products.status.evaluate": "评估商品状态",
    "products.status.confirm": "确认商品状态",
    "products.status.high_risk_confirm": "确认高风险商品状态",
    "system.organization.view": "查看组织架构",
    "system.organization.manage": "管理组织架构",
    "system.users.view": "查看用户目录",
    "system.users.manage": "管理用户目录",
    "system.roles.view": "查看角色与权限",
    "system.roles.manage": "管理角色与权限",
    "masterdata.view": "查看基础档案",
    "masterdata.manage": "管理基础档案",
    "influencers.view": "查看达人目录",
    "influencers.manage": "管理达人目录",
    "influencers.outreach.view": "查看达人触达任务",
    "influencers.outreach.manage": "管理达人触达任务",
    "influencers.fulfillment.view": "查看样品履约",
    "influencers.fulfillment.manage": "管理样品履约",
    "influencers.catalog.view": "查看达人商品价格",
    "security.operations.view": "查看安全运维",
    "governance.api.view": "查看 API 合同",
    "governance.api.check": "检查 API 合同",
    "governance.assistants.view": "查看助手治理",
    "governance.assistants.evaluate": "评估助手定义",
    "pilot.readiness.view": "查看试点就绪度",
    "pilot.topology.view": "查看试点拓扑",
    "pilot.topology.verify": "验证试点拓扑",
    "pilot.recovery.view": "查看恢复计划",
    "pilot.recovery.plan": "规划恢复演练",
    "pilot.recovery.review": "审核恢复计划",
    "pilot.recovery.record": "记录恢复证据",
    "pilot.release.view": "查看发布计划",
    "pilot.release.plan": "规划试点发布",
    "pilot.release.review": "审核试点发布",
    "pilot.release.record": "记录发布证据",
    "pilot.release.rollback": "审核并记录回滚",
    "pilot.capacity.view": "查看试点容量",
    "pilot.control.view": "查看试点控制台",
    "pilot.security_review.view": "查看试点安全评审",
    "pilot.security_review.plan": "规划试点安全评审",
    "pilot.security_review.review": "审核试点安全评审",
    "listings.workbench.view": "查看全球刊登工作台",
    "listings.workbench.manage": "管理全球刊登工作台",
    "listings.mapping.view": "查看平台类目与属性映射",
    "listings.mapping.manage": "维护平台类目与属性映射",
    "listings.task.view": "查看刊登任务与日志",
    "listings.task.manage": "管理刊登任务",
    "listings.publish.production": "确认生产刊登",
}


_PERMISSION_MODULE_NAMES_ZH = {
    "products": "商品",
    "purchasing": "采购",
    "workflow": "流程",
    "rpa": "RPA",
    "reports": "报表",
    "config": "配置",
    "replenishment": "补货",
    "alerts": "预警",
    "analytics": "分析",
    "sales_management": "销售管理",
    "finance": "财务",
    "integrations": "集成",
    "suppliers": "供应商",
    "system": "系统",
    "masterdata": "基础档案",
    "influencers": "达人",
    "security": "安全",
    "governance": "治理",
    "pilot": "试点",
    "listings": "刊登",
}
_PERMISSION_ACTION_NAMES_ZH = {
    "view": "查看",
    "manage": "管理",
    "create": "创建",
    "update": "更新",
    "calculate": "计算",
    "evaluate": "评估",
    "review": "审核",
    "confirm": "确认",
    "submit": "提交",
    "withdraw": "撤回",
    "export": "导出",
    "import": "导入",
    "download": "下载",
    "run": "运行",
    "plan": "规划",
    "record": "记录",
    "verify": "验证",
    "cancel": "取消",
    "rollback": "回滚",
    "rotate": "轮换",
    "freeze": "冻结",
    "handle": "处理",
    "dry_run": "执行演练",
}
_PERMISSION_RESOURCE_NAMES_ZH = {
    "research": "商品调研",
    "master": "商品主数据",
    "orders": "采购订单",
    "approvals": "审批流程",
    "exceptions": "流程异常",
    "collaboration": "协同反馈",
    "tasks": "任务",
    "devices": "设备",
    "stability": "稳定性",
    "roles": "角色与权限",
    "users": "用户目录",
    "organization": "组织架构",
    "readiness": "试点就绪度",
    "topology": "试点拓扑",
    "recovery": "恢复计划",
    "release": "试点发布",
    "capacity": "试点容量",
    "control": "试点控制台",
    "security_review": "试点安全评审",
    "verification": "验证运行",
    "performance": "性能运行",
    "entry": "准入决策",
}


def permission_display_name(code, fallback=""):
    """Return a stable Chinese label without changing the permission code."""
    if code in PERMISSION_DISPLAY_NAMES_ZH:
        return PERMISSION_DISPLAY_NAMES_ZH[code]
    if fallback and any("\u4e00" <= char <= "\u9fff" for char in str(fallback)):
        return fallback

    parts = str(code or "").split(".")
    action = parts[-1] if parts else ""
    resource = parts[-2] if len(parts) > 1 else ""
    module = parts[0] if parts else ""
    action_label = _PERMISSION_ACTION_NAMES_ZH.get(action, "配置")
    resource_label = _PERMISSION_RESOURCE_NAMES_ZH.get(resource, resource.replace("_", " "))
    module_label = _PERMISSION_MODULE_NAMES_ZH.get(module, module)
    if resource_label:
        return f"{action_label}{resource_label}"
    return f"{action_label}{module_label}"
