PERMISSION_DEFINITIONS = (
    {
        "code": "workflow.approvals.view",
        "name": "View workflow approvals",
        "module": "workflow",
        "action": "approvals.view",
        "description": "View tenant and permission-specific data-scope filtered approvals.",
    },
    {
        "code": "workflow.approvals.submit",
        "name": "Submit mock workflow approvals",
        "module": "workflow",
        "action": "approvals.submit",
        "description": "Submit audited mock approval requests without executing business actions.",
    },
    {
        "code": "workflow.approvals.review",
        "name": "Review workflow approvals",
        "module": "workflow",
        "action": "approvals.review",
        "description": "Approve or reject authorized approvals with requester/reviewer separation.",
    },
    {
        "code": "workflow.approvals.withdraw",
        "name": "Withdraw workflow approvals",
        "module": "workflow",
        "action": "approvals.withdraw",
        "description": "Withdraw the actor's own pending approval requests.",
    },
    {
        "code": "workflow.exceptions.view",
        "name": "View workflow exceptions",
        "module": "workflow",
        "action": "exceptions.view",
        "description": "View tenant and module scoped exception records.",
    },
    {
        "code": "workflow.exceptions.manage",
        "name": "Manage workflow exceptions",
        "module": "workflow",
        "action": "exceptions.manage",
        "description": "Assign, resolve and close authorized exception records.",
    },
    {
        "code": "workflow.collaboration.view",
        "name": "View collaboration feedback",
        "module": "workflow",
        "action": "collaboration.view",
        "description": "View masked mock collaboration feedback awaiting confirmation.",
    },
    {
        "code": "workflow.collaboration.confirm",
        "name": "Confirm collaboration feedback",
        "module": "workflow",
        "action": "collaboration.confirm",
        "description": "Confirm or reject mock feedback without directly writing business state.",
    },
    {
        "code": "rpa.tasks.view",
        "name": "View RPA tasks and runs",
        "module": "rpa",
        "action": "tasks.view",
        "description": "View tenant and data-scope filtered RPA task and run metadata.",
    },
    {
        "code": "rpa.tasks.manage",
        "name": "Manage RPA manual queue",
        "module": "rpa",
        "action": "tasks.manage",
        "description": "Assign manual review and authorize mock-only retries without executing platform actions.",
    },
    {
        "code": "rpa.devices.view",
        "name": "View RPA devices",
        "module": "rpa",
        "action": "devices.view",
        "description": "View masked tenant and data-scope filtered RPA device metadata.",
    },
    {
        "code": "rpa.devices.dry_run",
        "name": "Run RPA device dry-run checks",
        "module": "rpa",
        "action": "devices.dry_run",
        "description": "Run audited local checks that never connect to a real platform or execute browser automation.",
    },
    {
        "code": "rpa.stability.view",
        "name": "View RPA stability evidence",
        "module": "rpa",
        "action": "stability.view",
        "description": "View account locks, masked page signatures, and task/run state summaries.",
    },
    {
        "code": "reports.view",
        "name": "View report catalog and exports",
        "module": "reports",
        "action": "view",
        "description": "View tenant and data-scope filtered report metadata.",
    },
    {
        "code": "reports.export",
        "name": "Request report exports",
        "module": "reports",
        "action": "export",
        "description": "Create audited placeholder report export requests.",
    },
    {
        "code": "reports.download",
        "name": "Download audited report placeholders",
        "module": "reports",
        "action": "download",
        "description": "Request short-lived placeholder download references with tenant, data-scope and audit checks.",
    },
    {
        "code": "config.view",
        "name": "View configuration",
        "module": "config",
        "action": "view",
        "description": "View authorized tenant configuration metadata and masked values.",
    },
    {
        "code": "config.manage",
        "name": "Manage tenant configuration",
        "module": "config",
        "action": "manage",
        "description": "Create versioned tenant configuration values.",
    },
    {
        "code": "config.approve",
        "name": "Approve configuration",
        "module": "config",
        "action": "approve",
        "description": "Approve configuration versions with creator/approver separation.",
    },
    {
        "code": "config.rollback",
        "name": "Rollback configuration",
        "module": "config",
        "action": "rollback",
        "description": "Create a new configuration version from authorized history.",
    },
    {
        "code": "config.system.manage",
        "name": "Manage system configuration",
        "module": "config",
        "action": "system.manage",
        "description": "Access restricted system-scope configuration versions.",
    },
    {
        "code": "products.lifecycle.view",
        "name": "View product lifecycle reviews",
        "module": "products",
        "action": "lifecycle.view",
        "description": "View tenant and data-scope filtered lifecycle reviews and decisions.",
    },
    {
        "code": "products.lifecycle.evaluate",
        "name": "Evaluate product lifecycle",
        "module": "products",
        "action": "lifecycle.evaluate",
        "description": "Generate mock product lifecycle recommendations.",
    },
    {
        "code": "products.lifecycle.confirm",
        "name": "Confirm product lifecycle reviews",
        "module": "products",
        "action": "lifecycle.confirm",
        "description": "Confirm or reject standard lifecycle recommendations.",
    },
    {
        "code": "products.lifecycle.high_risk_confirm",
        "name": "Confirm high-risk lifecycle reviews",
        "module": "products",
        "action": "lifecycle.high_risk_confirm",
        "description": "Confirm clearance, stopped, or archived lifecycle recommendations.",
    },
    {
        "code": "replenishment.view",
        "name": "View replenishment recommendations",
        "module": "replenishment",
        "action": "view",
        "description": "View tenant and data-scope filtered replenishment recommendations.",
    },
    {
        "code": "replenishment.evaluate",
        "name": "Evaluate replenishment recommendations",
        "module": "replenishment",
        "action": "evaluate",
        "description": "Generate mock replenishment recommendations without creating purchase orders.",
    },
    {
        "code": "replenishment.review",
        "name": "Review replenishment recommendations",
        "module": "replenishment",
        "action": "review",
        "description": "Accept or reject recommendations without executing procurement.",
    },
    {
        "code": "alerts.view",
        "name": "View operational alerts",
        "module": "alerts",
        "action": "view",
        "description": "View tenant and data-scope filtered operational alerts.",
    },
    {
        "code": "alerts.evaluate",
        "name": "Evaluate operational alerts",
        "module": "alerts",
        "action": "evaluate",
        "description": "Run mock tenant-scoped inventory alert evaluations.",
    },
    {
        "code": "alerts.manage",
        "name": "Manage operational alerts",
        "module": "alerts",
        "action": "manage",
        "description": "Assign, silence, handle, and close tenant-scoped operational alerts.",
    },
    {
        "code": "analytics.view",
        "name": "View analytics",
        "module": "analytics",
        "action": "view",
        "description": "View tenant-scoped metric definitions and read-only BI aggregates.",
    },
    {
        "code": "analytics.calculate",
        "name": "Calculate analytics",
        "module": "analytics",
        "action": "calculate",
        "description": "Run tenant-scoped mock BI metric aggregation.",
    },
    {
        "code": "analytics.manage",
        "name": "Manage analytics definitions",
        "module": "analytics",
        "action": "manage",
        "description": "Create audited versions of tenant-scoped analytics metric definitions.",
    },
    {
        "code": "finance.view",
        "name": "View finance data",
        "module": "finance",
        "action": "view",
        "description": "View finance statements, withdrawals, receipts, matches, and exceptions.",
    },
    {
        "code": "finance.export",
        "name": "Export finance data",
        "module": "finance",
        "action": "export",
        "description": "Export authorized finance data.",
    },
    {
        "code": "finance.import",
        "name": "Import finance data",
        "module": "finance",
        "action": "import",
        "description": "Import authorized finance data, including phase 2 demo fixtures.",
    },
    {
        "code": "finance.reconcile",
        "name": "Reconcile finance data",
        "module": "finance",
        "action": "reconcile",
        "description": "Run and review finance reconciliation suggestions.",
    },
    {
        "code": "finance.exception.handle",
        "name": "Handle finance exceptions",
        "module": "finance",
        "action": "exception.handle",
        "description": "Handle finance reconciliation exceptions.",
    },
    {
        "code": "integrations.view",
        "name": "View integrations",
        "module": "integrations",
        "action": "view",
        "description": "View integration configuration metadata and synchronization runs.",
    },
    {
        "code": "integrations.manage",
        "name": "Manage integrations",
        "module": "integrations",
        "action": "manage",
        "description": "Create, update, verify, or disable integration configurations and jobs.",
    },
    {
        "code": "integrations.rotate",
        "name": "Rotate integration credentials",
        "module": "integrations",
        "action": "rotate",
        "description": "Rotate encrypted integration credentials.",
    },
    {
        "code": "integrations.run",
        "name": "Run integration synchronization",
        "module": "integrations",
        "action": "run",
        "description": "Run phase 2 mock integration synchronization jobs.",
    },
    {
        "code": "suppliers.performance.view",
        "name": "View supplier performance",
        "module": "suppliers",
        "action": "performance.view",
        "description": "View supplier performance within the assigned data scope.",
    },
    {
        "code": "suppliers.performance.calculate",
        "name": "Calculate supplier performance",
        "module": "suppliers",
        "action": "performance.calculate",
        "description": "Calculate phase 2 mock supplier performance snapshots.",
    },
    {
        "code": "products.status.view",
        "name": "View product status",
        "module": "products",
        "action": "status.view",
        "description": "View product status recommendations and transitions.",
    },
    {
        "code": "products.status.evaluate",
        "name": "Evaluate product status",
        "module": "products",
        "action": "status.evaluate",
        "description": "Generate product status recommendations from phase 2 mock metrics.",
    },
    {
        "code": "products.status.confirm",
        "name": "Confirm product status",
        "module": "products",
        "action": "status.confirm",
        "description": "Confirm or reject standard product status recommendations.",
    },
    {
        "code": "products.status.high_risk_confirm",
        "name": "Confirm high-risk product status",
        "module": "products",
        "action": "status.high_risk_confirm",
        "description": "Confirm clearance, stopped, or archived product status recommendations.",
    },
    {
        "code": "system.organization.view",
        "name": "View organization directory",
        "module": "system",
        "action": "organization.view",
        "description": "View tenant-scoped departments and organization structure.",
    },
    {
        "code": "system.organization.manage",
        "name": "Manage organization directory",
        "module": "system",
        "action": "organization.manage",
        "description": "Create and update tenant-scoped departments.",
    },
    {
        "code": "system.users.view",
        "name": "View user directory",
        "module": "system",
        "action": "users.view",
        "description": "View masked tenant-scoped user account metadata.",
    },
    {
        "code": "system.users.manage",
        "name": "Manage user directory",
        "module": "system",
        "action": "users.manage",
        "description": "Create, activate, deactivate, and assign roles to tenant users.",
    },
    {
        "code": "system.roles.view",
        "name": "View roles and permissions",
        "module": "system",
        "action": "roles.view",
        "description": "View tenant roles, permission catalog, and data scopes.",
    },
    {
        "code": "system.roles.manage",
        "name": "Manage roles and permissions",
        "module": "system",
        "action": "roles.manage",
        "description": "Create roles and update tenant role permissions and data scopes.",
    },
    {
        "code": "masterdata.view",
        "name": "View master data",
        "module": "masterdata",
        "action": "view",
        "description": "View tenant-scoped platform, store, warehouse, and supplier archives.",
    },
    {
        "code": "masterdata.manage",
        "name": "Manage master data",
        "module": "masterdata",
        "action": "manage",
        "description": "Create, update, activate, and deactivate tenant master data.",
    },
    {
        "code": "security.operations.view",
        "name": "View security operations",
        "module": "security",
        "action": "operations.view",
        "description": "View masked credential metadata and tenant operation audit summaries.",
    },
)


def permission_defaults(definition):
    return {key: value for key, value in definition.items() if key != "code"}
